Use embedded zxing lib in BarcodeWidget. Fixes #1021
getodk/collect pull request #1035
Opened 2017-05-20 05:19 UTC by MukundAnanthu

Pull request for issue 1021. Uses embedded zxing lib in BarcodeWidget instead of launching intent for an external Barcode scanning app.

2017-05-20 06:17 UTC, shobhitagarwal1612 commented
Hey, Mukund. 
IntentIntegrator only sets up an intent for scanning a barcode. We have to get the results by overriding the onActivityResult method. 
Here, [onActivityResult](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L572) is already overridden in FormEntryActivity. So, you just need to replace the existing code for fetching the results in that method.

```
// sample code
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
    if(result != null) {
        if(result.getContents() == null) {
            // scanning cancelled
        } else {
            String data = result.getContents();
        }
    } else {
        super.onActivityResult(requestCode, resultCode, data);
    }
}
```

Link to [zxing library](https://github.com/journeyapps/zxing-android-embedded#usage-with-intentintegrator)

2017-05-21 17:42 UTC, MukundAnanthu commented
Thanks @shobhitagarwal1612 for the review. Have made some more changes, would love to hear your feedback

2017-05-21 18:23 UTC, shobhitagarwal1612 requested changes

2017-05-21 18:23 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
>                  String sb = intent.getStringExtra("SCAN_RESULT");
This should be replaced with the following line, 
`String sb = barcodeScannerResult.getContents();`

2017-05-21 18:23 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +                return;
This statement makes the `refreshCurrentView()` line at the end of this method ([line 761](https://github.com/MukundAnanthu/collect/blob/27a051c1bf64ea38a0b001b6e2eace8c7c378ab7/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L761)) unreachable.
So you should call this function `refreshCurrentView()` before returning from this method.

2017-05-22 05:30 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
> -                                    R.string.barcode_scanner_error),
Please remove this string from strings.xml file as it's no longer needed.

2017-05-22 14:34 UTC, MukundAnanthu commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
>                  String sb = intent.getStringExtra("SCAN_RESULT");
@shobhitagarwal1612 I actually wrote both statements in the same place just for comparison..i.e 
Line 1: String sb1 = barcodeScannerResult.getContents();
and 
Line 2: String sb2 = intent.getStringExtra("SCAN_RESULT");

Turns out the value stored in sb1 and sb2 are exactly identical.i.e both statements are storing the same value in sb. 

Would you still recommend replacing the current statement
String sb = intent.getStringExtra("SCAN_RESULT"); 
with
 String sb = barcodeScannerResult.getContents();
If yes, why?

2017-05-22 14:51 UTC, MukundAnanthu commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +                return;
@shobhitagarwal1612 Yes, will make this change to ensure refreshCurrentView() is reachable

2017-05-22 14:52 UTC, MukundAnanthu commented on collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
> -                                    R.string.barcode_scanner_error),
@grzesiek2010 Sure!!

2017-05-22 16:55 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
>                  String sb = intent.getStringExtra("SCAN_RESULT");
I am not sure if the later one will work as I used the way it was mentioned in the zxing library documentation. But if it's working then I guess it doesn't matter which one is used.

2017-05-24 02:44 UTC, merged

2017-05-24 02:46 UTC, lognaturel commented
Thank you so much, @MukundAnanthu! This is a way better user experience and hopefully will encourage more organizations to use the power of barcodes.

And fantastic teamwork with @shobhitagarwal1612 and @grzesiek2010 as well! Go team. 😎