Refactors shared preferences
getodk/collect pull request #1036
Opened 2017-05-20 16:10 UTC by shobhitagarwal1612

Resolves #1011

2017-05-22 01:18 UTC, lognaturel commented
At first pass, this approach looks good! I'm going to need to block off some time to go over it more carefully and consider alternatives. Will do that by feature freeze time.

2017-05-25 02:59 UTC, lognaturel requested changes
I think this is a big improvement! And it does appear to fix the crash I was getting which is great.

Couple of things that need fixing marked inline.

We should use these classes whenever prefs are accessed. I think I'd prefer `get` in the admin class to also refer to a `HashMap` with explicit defaults like the one in general prefs. But this can happen later -- refactoring is a constant exercise!

2017-05-25 02:59 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java
>          keys.add(KEY_PASSWORD);
`keySet` doesn't support `add`, see [here](http://docs.oracle.com/javase/7/docs/api/java/util/HashMap.html#keySet%28%29). I think the right thing to do is to use the copy constructor.

2017-05-25 02:59 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceKeys.java
> +    private static HashMap<String, Object> getHashMap() {
Sorry I didn't get back to you sooner --  I do think language should be included. I also notice analytics is missing.

2017-05-25 04:03 UTC, lognaturel approved these changes

2017-05-25 04:05 UTC, merged

2017-05-25 16:39 UTC, shobhitagarwal1612 commented
@lognaturel I didn't use a `hashmap` for admin prefs because the default value for all boolean preferences is `true`

2017-05-25 16:41 UTC, lognaturel commented
@shobhitagarwal1612 That's true... for now! I don't love the idea that adding a new admin pref with a non-true default requires also making sure the get method is updated. On the general prefs side, there's only one change to make which is great. But it's not a very big deal and we can certainly leave it as we keep considering how the preferences menu will evolve.

2017-05-25 16:47 UTC, shobhitagarwal1612 commented
Also with this PR being merged, I think we should refactor the use of shared preferences used elsewhere in the code too.

2017-05-25 16:48 UTC, lognaturel commented
@shobhitagarwal1612 Yes, I agree with you.

2017-05-25 16:54 UTC, shobhitagarwal1612 commented
@lognaturel We should open an issue regarding that to track the status of global refactoring of shared preferences