Settings redesign
getodk/collect pull request #1101
Opened 2017-06-05 20:36 UTC by shobhitagarwal1612

In continuation of #1066

2017-06-05 23:18 UTC, lognaturel commented
Looking great! I hope merging the conflicts isn't too time-consuming.

Two things I noticed are missing: the actual splash screen image and the form metadata.

2017-06-06 13:01 UTC, shobhitagarwal1612 commented
@lognaturel Done

2017-06-08 03:38 UTC, lognaturel commented
Looking good! 

Fonts are pretty small. Are those the Material design standards? Could we just bump everything up by a couple of sp? I changed the font size to large at the device level and that feels very comfortable to me. Maybe those sizes could be the defaults? I'm willing to be talked out of this if you think sticking to standards and helping users change the font size at the device level is better.

Passwords should have a show/hide option. We can also file this as a separate issue and do it as the eye overlay which I think is now standard. Or perhaps dialogs should be handled separately. I notice the color of the dialog buttons are also inconsistent.

Speaking of color inconsistency! I sometimes get a mix of blue and teal on Nexus 5, API 22. Everything is consistently blue on my Moto G4, Android 7.0.0.
<img src="https://user-images.githubusercontent.com/967540/26911159-7790e568-4bc0-11e7-9037-42575ed6e355.png" width=250>

I haven't done a proper review of the code yet but one quick thing I noticed is that there is now only one key for the auto send setting. That's probably the right thing to do but the reason @yanokwa mentioned using the same preference keys is for backwards compatibility. We really don't want users not getting their forms as expected because autosend was turned off without them noticing. Also, if users have the separate settings as part of configuration QR codes, those should still work. You might want to look at `FormMetadataMigrator` for ideas on how to handle that.

2017-06-08 13:13 UTC, shobhitagarwal1612 commented
@lognaturel : 
> Fonts are pretty small

Font size of entire app or just the settings screen?

2017-06-08 17:06 UTC, lognaturel commented
For the font size, I'm talking specifically about the settings screen for now.

2017-06-09 23:05 UTC, lognaturel requested changes
I don't see any code for doing the migration from two autosend preferences to one in the case of a normal update. To verify:
1. `git checkout v1.7.0` and install to device
1. check both "autosend with wifi" and "autosend with network"
1. checkout this branch and install to device
Now I should see "Wifi or cellular" selected for "Autosend" in the form management settings but I don't.

Another small thing I noticed is that if I uncheck everything in Admin Settings > User Settings, the Server category disappears but the other three categories are still there. Form management is clickable but empty.

Other than that, it looks ready to merge! The first one is a must-fix. The second we can file as a separate issue.

2017-06-09 23:05 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> +    private void checkForBackwardCompatility(Map<String, ?> entries, Editor prefEdit) {
A method name that starts with `check` implies it's going to return a boolean. I would name this something like `migrateAutosendPrefKeys`.

2017-06-09 23:05 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/DisabledPreferencesRemover.java
> +        String[] preferenceScreensWithNoChildren = {
Isn't this the list WITH children, not with NO children?

2017-06-10 04:58 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> +    private void checkForBackwardCompatility(Map<String, ?> entries, Editor prefEdit) {
Fixed

2017-06-10 04:59 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/preferences/DisabledPreferencesRemover.java
> +        String[] preferenceScreensWithNoChildren = {
Fixed

2017-06-10 07:29 UTC, shobhitagarwal1612 commented
> I don't see any code for doing the migration from two autosend preferences to one in the case of a normal update. To verify:
> 
> git checkout v1.7.0 and install to device
> check both "autosend with wifi" and "autosend with network"
> checkout this branch and install to device
> Now I should see "Wifi or cellular" selected for "Autosend" in the form management settings but I don't.

Done

2017-06-10 09:21 UTC, shobhitagarwal1612 commented
@lognaturel : 

> Another small thing I noticed is that if I uncheck everything in Admin Settings > User Settings, the Server category disappears but the other three categories are still there. Form management is clickable but empty.

I have fixed this. Although there is still a minute bug left. The form management is visible and clickable if all the preferences are hidden but it hides if any one or more other preferences is/are unhidden.

2017-06-12 16:38 UTC, lognaturel approved these changes

2017-06-12 16:40 UTC, merged

2017-06-12 21:34 UTC, lognaturel commented
I verified that when I check check both auto send settings in v1.7.0, install this branch, then auto send is set to Wifi & Cellular as it should be.

However, when I checked auto send with network in v1.7.0, exported the settings file (Admin settings > menu > Save Settings to Disk), moved the generated file to /sdcard/odk/collect.settings, installed this branch and then launched it, I saw the "settings successfully imported" toast but auto send was still set to "Off" (It should have said "cellular"). This will likely be addressed by #1133 but I also wanted to keep a record of it here.