Crash when loading sample mbtiles file as offline layer
getodk/collect pull request #1172
Opened 2017-06-19 10:36 UTC by grzesiek2010

2017-06-21 04:18 UTC, lognaturel commented
@grzesiek2010 It is nice not to have a crash but I think it's pretty confusing not to have any feedback that the file failed and why it failed! I want to think about this one just a little bit more.

Other feedback appreciated!

2017-06-21 09:08 UTC, grzesiek2010 commented
@lognaturel I've added a toast please review again.

2017-06-22 00:42 UTC, lognaturel requested changes
Couple of small internal changes.

@mmarciniak90 the functionality is there and ready for you to review.

2017-06-22 00:42 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +    <string name="not_supported_offline_layer_format">Selected offline layer file uses PBF format which is not supported!</string>
This should be "uses the PBF format" (with "the"). 😊

2017-06-22 00:42 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java
> +    private boolean isFileFormatSupported(File file) {
Can you please add a little comment here so we remember why this method is here more easily? Might just be "osmdroid doesn't currently support pbf tiles: https://github.com/osmdroid/osmdroid/issues/101"

2017-06-22 08:49 UTC, grzesiek2010 commented
@lognaturel done.

2017-06-25 17:59 UTC, lognaturel approved these changes

2017-06-26 10:25 UTC, mmarciniak90 commented
Tested with success. 
Verified on Android v4.1, v4.2, v4.4, v5.1, v6.0.
ODK does not crash when I load layer from [Example1](https://www.mapbox.com/help/define-mbtiles/) or [Example2](https://openmaptiles.org/downloads/#country). 
Toast with message 'Selected offline layer file uses the PBF format which is not supported!' is visible
![screenshot_20170626-115308](https://user-images.githubusercontent.com/3907554/27535268-7024fb8a-5a6a-11e7-99d1-b710f4eab939.png)
.

2017-06-26 16:25 UTC, merged

2017-10-03 15:06 UTC, mmarciniak90 commented
@opendatakit-bot unlabel "needs testing"