Add All Widgets form link
getodk/collect pull request #1212
Opened 2017-06-27 18:04 UTC by lognaturel

It's useful to have a direct link to both for testing and to keep up to date.

2017-06-30 23:35 UTC, thedavidmccann approved these changes

2017-06-30 23:36 UTC, taylordowns2000 approved these changes
Looks good to go. Style question around lines with more than 80 characters, but won't stop approval ;-)

2017-07-04 00:28 UTC, yanokwa requested changes
I know this is nitpicky, but why not put the All Widgets form first? If it's the one that most people will use, then let's put that first and ask people to make or get other forms if they are so inclined.

2017-07-04 00:39 UTC, lognaturel commented
@yanokwa That's a good idea, done. And thanks, @daveycrockett, @taylordowns2000! Sorry I put you under pressure. Next review will be under more realistic conditions. 😄🙏

2017-07-04 01:08 UTC, merged