Decimal widget display text
getodk/collect pull request #1296
Opened 2017-07-31 01:56 UTC by lognaturel

Fixes #1282.

We need to be really careful with these core widgets so I thought this would be a good place to add some tests. It's really important that the display value is right because it replaces the backing value.

I structured the tests such that the current implementation wouldn't need to be changed. The formatting happens in the widget constructor and so I used a mocked `IAnswerData` to get things going. I think this exercises the code paths I want but it does feel heavyweight. I'd be very interested in some feedback on whether these are reasonable tests and whether there would be a better way to structure them. @grzesiek2010 @srsudar @alxndrsn 

The tests clearly show the issue from #1282 (revert `DecimalWidget` to the version from `master`) and the problems with #1284.

Did I illustrate all the cases?

2017-07-31 09:17 UTC, grzesiek2010 requested changes
Looks ok but we need to fix ExDecimalWidget as well.

2017-08-02 07:25 UTC, shobhitagarwal1612 commented
I tried using these values in the test `decimalValueShouldMaintainPrecision()` 
```
twoDecimalDouble = 9.00
twoDecimalString = "9.00"
```

Observation -
The test failed

Expected - 
The test passes

2017-08-02 15:38 UTC, lognaturel commented
@shobhitagarwal1612 that's a really great point. Unfortunately I don't know that there's any way to store precision for `Double` values in that way, only when doing the display. Perhaps we can document that as a limitation unless someone else knows an approach?

2017-08-02 19:50 UTC, grzesiek2010 approved these changes

2017-08-02 22:33 UTC, yanokwa commented
I can confirm that this fixes the bug I saw in #1282.

2017-08-02 22:33 UTC, merged