Adds pmd rule UseEqualsToCompareStrings
getodk/collect pull request #1448
Opened 2017-09-11 19:49 UTC by shobhitagarwal1612

Adds rule UseEqualsToCompareStrings to pmd-ruleset and fixes raised issues

2017-09-12 00:26 UTC, lognaturel requested changes
:/ This is why these changes make me nervous and why it's good to do them one at a time so they're easier to review.

2017-09-12 00:26 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
> +                    if (value.equals("")) {
This is missing a `!`, right?

2017-09-12 04:10 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
> +                    if (value.equals("")) {
fixed

2017-09-14 20:48 UTC, shobhitagarwal1612 commented
#1465

2017-09-14 20:48 UTC, closed without merging

2017-10-23 14:23 UTC, mmarciniak90 commented
@opendatakit-bot unlabel "needs testing"