Enhance #1674
getodk/collect pull request #1687
Opened 2017-12-04 21:25 UTC by srv-twry

### Work in Progress 

Closes #1674 

#### What has been done to verify that this works as intended?
Tested manually on all the three widgets i.e. Integer, Decimal and StringNumber.

#### Why is this the best possible solution? Were any other approaches considered?
Implemented it as discussed [here](https://github.com/opendatakit/collect/issues/1674).

#### Are there any risks to merging this code? If so, what are they?
Yes, If the user deletes a digit from the middle , then the cursor still moves to the end automatically. Since this is still in progress, i will fix it.

#### Do we need any specific form for testing your changes? If so, please attach one.
No

2017-12-05 00:49 UTC, srv-twry commented
@lognaturel Please review, 
The keyword to be used in the ```appearance``` is `thousand-sep`.

I have only considered the following widgets for this feature:
- Integer
- Decimal
- StringNumber

2017-12-06 16:31 UTC, lognaturel commented
Thank you, @srv-twry!

Form needed for testing: [thousands-separator.xml.txt](https://github.com/opendatakit/collect/files/1535914/thousands-separator.xml.txt) ([xlsx](https://docs.google.com/spreadsheets/d/1pQfeOkiN7nuoLsi_uXcCek2bM7w3vQcF7GSmLopCiLU/edit#gid=0))

I wasn't able to get it to work with numeric text, can you share the form you verified that with?

I notice that having a separator reduces the total number of digits allowed. Without a separator, 9 digits are allowed but with only 7 are. I think it would be better if the number of digits allowed didn't change.

It's really important that we cite sources when pulling in external code! In this case it looks like https://stackoverflow.com/a/34265406/137744 needs credit. You can read more about that [here](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#code-from-external-sources).

How did you pick this particular approach over others either in that thread or other concepts you might have considered?

2017-12-06 17:53 UTC, srv-twry commented
@lognaturel Separator now works with the numeric text and integer widget also accomodates 9 digits now for both with and without appearance.

Yes i agree, I forgot to cite the source. Thank you , I have edited the main comment.

I picked this approach since it was accepted by most number of users and hence was well tested. The issue with the answer accepted by the asker is that it would only work within the range of ```long``` but the approach i have selected uses ```String``` hence would work for any range.

2017-12-06 23:05 UTC, lognaturel requested changes
I started doing a deeper review and saw that the imported code isn't of very high quality. Could you please carefully review and improve it?

2017-12-06 23:05 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/listeners/ThousandSeparatorTextWatcher.java
> +    public static String getDecimalFormattedString(String value) {
This code could be improved and I think it would be worth doing a pass over. For example, I think better variable names would help. I also have a preference for using `split` over a `StringTokenizer`.
```
String[] splitValue = value.split(".");
String beforeDecimal = value;
String afterDecimal = null;
if (splitValue.length == 2) {
  beforeDecimal = splitValue[0];
  afterDecimal = splitValue[1];
}
```

The loop is also very strange. To find the index of the decimal marker, it should be possible to do something like use `indexOf`. Remember that the decimal marker could also be localized so searching for a period isn't right. Rebuilding the parts before and after the decimal should be done after the loop not within it with a break.

I would recommend writing a couple of tests for the desired behavior and then rewriting this method.

I haven't looked at the others in detail but it would be good to do a similar review and improvement.

2017-12-06 23:05 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/listeners/ThousandSeparatorTextWatcher.java
> +    public static String getOriginalString(String string) {
This can be simplified to just `return string.replace(thousandSeparator,"");`. No need to test if it's there before because replacing something that's not there has no effect.

2017-12-06 23:05 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/DecimalWidget.java
> +        //thousand separator
The good variable naming makes a comment here redundant.

2017-12-06 23:05 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/listeners/ThousandSeparatorTextWatcher.java
> + * Created by srv_twry on 4/12/17.
Should say `Source: https://stackoverflow.com/a/34265406/137744`.

2017-12-07 00:48 UTC, srv-twry commented
@lognaturel Wrote the ```getDecimalFormattedString``` method from scratch and other minor changes.

2017-12-08 20:30 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/listeners/ThousandSeparatorTextWatcher.java
> +    * Returns the string back after removing all the thousand separators.
“back” is redundant. “Returns the string” is cleaner.
I think “thousands separators” (plural) is more common than “thousand separators”.

2017-12-08 20:32 UTC, dcbriccetti commented on collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
> +        return new DecimalWidget(RuntimeEnvironment.application, formEntryPrompt, false,false);
Space after comma

2017-12-13 03:12 UTC, lognaturel requested changes
Looking very close, @srv-twry! A few more small comments inline. I would tend to take all the things about leading 0s out but we can certainly talk through it in Slack if you disagree.

Hopefully the conversation at https://forum.opendatakit.org/t/spec-addition-proposal-appearance-for-thousands-separators-in-numeric-fields/10948 will conclude soon so we can have a finalized `appearance` name!

2017-12-13 03:12 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/listeners/ThousandSeparatorTextWatcher.java
> +                if (value.startsWith(decimalMarker)) {
Forcing decimals to start with 0s isn't related to the thousands separators and it doesn't feel necessary to me.

2017-12-13 03:12 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/listeners/ThousandSeparatorTextWatcher.java
> +                if (value.startsWith("0") && !value.startsWith("0" + decimalMarker)) {
It looks like the purpose of this code is to prevent leading 0s from being added. But it always allows one leading 0 because there could be a decimal as the second character. Again, this doesn't feel related to the thousands separators behavior and doesn't feel necessary. 0s get collapsed on save and retrieval anyway so I would prefer to keep this feature really focused on thousands separation!

2017-12-13 03:12 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/listeners/ThousandSeparatorTextWatcher.java
> +    private static String getDecimalFormattedString(String value) {
Thanks, this is much better.

2017-12-13 03:12 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
> +                            questionWidget = new DecimalWidget(context, fep, readOnlyOverride,useThousandSeparator);
@dcbriccetti pointed out one missing space after a comma but there are some more! Please go through and remove all.

2017-12-13 03:52 UTC, srv-twry commented
@lognaturel Removed the constraints related to leading zeroes. Initially i thought it may be an enhancement but i think it might be confusing for some so it's better to remove it.

> Hopefully the conversation at https://forum.opendatakit.org/t/spec-addition-proposal-appearance-for-thousands-separators-in-numeric-fields/10948 will conclude soon so we can have a finalized appearance name!

When it does , i will add it in my code and squash the commits into one with a meaningful message since there are way too many commits right now.

2017-12-13 03:52 UTC, lognaturel commented
:fire:

2017-12-13 19:52 UTC, lognaturel commented
Thanks so much, @srv-twry. Since this is turning out to be quite a popular feature, let's get it in for the beta. I'll squash and merge now and then issue a separate pull request to make the small change in appearance name described at https://forum.opendatakit.org/t/spec-addition-proposal-appearance-for-thousands-separators-in-numeric-fields/10948/8.

2017-12-13 19:53 UTC, lognaturel approved these changes

2017-12-13 19:54 UTC, merged