Avoid . as thousands marker and always use it as decimal marker
getodk/collect pull request #1718
Opened 2017-12-14 23:09 UTC by lognaturel

Closes #1715 

#### What has been done to verify that this works as intended?
Tried decimal with `thousands-sep` appearance in German (. thousands / , decimal), French (" " thousands / , decimal) and US English (, thousands / .decimal). The intent is that German act like French and all locales use . as the decimal marker because of an Android limitation (https://issuetracker.google.com/issues/36907764)

#### Why is this the best possible solution? Were any other approaches considered?
See https://forum.opendatakit.org/t/odk-collect-v1-12-beta/10965/6. I think this provides the most consistent and least confusing behavior. Another approach could be to always use the US English markers but as a French speaker I appreciate space being used as the thousands separator. I think that will be less confusing to people in locales that typically use commas as decimal separators.

#### Are there any risks to merging this code? If so, what are they?
There may be other marker combinations this breaks.

#### Do we need any specific form for testing your changes? If so, please attach one.
[thousands-separator.xml.txt](https://github.com/opendatakit/collect/files/1561056/thousands-separator.xml.txt)

2017-12-14 23:42 UTC, dr0pdb requested changes
Everything works fine except that for Dutch language(period as thousand sep and comma as decimal marker) , the hierarchy view isn't consistent with the form.

### Screenshots:
![screenshot_2017-12-15-05-07-05-24](https://user-images.githubusercontent.com/21277837/34019759-633275ba-e156-11e7-8abc-fb68c721f07f.png)
![screenshot_2017-12-15-05-07-11-07](https://user-images.githubusercontent.com/21277837/34019764-6801f296-e156-11e7-9866-7ad221710c71.png)

2017-12-15 01:37 UTC, lognaturel commented
Hehe, you are good @srv-twry. I did notice that and figured it wasn't important but you're right that it doesn't make much sense to only fix the problem in one place. Fixed and force pushed to keep the history clean.

2017-12-15 01:53 UTC, dr0pdb approved these changes
Works great locally!

2017-12-15 09:59 UTC, mmarciniak90 commented
**Tested with success!**
Verified on Android: 4.1, 4.4, 5.1, 7.0, 8.0.
Verified cases:
- Danish 
![danish](https://user-images.githubusercontent.com/3907554/34036759-9cae8394-e186-11e7-8be3-c00be0830b9b.png)
- Dutch 
![dutch](https://user-images.githubusercontent.com/3907554/34036760-9ccbef88-e186-11e7-81c2-788497f70908.png)
- English 
![english](https://user-images.githubusercontent.com/3907554/34036762-9cea4c26-e186-11e7-97e9-bd025c42c711.png)
- French 
![french](https://user-images.githubusercontent.com/3907554/34036763-9d06dcba-e186-11e7-97d8-a4b596ffd372.png)
- German 
![german](https://user-images.githubusercontent.com/3907554/34036764-9d24ab00-e186-11e7-81e8-86beb44437b7.png)
- Italian 
![italian](https://user-images.githubusercontent.com/3907554/34036765-9d42976e-e186-11e7-94cb-e686d74a6367.png)
- Spanish 
![spanish](https://user-images.githubusercontent.com/3907554/34036767-9d82f0b6-e186-11e7-93bc-756cbee572ef.png)

2017-12-15 10:00 UTC, mmarciniak90 commented
@opendatakit-bot unlabel "needs testing"

2017-12-15 18:49 UTC, merged