Fix commit
getodk/collect pull request #1863
Opened 2018-02-14 13:15 UTC by vrjgamer

+Added "Share" vector icon from  https://material.io/icons/#ic_share.
+Fixed Import/Export Settings menu.

Closes #1857  

#### What has been done to verify that this works as intended?
Steps to be followed
1. Go to Admin Settings -> Import/Export Settings
2. Open the popup menu.
Here you can check the icons in the top bar. Below is a comparison of screens before and after the fix
Before->
![wadasdsa](https://user-images.githubusercontent.com/10618953/36203693-74c2eb42-11ae-11e8-8c70-e6194cd91542.png)
After->
![screen_dark](https://user-images.githubusercontent.com/10618953/36203814-e87c83cc-11ae-11e8-8ea8-d438048235e3.png)

#### Why is this the best possible solution? Were any other approaches considered?
This is the best solution as its using vector graphics instead of PNGs. Vector graphics are more flexible and take less memory. They are automatically resized according to the screen size and pixel density. 
Another approach is to use PNGs but then we have to create different icons to support all screen sizes. 
 
#### Are there any risks to merging this code? If so, what are they?
No, there are no risks in merging my code.
#### Do we need any specific form for testing your changes? If so, please attach one.
No, as there are no forms involved with this screen.

2018-02-14 13:26 UTC, vrjgamer commented
@grzesiek2010 Sir this time, I did a re-fork and started from scratch. I added one vector icon for share icon and made changes only in settings_menu.xml. I don't know why it failed.

2018-02-14 13:32 UTC, grzesiek2010 requested changes

2018-02-14 13:32 UTC, grzesiek2010 commented on collect_app/src/main/res/drawable/ic_menu_share.xml
> +    android:height="24dp"
I think it should be 36dp, not 24. For example, the save icon is bigger.

2018-02-14 13:32 UTC, grzesiek2010 commented on collect_app/src/main/res/menu/settings_menu.xml
> +		/>
Please, inline.

2018-02-14 13:35 UTC, grzesiek2010 commented
> I don't know why it failed.

It might be a random fail it happens you can always click on `Details` above and then `Rerun job` button on CircleCi. (you may need to log in using your Github account)

2018-02-14 13:37 UTC, vrjgamer commented on collect_app/src/main/res/drawable/ic_menu_share.xml
> +    android:height="24dp"
Okay.

2018-02-14 13:48 UTC, grzesiek2010 approved these changes

2018-02-14 13:48 UTC, grzesiek2010 commented
@vrjgamer Looks good thanks. Just change the pr title, please.

2018-02-14 13:49 UTC, grzesiek2010 commented
@opendatakit-bot label "needs testing"

2018-02-14 13:49 UTC, raks097 commented
Hey @vrjgamer @grzesiek2010 
I was observing this thread as I was facing the same issue of the test failing.
Did you have to change any code or does rerunning the test suffice?
If so, How did you rerun it?
It says that I need write permissions to do it.
Thanks in advance! :D

2018-02-14 13:50 UTC, grzesiek2010 commented
> It says that I need write permissions to do it.

Probably you are not logged in. try to log in using your Github account as I said above.

2018-02-14 14:10 UTC, vrjgamer commented
Hi @raks097 @grzesiek2010 
I tried logging in with my github account, but it still said that I need write permissions to trigger builds.
When I submitted my changes on the reviews, it automatically triggered a rebuild and that's how it worked for me :sweat_smile: .

2018-02-14 14:12 UTC, vrjgamer commented
@grzesiek2010 is the pr title okay?

2018-02-14 14:19 UTC, grzesiek2010 commented
> is the pr title okay?

yes, thanks.

2018-02-16 14:22 UTC, mmarciniak90 commented
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.
<img width="40%" src="https://user-images.githubusercontent.com/3907554/36311874-9d6d3f76-1324-11e8-9406-2b0b876acdb4.png">

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2018-02-16 14:39 UTC, shobhitagarwal1612 commented
The title is wrapping due to less space `Import/Export Sett...`. Wouldn't it look better if it is shorter? Maybe `Import / Export`. @lognaturel @grzesiek2010 What do you think?

2018-02-16 14:41 UTC, grzesiek2010 commented
> The title is wrapping due to less space

It was not visible even before I think we don't need that icon. It would give us more space for the title.

2018-02-16 19:51 UTC, lognaturel approved these changes

2018-02-16 19:52 UTC, merged

2018-02-16 19:55 UTC, lognaturel commented
As @grzesiek2010 points out, the wrapping hasn't changed so let's leave as-is for now.