Removed no-value log from FormEntryActivity
getodk/collect pull request #1866
Opened 2018-02-14 20:18 UTC by JainilGada

Closes #
I have removed the following Logs 
>onAnimationStart
>onAnimationEnd
>afterAllAnimations
>OnAnimationRepeat
>CreatingProgressDialog
>CreatingSavingDialog
>DismissDialogs
#### What has been done to verify that this works as intended?
I tested app on my phone and logs on LogCat in Android Studio

#### Why is this the best possible solution? Were any other approaches considered?

#### Are there any risks to merging this code? If so, what are they?
I don't think, as I have removed few log statements

#### Do we need any specific form for testing your changes? If so, please attach one.
no

2018-02-14 20:45 UTC, srv-twry commented
@JainilGada Please link the issue with the PR.

2018-02-15 05:11 UTC, lognaturel commented
Thanks @JainilGada! Please remove the newlines that were added and this will be ready to merge.

2018-02-15 05:48 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +
While you’re in here, why don’t we remove these no-value comments, too. With a modern IDE, or Javadoc, it’s trivially easy to see which interface a method is associated with.
`// Added by AnimationListener interface.` = noise

2018-02-17 07:01 UTC, dcbriccetti commented
I changed the “closes” to the correct issue number.

2018-02-17 07:04 UTC, dcbriccetti requested changes
Ready to go after the requested changes

2018-02-17 19:53 UTC, JainilGada commented
I have removed extra lines and comments

2018-02-18 00:11 UTC, dcbriccetti approved these changes

2018-02-18 00:12 UTC, merged

2018-02-18 00:12 UTC, dcbriccetti commented
Thanks for your improvement!