Fix #1552. Pictures taken by the SelfieWidget are rotated incorrectly on some devices.
getodk/collect pull request #1877
Opened 2018-02-18 06:05 UTC by ShenJack

Closes #1552

What has been done to verify that this works as intended?
Fix #1552. Pictures taken by the SelfieWidget are rotated incorrectly on some devices

Why is this the best possible solution? Were any other approaches considered?
Using official api, and maybe the least code, actually I‘ve just change some number and experession.

Are there any risks to merging this code? If so, what are they?
Maybe not support devices whose front camera isn't 270, I don’t have devices like that.

Do we need any specific form for testing your changes? If so, please attach one.
Test it on more devices, especially whose front camera isn't 270° placed.

2018-02-18 07:03 UTC, dcbriccetti requested changes
Hi! I can confirm that this fixes an upside-down problem when in landscape orientation, on my Nexus 7. I made some suggestions about your comments. Others who know more about this code should also review.

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +     */
I don’t think this comment adds much value, especially the note about the bug fix. We have issues, pull requests, and commit histories to record when bugs are fixed.

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +    * */
I don’t see any value in this comment. The old values will be in the commit history. The doc comment is malformed and misplaced.

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +     * Front Sensor is normally 270.
The back sensor .... (end with period)
The front sensor ...

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +     * {@code return (ORIENTATIONS.get(rotation) + sensorOrientation + 270) % 360;}
No need to record here what the code was.

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +     * The final degrees the jpeg need to be rotated will be the sum degrees of screen orientation and
... the JPEG needs ...

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +     * {@link CameraDevice } 's orientation.Just like the code below.
Space after period, and perhaps not before the apostrophe?

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +     * And orientation is always the degrees something needs to rotate clockwise to be upright.
... always the number of degrees ...
or
... always the angle (in degrees) ...

2018-02-18 07:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
> +        // After bug #1552 fixed on 2018.2.17, we use this orientation expression to amend the camera direction.
No need to mention the bug fix.

2018-02-18 07:27 UTC, ShenJack commented
@dcbriccetti Thanks for your reminder, I'll make changes right away.

2018-02-19 03:53 UTC, dcbriccetti approved these changes
Thanks, @ShenJack. OK, now an Android expert review, please?

2018-02-19 10:53 UTC, grzesiek2010 approved these changes
It should be tested carefully on different devices so I'm going to approve and let our QA test it.

2018-02-20 15:12 UTC, mmarciniak90 commented
**Not all cases are resolved.** 
Despite that, I would suggest to merge this PR because it fixes problem on higher Android versions which are more popular than Android 4.4 and 4.1. I can create a separate issue for mentioned Android versions.
It will be good to have this in newest Collect version.

@S2606 @lognaturel 

| case/device  | Nexus 5X | Samsung S7 | Sony z3 | Nexus 5 | Huawei | Samsung J1 | Infinix | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Android | 8.0 | 7.0 | 6.0 | 6.0 | 5.1 | 4.4 | 4.2 |
| selfie widget, front camera, vertical device orientation | vertical | vertical |vertical |vertical | vertical | **horizontal** | **horizontal** |
| selfie widget, front camera, horizontal device orientation | horizontal | horizontal | horizontal | horizontal | horizontal | horizontal | horizontal |

@opendatakit-bot label "needs discussion"

2018-02-20 17:34 UTC, shobhitagarwal1612 commented
@ShenJack  @grzesiek2010 This PR only fixes the orientation issue in the `Camera2Fragment` class. And if we look at this [line](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java#L169), it is clearly defined that for devices running Android Lollipop (5.0) and above, the `CameraSelfieActivityNewApi` is being used(which uses `Camera2Fragment`) and for other devices `CameraSelfieActivity` is being used (which uses Camera api v1). So that's why, the fix didn't work for Android 4.4 and 4.1 devices.

2018-02-20 18:58 UTC, lognaturel commented
Thanks for taking this on @ShenJack and for the explanation for why the fix is partial, @shobhitagarwal1612. I agree with @mmarciniak90, let's merge this and file an issue for Android <=4.4.

2018-02-20 18:58 UTC, merged

2018-02-21 07:18 UTC, mmarciniak90 commented
New issue #1900 is created.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs discussion"

2018-02-21 07:19 UTC, mmarciniak90 commented
@opendatakit-bot unlabel "needs testing"