Temp1811
getodk/collect pull request #1883
Opened 2018-02-19 10:53 UTC by raks097

Closes #1811 

#### What has been done to verify that this works as intended?
I have run this on my physical Android device and works as intended.
Device Specs:
Sony Xperia C4 Dual E5363 ( Android 6.0)

#### Why is this the best possible solution? Were any other approaches considered?
The previous error message had certain ambiguity in the context of the tag names used in the
message.Those have been changed so that any error message is crisp and clear.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No

2018-02-19 20:03 UTC, lognaturel requested changes

2018-02-19 20:03 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java
> +                                    + " has missing or empty tag(s) : formID ,downloadUrl or name";
The project uses American English conventions so there should be no space before the colon. There should be no space before the comma and a space after it.

2018-02-19 20:03 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java
> +                                        + " has missing or empty tag(s) : form or url";
No space before colon. `url` is an attribute, not a tag. So something like "has missing or empty form name or url attribute" would be better

2018-02-21 13:33 UTC, raks097 commented
Hey @lognaturel 
I pushed a different branch I was working on to fix this issue.
I'm having troubles reverting back
I'll try my level best to revert back or I'll close this PR and put up a new one.
Sorry for causing this confusion.

2018-02-21 13:46 UTC, closed without merging

2018-02-21 13:56 UTC, raks097 commented
@lognaturel 
I'm rebasing my branch and create a new PR.