Make Spinner widget open from start-of-list when nothing is selected
getodk/collect pull request #1955
Opened 2018-02-28 23:40 UTC by iammvaibhav

Closes #1935 

#### What has been done to verify that this works as intended?
Used the form for testing provided In the Issue

#### Why is this the best possible solution? Were any other approaches considered?
AppCompatSpinner by default doesn't provide such functionality, so in order to achieve this, extending AppCompatSpinner was must.

#### Are there any risks to merging this code? If so, what are they?
I don't think so.

#### Do we need any specific form for testing your changes? If so, please attach one.
[selectOneMinimal.xml.txt](https://github.com/opendatakit/collect/files/1769226/selectOneMinimal.xml.txt)

2018-03-01 02:26 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/CustomSpinner.java
> + */
Please replace this comment with a description of the class. The very top should have a copyright notice with your name (you are the copyright holder) -- https://github.com/opendatakit/collect/blob/master/LICENSE.md#appendix-how-to-apply-the-apache-license-to-your-work

2018-03-01 02:28 UTC, lognaturel requested changes
Thanks, @iammvaibhav! I've made a few comments inline.

2018-03-01 02:28 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/CustomSpinner.java
> +public class CustomSpinner extends AppCompatSpinner {
What would a more descriptive name be? How about `ScrolledToTopSpinner` or something like that?

2018-03-01 02:28 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/CustomSpinner.java
> +    private boolean toggleFlag = true;
This should also have a more descriptive name. I would call it `spinnerClicked` and have it start as `false`. It's confusing that the condition in `getSelectedItemPosition` is negated.

2018-03-01 03:00 UTC, iammvaibhav commented
Thank You @lognaturel for suggestions. I have made the required changes.

2018-03-01 04:05 UTC, iammvaibhav commented
I have no idea why build_debug is failing on CircleCI. The logs aren't helpful either.
I ran the same task `./gradlew pmd checkstyle lint findbugs` on my computer and it the build was successful.

2018-03-02 11:20 UTC, mmarciniak90 commented
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.

Verified cases: 
* new form
* saved form
* both device orientations

New, related issue was created - #1960 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2018-03-02 23:36 UTC, lognaturel approved these changes

2018-03-02 23:36 UTC, merged

2018-03-02 23:37 UTC, lognaturel commented
Thanks, @iammvaibhav! The failure was due to the continuous integration server running out of memory. I simply re-ran it and it passed.