Fix : Error logs in code segments
getodk/collect pull request #1968
Opened 2018-03-05 08:49 UTC by sashank27

Closes #1956

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?
Uses `Timber.d` and `Timber.i` in place of `Timber.e`.
#### Are there any risks to merging this code? If so, what are they?
No
#### Do we need any specific form for testing your changes? If so, please attach one.
No

@lognaturel @grzesiek2010 please review

2018-03-08 20:18 UTC, lognaturel requested changes
One quick change and the rest looks good to me!

2018-03-08 20:18 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/location/client/AndroidLocationClient.java
> -        Timber.e("Can't set updateInterval on AndroidLocationClient. You should check canSetUpdateIntervals before calling this method.");
Calling `setUpdateIntervals` would actually be an error in Collect code so this should be logged at level `e`.

2018-03-08 20:49 UTC, sashank27 commented
did the changes @lognaturel . Please review

2018-03-09 00:15 UTC, lognaturel approved these changes

2018-03-09 00:15 UTC, merged