Background color change can be removed. Fix #1975
getodk/collect pull request #1987
Opened 2018-03-08 07:02 UTC by hossamnasser938

Closes #1975

#### What has been done to verify that this works as intended?
Tested on physical device (Samsung galaxy J5) and some emulators.

#### Why is this the best possible solution? Were any other approaches considered?
@lognaturel said "Yes, I agree that highlighting the text is a sufficient indicator that audio is playing and that the background color change can be removed. " so I simply removed the code that changes the color of the background.

#### Are there any risks to merging this code? If so, what are they?
Because this issue is about removing unwanted highlighting which solved by deleting some lines of code so you might need to check whether that deletion affects something else or not.

#### Do we need any specific form for testing your changes? If so, please attach one.
'Birds' form can be tested.

2018-03-08 14:23 UTC, grzesiek2010 commented
and where is that change with our tint color instead of blue?

2018-03-08 14:26 UTC, grzesiek2010 requested changes
and where is that change with our tint color instead of blue?

2018-03-08 15:56 UTC, hossamnasser938 commented
@grzesiek2010 When I add it the commit fails to build by CircleCi however in builds and runs correctly on my side

2018-03-08 18:41 UTC, grzesiek2010 commented
so check reports and solve the issue from CircleCi. It's not a solution to remove a part of required changes.

2018-03-08 19:08 UTC, hossamnasser938 commented
Ok @grzesiek2010  I'm on it.

2018-03-08 19:59 UTC, hossamnasser938 commented
@grzesiek2010 Can you review now, please

2018-03-08 20:18 UTC, lognaturel approved these changes

2018-03-09 01:03 UTC, grzesiek2010 approved these changes

2018-03-12 12:39 UTC, mmarciniak90 commented
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2018-03-12 15:54 UTC, merged

2018-03-12 15:57 UTC, hossamnasser938 commented
Now I should delete the branch, right?