Address inconsistency between SelectOne widgets ,fix issue #1855
getodk/collect pull request #2026
Opened 2018-03-16 06:10 UTC by huangyz0918

Closes #1855 

#### What has been done to verify that this works as intended?

I have readed others' discuss about this problem and I think it's easy to achieve this goal, so I check the `SelectOneImageMapWidget.java` which calls the `svg _map_helper.js` by an internal Java interface `@android.webkit.JavascriptInterface` and founded that the only way to address this issue is to modify the Javascript file which called by Java methods.

So I modified the function : `clickOnArea(areaId)` in `svg _map_helper.js` which is related to the twice-click action ( you can check codes in my branch `issue#1855` )

Here you can see the demos:

Single-selection mode:
![single mode](https://i.loli.net/2018/03/16/5aab55e98efa9.gif)

Multiple-selections mode:
![multiple mode](https://i.loli.net/2018/03/16/5aab55d14878e.gif)

#### Why is this the best possible solution? Were any other approaches considered?

We use a Android WebView to display the map and it related to the JavaScript injection in Android, so it's likely the only way to address this issue is changing logic inside the Javascript file because of the isolation between Android package and js.

I think it may exist other approaches to meet these requirtments but it maybe more complex than this solution.

#### Are there any risks to merging this code? If so, what are they?

From the tests I have done before submiting pull request, I think the new project has no risks than previous work:

1. I have only modified the logic inside `svg _map_helper.js` ,with the same `JavascriptInterface` that java methods called, it won't impact the logic of Java.

2. I considered either `Single-option Mode` and `Multiple-options Mode`, they all have past the testing and work well.

#### Do we need any specific form for testing your changes? If so, please attach one.

I think you don't have to test more, just review the code and run on several devices .
I think it's okey if you are willing to take futher testing :)

2018-03-16 10:13 UTC, grzesiek2010 requested changes
It looks ok but please clean the code and your branch because you have unrelated changes here.

2018-03-16 10:13 UTC, grzesiek2010 commented on collect_app/src/main/assets/svg_map_helper.js
> +            }else{
space before and after `else`

2018-03-16 10:13 UTC, grzesiek2010 commented on collect_app/src/main/assets/svg_map_helper.js
> +        }else{
space before and after `else`

2018-03-16 10:13 UTC, grzesiek2010 commented on collect_app/src/main/assets/svg_map_helper.js
> +        if (Boolean(isSingleSelect)){
space before `{`

2018-03-16 10:22 UTC, huangyz0918 commented
@grzesiek2010 okey 
I will format the js code right now

2018-03-16 11:18 UTC, grzesiek2010 approved these changes

2018-03-16 11:18 UTC, grzesiek2010 commented
@opendatakit-bot label "needs testing"

2018-03-16 11:27 UTC, huangyz0918 commented
@grzesiek2010 I think I got sufficient testing already
do you suggest I need do more testing ? that I am not sure about that
I'm new and please advise ,thanks : )

2018-03-16 11:54 UTC, grzesiek2010 commented
`needs testing` means it's ready to test by our QAs.

2018-03-21 15:23 UTC, mmarciniak90 commented
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

Verified cases: 
* Image select one widget
* Image select multiple widget
* Other select one widgets available in `All widgets` form
* Other select multiple widgets available in `All widgets` form
* New and saved form

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2018-03-21 17:26 UTC, shobhitagarwal1612 approved these changes
@huangyz0918 Welcome to ODK and congrats on your first PR! :100:

2018-03-21 17:27 UTC, merged