Media files are lost when user changes them but then ignores the changes
getodk/collect pull request #2053
Opened 2018-03-23 18:40 UTC by grzesiek2010

Closes #2049 

#### What has been done to verify that this works as intended?
I tested mentioned scenario.

#### Why is this the best possible solution? Were any other approaches considered?
My second idea was to just get rid of removing media files at all during filling a form and then at the end check all answers and remove unused media files but it might be too complex (too much time needed) when a form is really big or user changed media files many times, so I decided to implement such a singleton.

#### Are there any risks to merging this code? If so, what are they?

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with media questions

2018-04-06 00:35 UTC, lognaturel requested changes
Some commenting and naming changes would help make this clearer but looks good overall!

2018-04-06 00:35 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java
> +    public void markOriginalFileOrDelete(String index, String fileName) {
`questionIndex` would help make this a little more explicit.

2018-04-06 00:35 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java
> +    public void markRecentFile(String index, String fileName) {
It's not clear from the name that this may also delete a file. Maybe something like `replaceRecentFileForQuestion`?

2018-04-06 00:35 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java
> +    public void markRecentFile(String index, String fileName) {
Or is it really `replaceCurrentFileForQuestion`?

2018-04-06 00:35 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java
> +public class MediaManager {
It would be very helpful to have a comment on this class.

2018-04-06 00:35 UTC, lognaturel commented
Marking for testing since none of the changes modify behavior.

2018-04-18 13:55 UTC, kkrawczyk123 commented
### Tested with success!
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2018-04-18 18:10 UTC, lognaturel approved these changes

2018-04-18 18:10 UTC, merged