separator lines added to SelectOneSearchWidget. fix #1976
getodk/collect pull request #2072
Opened 2018-03-28 23:13 UTC by Hanan194

separator lines in SelectOneWidget are created using the function createMediaLayout which contains the devider that creates separator lines, this function isn't called when creating SelectOneSearchWidget layout so we don't have separator lines in it as in the SelectOneWidget layout.
I added this function to SelectOneSearchWidget and now there're separator lines as in the SelectOneWidget

2018-03-29 07:02 UTC, Hanan194 commented
@grzesiek2010

2018-03-29 10:08 UTC, grzesiek2010 commented
@Hanan194 please fill the description using our template you saw creating this pr.

2018-03-29 10:40 UTC, Hanan194 commented
sorry but I don't know what's this template

2018-03-29 11:04 UTC, huangyz0918 commented
You can take a look at other PRs

2018-03-29 11:05 UTC, grzesiek2010 commented
https://github.com/opendatakit/collect/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2018-03-31 15:11 UTC, Hanan194 commented
@grzesiek2010  I modified the description based on the template. is it good for solving the issue you talk about on #1976  ?

2018-04-04 07:58 UTC, grzesiek2010 requested changes
@Hanan194 

I took a quick look at your changes and it causes regression.

1. Select any answer
2. Use the search box adding any char

Selected answer disappears.

2018-04-12 03:16 UTC, closed without merging