Add margin to GeoPoint Layout, fix #1181.
getodk/collect pull request #2094
Opened 2018-04-05 04:51 UTC by huangyz0918

Closes #1181 

#### What has been done to verify that this works as intended?
It's a mathematical problem. 
When building a layout file, each button has `padding="15dp"` and `layout_margin="5dp"` attributes. So we need to calculate an appropriate top margin. In this occasion, `20dp` works well.

|   **Initial**         |  **Scrolling**   |
| ---- | :----: |
|<img src="https://i.loli.net/2018/04/05/5ac5a9850b3ba.png" width = "300" align=center />|<img src="https://i.loli.net/2018/04/05/5ac5a9993312c.png" width = "300" align=center />|

Tested in such screen resolutions:
|   480x800      |  230x320   | 720x1280   | 1920x1080   |
| ---- | ---- | ---- | :----: |
|<img src="https://i.loli.net/2018/04/05/5ac5a9e117dc6.png" width = "300" align=center />|<img src="https://i.loli.net/2018/04/05/5ac5a9fe72918.png" width = "300" align=center />|<img src="https://i.loli.net/2018/04/05/5ac5aa27e83d5.png" width = "300" align=center />|<img src="https://i.loli.net/2018/04/05/5ac5aa4713e28.png" width = "300" align=center />|

#### Why is this the best possible solution? Were any other approaches considered?

#### Are there any risks to merging this code? If so, what are they?
No. 
#### Do we need any specific form for testing your changes? If so, please attach one.
Forms with such maps.

2018-04-06 20:44 UTC, lognaturel approved these changes

2018-04-12 09:47 UTC, grzesiek2010 requested changes
I see you fixed geopint_osm_layout only but it's related to other map layouts as well, for example in the issue I can see screenshots from google maps (that's a different layout)

2018-04-12 09:47 UTC, grzesiek2010 commented
@opendatakit-bot unlabel "needs testing"

2018-04-12 11:07 UTC, huangyz0918 commented
@grzesiek2010 Thanks for reminding !
 It's ready for a review now.

2018-04-12 11:31 UTC, grzesiek2010 commented
It's still not enough since you fixed only geopint layouts but geotrace and geoshape have their own :smile: 

And the second thing is that I would expect deeper layout changes here. You have just added `layout_marginTop="20dp"` but in this case, it's 20dp from the top of the screen what is not perfect and may be not enough if we for example change that info text to longer.

So I would like to refactor that layouts to be able to use a margin from the info layout not from the top of the screen and maybe share some code since we have lots of similar layouts
geopoint, geotrace, geoshape for GoogleMaps
geopoint, geotrace, geoshape for OSM

9 layout's as I know.

2018-04-12 11:48 UTC, huangyz0918 commented
@grzesiek2010 Yeah you are right, I skipped `geotrace` and `geoshape` because the header are short (means they won't touch the button view), so I only added the margins to the `geopoint`. 

It's a quick fix, but may cause the **button view** and the **header** have different proportions in different resolutions. Thanks for your suggestion and I'll refactor this. (and adapt to all those layouts)

2018-04-12 13:48 UTC, huangyz0918 commented
@grzesiek2010 As you said, I took a deeper look in those layouts:
**Don't need change:** (means this issue won't happen in these layouts)
- geotrace

**Do need refactor:**
- geopoint
- geoshape

And I also test new solution in different resolutions, it work very good ! 
So please review (sorry to ask your review so frequently, but I have to say your suggestions are awesome!)

2018-04-13 07:38 UTC, grzesiek2010 commented
> So please review (sorry to ask your review so frequently, but I have to say your suggestions are awesome!)

No worries I enjoy this part of my job as well.

Generally this his is what I wanted. Maybe 20dp is too much here? There is a pretty big gap in your screenshot.

2018-04-13 14:38 UTC, huangyz0918 commented
@grzesiek2010 I adjusted the padding to `10dp` and adapted to all layouts. It looks better.
I think it’s ready for a testing.

2018-04-14 07:16 UTC, shobhitagarwal1612 commented on collect_app/src/main/res/layout/activity_geo.xml
> +        android:paddingTop="10dip">
Attributes `layout_gravity`,  `padding_bottom` & `padding_top` are not required now

2018-04-14 07:18 UTC, shobhitagarwal1612 commented on collect_app/src/main/res/layout/geopoint_layout.xml
> +        android:paddingTop="10dip">
Attributes `layout_gravity`, `paddingBottom` & `paddingTop` are not required now

2018-04-14 07:18 UTC, huangyz0918 commented on collect_app/src/main/res/layout/activity_geo.xml
> +        android:paddingTop="10dip">
Thanks for a review. Copy that and will update soon !

2018-04-14 07:44 UTC, huangyz0918 commented on collect_app/src/main/res/layout/geopoint_layout.xml
> +        android:paddingTop="10dip">
@shobhitagarwal1612 I think we can remove all the paddings since the button view won’t touch the header again, what’s your opinion?

2018-04-14 08:24 UTC, shobhitagarwal1612 commented on collect_app/src/main/res/layout/geopoint_layout.xml
> +        android:paddingTop="10dip">
Are you referring to the padding added to the image buttons or just the padding of the view group layouts?

2018-04-14 08:34 UTC, huangyz0918 commented on collect_app/src/main/res/layout/geopoint_layout.xml
> +        android:paddingTop="10dip">
All `paddingTop`s and `paddingBottom` under `ScrollView` in those 7 layouts

2018-04-14 08:34 UTC, huangyz0918 commented on collect_app/src/main/res/layout/geopoint_layout.xml
> +        android:paddingTop="10dip">
All `paddingTop`s and `paddingBottom` under `ScrollView` in those 7 layouts

2018-04-14 09:30 UTC, shobhitagarwal1612 commented on collect_app/src/main/res/layout/geopoint_layout.xml
> +        android:paddingTop="10dip">
:+1:

2018-04-14 10:21 UTC, huangyz0918 commented
Paddings removed ! Screenshots attached:

|   230x320  Scrolling      |  230x320  Initial    |
| ---- | :----: |
|<img src="https://i.loli.net/2018/04/14/5ad1d5fe086d4.png" width = "300" align=center />|<img src="https://i.loli.net/2018/04/14/5ad1d5ef9a460.png" width = "300" align=center />|

@grzesiek2010 @lognaturel @shobhitagarwal1612 please review

2018-04-17 03:26 UTC, huangyz0918 commented
@opendatakit-bot  label "needs review"

2018-04-18 10:13 UTC, grzesiek2010 approved these changes

2018-04-18 10:13 UTC, grzesiek2010 commented
@opendatakit-bot label "needs testing"

2018-04-19 13:52 UTC, kkrawczyk123 commented
### Bugs have been found!
Buttons don’t overlap the header anymore on Androids: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0 And 8.1 which is good, but:
- geopoint type with placement-map appearance: 2 upper buttons are disabled on Androids: 4.1, 4.2, 4.4, 
![screenshot_2018-04-19-15-21-45](https://user-images.githubusercontent.com/33342488/38995566-7b24ea0e-43e9-11e8-8170-2d2f15f0e3d1.png)

- geopoint type with maps appearance: 2 upper buttons are disabled on Androids: 4.1, 4.2, 4.4, 
(same as on screenshot above)
- geopoint type with no appearance: 1st and 4th buttons are disabled on Androids: 4.1, 4.2, 4.4, 

![screenshot_2018-04-19-15-38-03](https://user-images.githubusercontent.com/33342488/38995611-950137f2-43e9-11e8-85b5-a826e428a9ee.png)

@opendatakit-bot unlabel "needs testing"

2018-04-19 14:08 UTC, huangyz0918 commented
Thanks for your thorough checks @kkrawczyk123 
I'll take a look at these bugs.

2018-04-20 04:51 UTC, huangyz0918 commented
I think these are new bugs which means they are not introduced by the changes here. @kkrawczyk123
 
I also tested the ODK Collect 1.14.1 from Google Play store and these buttons were disabled too. Besides, the 3rd screenshot attached was from `Start GeoTrace` where I haven't done any changes to that. So I hope you can take a second test to these and if they are new bugs please open an issue if possible. 

**ODK Collect v1.14.1**

| geopoint type with placement-map appearance | geopoint type with maps appearance |geotrace type with no appearance |
| :------------: |:---------------:|:-----:|
| ![2018-04-20 12 40 48](https://user-images.githubusercontent.com/15646062/39031059-b1b8ffba-4498-11e8-9aeb-7b1ea0c9817d.png)| ![2018-04-20 12 41 16](https://user-images.githubusercontent.com/15646062/39031066-ba687e6a-4498-11e8-9224-03237e907078.png) | ![2018-04-20 12 42 03](https://user-images.githubusercontent.com/15646062/39031053-a6c307a4-4498-11e8-9dc7-0a4f015da522.png)|

thanks.

BTW, I think I have discovered a new bug if you are using `OpenStreetMap SDK` and scaling the map view like this:

<img src="https://user-images.githubusercontent.com/15646062/39031179-3bd2e148-4499-11e8-9eb1-c5401486342f.png" width = "300"  align=center />

2018-04-20 10:59 UTC, kkrawczyk123 commented
@huangyz0918 I investigated that too and you are completely right !! I tested you changes again and it all looks good to me!

@opendatakit-bot label "behavior verified"

2018-04-20 12:04 UTC, huangyz0918 commented
@opendatakit-bot unlabel "needs review"

2018-04-20 18:36 UTC, merged