Fixed toggleButton in FormDownloadList, fix #2131
getodk/collect pull request #2133
Opened 2018-04-17 16:01 UTC by huangyz0918

Closes #2131 

#### What has been done to verify that this works as intended?
- A hot fix for toggleButton
- Set default value to `checked` (I think it's unnecessary, but I still followed the expected behavior in issue description)

You can find some details in commit message (with a cute emoji) ; )
Screen record attached:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15646062/38881842-5ef11ef6-429b-11e8-851b-05f187a40f96.gif)

#### Why is this the best possible solution? Were any other approaches considered?
This is the best one !
#### Are there any risks to merging this code? If so, what are they?
No.
#### Do we need any specific form for testing your changes? If so, please attach one.
No.
#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
N/A

2018-04-18 09:25 UTC, grzesiek2010 commented
@huangyz0918 

if you check git history you can find that lines you removed were added here https://github.com/opendatakit/collect/pull/1938 to solve this issue https://github.com/opendatakit/collect/issues/1919
 so your solution fixes this issue but introduces regression when it comes to https://github.com/opendatakit/collect/issues/1919 :wink:

2018-04-18 09:26 UTC, grzesiek2010 requested changes
if you check git history you can find out that lines you removed were added here https://github.com/opendatakit/collect/pull/1938 to solve that issue https://github.com/opendatakit/collect/issues/1919
 so your solution fixes this issue but introduces regression when it comes to https://github.com/opendatakit/collect/issues/1919 :wink:

2018-04-18 11:43 UTC, huangyz0918 commented
Haha, I haven't noticed that, thanks for reminding.
I found I can fix this by only one line 😄 @grzesiek2010 ,now it's ok for review.

2018-04-18 11:48 UTC, huangyz0918 commented
Current behavior:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15646062/38930151-7263ddec-4341-11e8-98b0-aa7d30861027.gif)

2018-04-19 12:35 UTC, grzesiek2010 commented
@huangyz0918 it's still not a solution. Your change causes that all forms are selected even those we have already downloaded.

2018-04-19 12:42 UTC, huangyz0918 commented
@grzesiek2010 As my understanding, is this the expected behavior we want ? (described in issue #2131 ). 

> Go back to Get Blank forms. (I expected all forms will be chosen and clear all button will be enabled, screenshot attached)

2018-04-19 12:50 UTC, huangyz0918 commented
I’ll add a listener if you think we need to select only those forms we have not downloaded. From my perspective, this solution is the expected behavior mentioned already. 😄 
@opendatakit-bot  label "needs discussion" 
If you feel that is ok, please remove the `needs discussion`, thank you.

2018-04-19 12:52 UTC, grzesiek2010 commented
It was a bug in the description. This issue is just about the button that should be enabled but is disabled.

2018-04-19 12:52 UTC, grzesiek2010 commented
@opendatakit-bot unlabel "needs discussion"

2018-04-19 12:59 UTC, huangyz0918 commented
Yes, exactly. @grzesiek2010 it’s caused by the code added in #1938 ,so what’s you opinion? I think current solution has already matched the requirements mentioned in this issue.

2018-04-19 13:02 UTC, grzesiek2010 commented
As I said your changes cause that all forms are selected by default what is not acceptable. Only new forms should be selected.

2018-04-19 13:04 UTC, huangyz0918 commented
You are right👌 @grzesiek2010 
I will add a listener and improve this soon.

2018-04-19 15:03 UTC, huangyz0918 commented
@grzesiek2010 please review, thanks.

2018-04-20 12:57 UTC, grzesiek2010 commented
Yes, this is it. Could you just fix the second occurrence of the same line:
`toggleButton.setEnabled(listView.getCount() > 0);`

because it also doesn't make sense (this button can't rely on the number of checked items). Probably you can fix both in the same way.

2018-04-20 13:00 UTC, huangyz0918 commented
@grzesiek2010 oh yes, will do that after my exam tomorrow 😁 
Thanks for so detailed review. I just fixed the current bug but didn’t notice more. 👍

2018-04-21 07:23 UTC, huangyz0918 commented
In `onCreate()`, both `getCheckedItemCount() ` and `getCount()` will return `0` because the list is not loaded yet during activity's creation. So I set this parameter to `false` for a easier reading.
It's ok for a review @grzesiek2010 , thanks.

2018-04-23 09:07 UTC, grzesiek2010 commented
@opendatakit-bot label "needs testing"

2018-04-23 09:07 UTC, grzesiek2010 approved these changes

2018-04-23 12:10 UTC, mmarciniak90 commented
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

Verified cases:
* refreshing
* not downloaded forms are selected as default
* changing device orientation

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2018-04-24 18:58 UTC, lognaturel approved these changes

2018-04-24 18:59 UTC, merged