Replace icons using svg
getodk/collect pull request #2140
Opened 2018-04-19 13:56 UTC by nani92

Closes #2068 

#### What has been done to verify that this works as intended?
Application was tested on my physical device. All SVGs were displayed correctly.
 
#### Why is this the best possible solution? Were any other approaches considered?

#### Are there any risks to merging this code? If so, what are they?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

2018-04-20 11:54 UTC, grzesiek2010 commented
@nani92 
Good job! Congrats on your first pull request!

I can see only one small problem:
your ic_distance icon is bigger than the original one:

current master branch:
![screenshot_2018-04-20-13-50-40](https://user-images.githubusercontent.com/3276264/39049566-46ec386e-44a2-11e8-890f-86a0018dedc2.png)

your branch:
![screenshot_2018-04-20-13-47-23](https://user-images.githubusercontent.com/3276264/39049563-44db774c-44a2-11e8-88d5-afed26a429cc.png)

I think it should be 36dp like other icons.

2018-04-20 11:56 UTC, grzesiek2010 commented on collect_app/src/main/res/drawable/ic_add_location_black.xml
> +        android:viewportHeight="36.000001">
Could it be just 36 in 4 lines above? I think that 000001 doesn't change anything.

2018-04-20 12:02 UTC, grzesiek2010 commented
And another thing... it's my fault because of I didn't list that icon in the description but `ic_pause_black_36dp` is also used in the same places and it's png. Would you like to fix that one also?

2018-04-20 12:11 UTC, grzesiek2010 commented
It's my fault because I missed it in the description but now I realized there three other icons used in the same activities:
`ic_pause_black_36dp.png`
`polygon.png`
`polyline.png`

would you like to fix them too? If not we can do that in a separate pull request but it looks as if you are good at it so probably it's not a problem for you :wink:

2018-04-21 12:59 UTC, nani92 commented
Sorry about wrong size. I'll fix it. 
I'll replace remaining icons as well. ;)

2018-04-21 13:20 UTC, grzesiek2010 commented
> Sorry about wrong size. I'll fix it.
I'll replace remaining icons as well. ;)

:+1: 

please notice also there are conflicts to solve because we have merged another pull request that changed the same classes.

2018-04-23 22:06 UTC, grzesiek2010 commented
I tested your changes on two devices. Everything looks ok on Android 5.0.1 but there is a crash on Android 4.2. Please take a look:

> FATAL EXCEPTION: main
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{org.odk.collect.android/org.odk.collect.android.activities.GeoTraceOsmMapActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2255)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:157)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             at android.os.Looper.loop(Looper.java:176)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5317)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                             at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                             at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:360)
                                                                             at android.app.Activity.setContentView(Activity.java:1932)
                                                                             at org.odk.collect.android.activities.GeoTraceOsmMapActivity.onCreate(GeoTraceOsmMapActivity.java:109)
                                                                             at android.app.Activity.performCreate(Activity.java:5326)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309) 
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:157) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                             at android.os.Looper.loop(Looper.java:176) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5317) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:593)
                                                                             at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                             at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:360) 
                                                                             at android.app.Activity.setContentView(Activity.java:1932) 
                                                                             at org.odk.collect.android.activities.GeoTraceOsmMapActi [...]

2018-04-27 07:42 UTC, nani92 commented
Hi,
I don't have jelly device and because of known issue I'm not able to run  emulator. See here: https://github.com/opendatakit/collect/issues/706 

The lowest API i could use on emulator is kitkat. Error occurred there as well and now is fixed.

2018-04-27 11:51 UTC, grzesiek2010 commented
@nani92 
unfortunately, the same crash still occurs.

2018-04-27 12:53 UTC, grzesiek2010 requested changes
@nani92
unfortunately, the same crash still occurs.

2018-04-27 13:16 UTC, nani92 commented
My bad :( Sorry for that.
Should be fine now.

2018-04-27 13:27 UTC, huangyz0918 commented
@nani92 I guess you faced a random CI problem, I think you can add an extra commit to redo the CI and pass the check 😄

2018-04-27 13:28 UTC, grzesiek2010 commented
> I think you can add an extra commit to redo the CI and pass the check 

you can just click `Rerun job` button.

2018-04-27 13:37 UTC, lakshyagupta21 commented
> you can just click Rerun job button

@grzesiek2010 I'm not sure if @nani92 has the privilege to rerun the job, only admins have access to that button.

@nani92 You can still rerun the CI without adding any extra commit by changing the latest commit name and followed by force push.
You can find more at [this link](https://help.github.com/articles/changing-a-commit-message/)

2018-04-27 13:39 UTC, nani92 commented
@grzesiek2010  if you talking about "Rerun job with SHH" on CircleCI page it's disabled for me and says I need write permissions.

2018-04-27 13:40 UTC, grzesiek2010 commented
Thanks! now it looks good. But it would be good to add more info about the problem we ran into. I mean you can edit your commit message describing which Android versions need that wrappers or you can add comments just in files. I think it's needed because it will allow us to remove those wrappers one we stop supporting affected Android versions.

2018-04-27 13:40 UTC, grzesiek2010 commented
> if you talking about "Rerun job with SHH" on CircleCI page it's disabled for me and says I need write permissions.

you must be logged in using the same Github account (I mean in CircleCI).

2018-04-27 13:40 UTC, nani92 commented
Thanks @lakshyagupta21 i'll try it right away. :)

2018-04-27 13:43 UTC, grzesiek2010 commented
> I'm not sure if @nani92 has the privilege to rerun the job, only admins have access to that button.

I'm not an admin and I have like lots of other contributors. Everyone can rerun their own job on their own branch.

2018-04-27 13:44 UTC, nani92 commented
> Thanks! now it looks ok. But it would be good to add more info about the problem we ran into. I mean you can edit your commit message describing which Android versions need that wrappers or you can add comments just in files. I think it's needed because it will allow us to remove those wrappers one we stop supporting affected Android versions.

Sure @grzesiek2010 ! will do it :)

2018-05-07 08:51 UTC, grzesiek2010 approved these changes

2018-05-08 14:13 UTC, kkrawczyk123 commented
###Tested with success!

Verified on Androids: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2018-05-08 15:41 UTC, lognaturel approved these changes

2018-05-08 15:42 UTC, merged

2018-05-08 15:43 UTC, lognaturel commented
Thank you very much @nani92! If you haven't already, consider joining the developer Slack at http://slack.opendatakit.org/ and checking out the forum at https://forum.opendatakit.org/.