Toggle button in "Send Finalized Form" and "Delete Saved Form"
getodk/collect pull request #2157
Opened 2018-04-26 12:55 UTC by lakshyagupta21

Closes #2153 

#### What has been done to verify that this works as intended?
Tested on a physical device (Android 7.1) and behaviour found correct

#### Why is this the best possible solution? Were any other approaches considered?
Button label is refreshed before listview is updated, I've added label change method in `onLoadFinished` so that it changes when the list gets updated.

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
No

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No

2018-04-27 12:52 UTC, grzesiek2010 requested changes
`Select all` button is disabled after searching:

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/3276264/39363411-822885e4-4a2a-11e8-8c3e-7bae26ce9a61.gif)

2018-04-27 15:02 UTC, huangyz0918 approved these changes

2018-04-27 15:14 UTC, huangyz0918 commented
@opendatakit-bot label "needs testing"

2018-05-07 09:21 UTC, grzesiek2010 approved these changes

2018-05-07 14:02 UTC, mmarciniak90 commented
**Tested with success**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0.

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

2018-05-07 16:11 UTC, lognaturel approved these changes

2018-05-07 16:12 UTC, merged