FIx #2159 The user is not able to add audio and video from Google Drive.
getodk/collect pull request #2189
Opened 2018-05-13 09:51 UTC by ShenJack

FIx #2159 The user is not able to add audio and video from Google Drive.

2018-05-16 07:25 UTC, jd-alexander requested changes

2018-05-16 07:25 UTC, jd-alexander commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +        String instanceFolder1 = Collect.getInstance().getFormController()
Is there a special reson why this variable is called `instanceFolder1` instead of just `instanceFolder`? I see that `instanceFolder` is being used as a local variable in another function but that shouldn't affect this one, so it would be good if the 1 is removed because as soon as I saw it I started looking for `instanceFolder2` :smile:

2018-05-16 07:25 UTC, jd-alexander commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +        Cursor returnCursor =
It would probably be alot cleaner to wrap the usage of this `Cursor` using [try with resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) so that you don't have to manually close the `Cursor`

2018-05-16 07:25 UTC, jd-alexander commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +            return "";
Can you expound a bit on what's happening right here where a substring version is being returned in one case and in the other an empty string.

2018-05-16 08:05 UTC, ShenJack commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +        Cursor returnCursor =
Thank you and it sounds great! actually I rarely use this feature before, but I'll add it. this works wonderful.

2018-05-16 08:05 UTC, ShenJack commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +        String instanceFolder1 = Collect.getInstance().getFormController()
Oops, I'll change it right away.

2018-05-16 08:05 UTC, ShenJack commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +            return "";
Thank you for your reminder above,  well  I found some Mp3 files' name don't contain extension, but can be played as audio, so I write so, but I still believe there are some way to get its extension.

2018-05-21 19:59 UTC, lognaturel reviewed
Just a couple of stylistic suggestions, @ShenJack.

Up to you if you want to handle generic files in this PR or start another one.

2018-05-21 19:59 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
> +        // get the file path and create a copy in the instance folder
This comment is sufficient -- the ones below are very similar to the code and don't add additional info!

2018-05-21 19:59 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
> +        // get the file path and create a copy in the instance folder
Same comment as above -- this comment is enough and the ones below can be removed.

2018-05-21 19:59 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +                Runnable saveVideoRunnable = new Runnable() {
What about naming this `saveMediaRunnable` so it's a little more general?

2018-05-21 19:59 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +    private void saveChosenAudioVideo(Uri selectedFile) {
Similar to the comment above, how about calling this `saveChosenMedia`?

2018-05-29 14:10 UTC, mmarciniak90 commented
**Tested with success!**

Verified on Android: 5.1, 6.0, 7.0, 8.1
Audio and Video widgets load files from Google Drive

Problem is still visible on `File widget` but I created a separate issue to fix this - #2258

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

2018-05-29 15:28 UTC, lognaturel approved these changes

2018-05-29 15:29 UTC, merged

2018-05-29 15:33 UTC, ShenJack commented
@mmarciniak90  Thanks a lot for testing my changes, I'll go on to fix the issue of File Widget.