Dark mode improvements
getodk/collect pull request #2242
Opened 2018-05-24 16:12 UTC by grzesiek2010

Closes #2241 

#### What has been done to verify that this works as intended?
I tested all mentioned cases. Result:
![screenshot_2018-05-24-18-09-00](https://user-images.githubusercontent.com/3276264/40497952-dfe28d34-5f7d-11e8-8cce-d122f94ab823.png)
![screenshot_2018-05-24-18-09-33](https://user-images.githubusercontent.com/3276264/40497958-e31b9be4-5f7d-11e8-8289-8ec8cb17de52.png)
![screenshot_2018-05-24-18-09-42](https://user-images.githubusercontent.com/3276264/40497962-e57e550c-5f7d-11e8-85b2-e75a5b55ca2c.png)
![screenshot_2018-05-24-18-10-38](https://user-images.githubusercontent.com/3276264/40497968-e977eaf6-5f7d-11e8-90fa-4edd856c5849.png)
![screenshot_2018-05-24-18-10-24](https://user-images.githubusercontent.com/3276264/40497975-ef74958a-5f7d-11e8-9688-598c2e6151f8.png)
![screenshot_2018-05-24-18-10-14](https://user-images.githubusercontent.com/3276264/40497982-f31fe266-5f7d-11e8-9af2-b4002b86e4bd.png)

#### Why is this the best possible solution? Were any other approaches considered?
Everything should be as much consistently as possible and as similar to the previous version as possible.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2018-05-24 17:47 UTC, shobhitagarwal1612 requested changes

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
> +            zoomLocationButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
`themeUtils` is already initialized in `CollectAbstractActivity`. So that can be reused

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeGoogleMapActivity.java
> +                zoomPointButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeGoogleMapActivity.java
> +                zoomLocationButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
> +            zoomPointButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeOsmMapActivity.java
> +            zoomLocationButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeOsmMapActivity.java
> +            zoomPointButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java
> +                zoomPointButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
> +            zoomPointButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
> +            zoomLocationButton.setTextColor(new ThemeUtils(this).getPrimaryTextColor());
Same as above

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java
> +                answerLayout.setDividerDrawable(getResources().getDrawable(new ThemeUtils(getContext()).getDivider()));
`QuestionWidget` also contains `themeUtils`, so that can be reused

2018-05-24 17:47 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
> +            divider.setBackgroundResource(new ThemeUtils(getContext()).getDivider());
Same as above

2018-05-24 19:28 UTC, grzesiek2010 commented
@shobhitagarwal1612 thanks, I fixed everything.

2018-05-24 19:43 UTC, shobhitagarwal1612 approved these changes

2018-05-24 19:44 UTC, shobhitagarwal1612 commented
@grzesiek2010 Thanks. The code looks great!

2018-05-30 12:02 UTC, mmarciniak90 commented
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

|![screenshot_2018-05-30-14-56-24](https://user-images.githubusercontent.com/3907554/40718851-08b08afe-6401-11e8-9d7e-24abc48832ac.png)|![screenshot_2018-05-30-14-56-09](https://user-images.githubusercontent.com/3907554/40718858-0d8e27e8-6401-11e8-9b58-2e21293e7bbb.png)|![screenshot_2018-05-30-14-57-40](https://user-images.githubusercontent.com/3907554/40718868-126ca2da-6401-11e8-9897-b356e8bb314f.png)|
|---|---|---|
|![screenshot_2018-05-30-14-53-42](https://user-images.githubusercontent.com/3907554/40718881-1978a6d2-6401-11e8-83d1-a46856b5a6aa.png)|![screenshot_2018-05-30-14-27-58](https://user-images.githubusercontent.com/3907554/40718885-1eb5620c-6401-11e8-8d85-127852485ba7.png)|![screenshot_2018-05-30-14-44-45](https://user-images.githubusercontent.com/3907554/40718889-22b2460e-6401-11e8-98fc-c2a108f2b01c.png)|

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

2018-05-30 18:53 UTC, merged