Updated open mapping options. Closes #216
getodk/collect pull request #246
Opened 2016-11-10 19:16 UTC by max2me

* Removed MapQuest tiles option
* Added OSM, USGS TOPO, USGS Satellite, Stamen Terrain tiles

2016-11-14 10:44 UTC, lognaturel requested changes
Sweet! Just a couple small things I marked inline.

Did you see a reason not to include the CartoDB basemaps with free licenses (Positron and Dark Matter)?

2016-11-14 10:44 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +<string name="openstreetmap_sdk">Other Map SDKs</string>
This should still be OpenStreet Map SDK. The basemap options have changed but not the SDK.

2016-11-14 10:44 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/spatial/TileSourceFactory.java
> +            "USGS National Map Topo",
I don't think these names are currently used in the interface but for consistency's sake, we should probably use the String resources.

2016-11-16 13:36 UTC, lognaturel commented on collect_app/src/main/res/values-de/strings.xml
> -  <string name="openstreetmap">OpenStreetMap</string>
Don't worry about translations, only the strings.xml file matters. The others will get pulled from Transifex (https://www.transifex.com/opendatakit/odk-collect/) and overwritten.

2016-11-22 15:28 UTC, jnordling commented
@max2me the pull request looks good, @lognaturel made some comments. I think if you make those small modification we can pull it in. 

It would be great to add this to master. Every little bit helps, Thanks!!

2016-11-22 16:07 UTC, lognaturel commented
@jnordling Do you have any thoughts on the basemaps? Is it worth also including the free ones from CartoDB or are they mostly just redundant?

2016-11-22 16:16 UTC, jnordling commented
Yeah I think as long as some the core tiles work. In general they are all the same except for some cartographic differences. However it would be sweet to have CartoDB and any others like MapBox free maps in there... The idea solution is to have a configurable setting in either admin or general settings to specify a custom URL to a tile server... Just an idea... Keeping basemap URL's up to-date is always challenging...

2016-11-22 16:21 UTC, lognaturel commented
Ok! @max2me Can you please look into both CartoDB and MapBox free maps for now? And @jnordling, I like this configurable idea. How about you file it as an issue for now and we can discuss there what that could look like.

2016-11-23 01:46 UTC, max2me commented on collect_app/src/main/res/values/strings.xml
> +<string name="openstreetmap_sdk">Other Map SDKs</string>
@lognaturel I've changed it back to OpenStreetMap SDK

2016-11-23 01:46 UTC, max2me commented on collect_app/src/main/java/org/odk/collect/android/spatial/TileSourceFactory.java
> +            "USGS National Map Topo",
I've refactored TileSourceFactory to now pull up those strings from resources (couldnt find how they are used either).

2016-11-23 01:54 UTC, max2me commented
@lognaturel @jnordling In general my hesitation with both CartoDB and MapBox is that they impose limits on tile views per month. 

* CartoDB offers 75,000 (or 100,000 - what they have published on the site is different from what they have in [Terms of Service](https://drive.google.com/file/d/0B3OBExqwT6KJaHdTcEVnYU8xYTg/view)) for free, 
* MapBox's free plan includes 50,000 map tiles per month and up to 50,000 mobile users.

Also free tiles from CartoDb seem to be more suited for visualization and rendering data on top of them.

I'm not sure how CartoDB enforces that limit since they do not require API key in tile URL so I'm going to add those. Let me know if I should sign up for MapBox and add those layers as well. 

Another option would be to let users enter their own MapBox account key in settings, that way they will be less likely to be affected by limits imposed.

2016-11-23 02:06 UTC, max2me commented
@lognaturel @jnordling Done. Please take a look.

2016-11-23 11:35 UTC, lognaturel commented
Cool. One thing I hadn't noticed before is that the USGS maps seem to be of pretty limited use outside the US. Maybe we should have a more considered conversation about which basemaps should be included.

It looks like the CartoDB tiles share a cache or something. If I set the basemap as Positron, load a few tiles and then change it to Dark Matter, the tiles that were loaded as Positron don't get loaded again and so I have tiles of both kinds showing up.

@yanokwa I think we can merge this now even with those small issues so there are osm sdk basemaps available. Then we can continue with a broader conversation about how to improve mapping.

2016-11-23 11:42 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/spatial/TileSourceFactory.java
> +        mCartoDbDarkMatter = new XYTileSource(context.getString(R.string.openmap_cartodb_positron),
@max2me This is what's causing the shared cache between the two CartoDB basemaps. Please fix!

2016-11-23 11:45 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/spatial/TileSourceFactory.java
> +        mCartoDbDarkMatter = new XYTileSource(context.getString(R.string.openmap_cartodb_positron),
To provide a bit of context, osmdroid saves tiles to the SDCard in the osmdroid/tiles folder. It makes a folder for each basemap using that string.

2016-11-23 17:40 UTC, merged