Closes #2012: Used X-OpenRosa-Accept-Content-Length header
getodk/collect pull request #2493
Opened 2018-08-20 16:19 UTC by SaumiaSinghal

Closes #2012 

#### What has been done to verify that this works as intended?
I tested it by sending a form, and displaying the value of content length that it uses now.

#### Why is this the best possible solution? Were any other approaches considered?
It fetches the value of OpenRosa Content length from the header of Http response and then uses it to decide the maximum size of a file to be sent in a single post. 

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2018-08-27 18:45 UTC, lognaturel commented
This looks good to me, @SaumiaSinghal! It does conflict with https://github.com/opendatakit/collect/pull/2257, though, and since that is a risky, long-running pull request, we should get that one merged first and then address merging the update into this branch. I will let you know when this happens.

2018-08-27 19:09 UTC, SaumiaSinghal commented
Thanks @lognaturel for reviewing my PR, yes, I know that is a long running pull request (getting notifications all day long 😅) and I know that you guys are working real hard. So I can definitey wait. Meanwhile, I'll look at other issues.

2018-09-05 22:22 UTC, lognaturel commented
Phew, it has been merged! Thanks for your patience, @SaumiaSinghal. You find that the same code that you worked with has moved to `HttpClientConnection` and you should be able to apply the change there.

2018-09-06 04:31 UTC, SaumiaSinghal commented
Yes @lognaturel, that would be better. I would definitely do that..

2018-09-25 23:46 UTC, SaumiaSinghal commented
Hey @lognaturel, I think it's ready for review. Sorry for taking so long...got caught up somewhere.

2018-09-25 23:57 UTC, SaumiaSinghal commented
@opendatakit-bot label "needs review"

2018-11-09 15:53 UTC, ggalmazor requested changes
Hi, @SaumiaSinghal!

I've studied your changes and it feels odd to have the `contentLength` set by the HEAD request because then there's an implicit coupling between that and the next request. We are assuming that the next call will be the upload call, and this is fine for now, but I think it entails a risk if the next person coming to this piece of code doesn't realize about this.

Both methods `head()` and `uploadSubmissionFile()` from the class `HttpClientConnection` are only used by the `InstanceServerUploader` class, which is the one sequencing them (first call to `head()`, then upload the submission).

The `head()` method returns an `HttpHeadResult` that contains the response headers. Why not read those headers in `InstanceServerUploader` and pass the content length to `uploadSubmissionFile()` as a new argument? That way, we can decouple both calls and make the overall design more robust.

2018-12-04 21:55 UTC, yanokwa commented
Hi @SaumiaSinghal! Will you have time in the next week or so to make changes based on @ggalmazor's feedback?

2019-01-02 21:26 UTC, yanokwa commented
@ggalmazor Would you be open to building on @SaumiaSinghal's PR with your proposed changes so we can get this merged?

2019-01-03 14:53 UTC, ggalmazor commented
Sure, I can work on that! I think I could find some time for this next week. Does that work for you?

2019-01-03 20:11 UTC, yanokwa commented
Yup! Not urgent.

2019-01-11 22:00 UTC, yanokwa commented
@ggalmazor is #2795 what you had in mind?

2019-01-21 19:31 UTC, yanokwa commented
Thanks for sending the PR, @SaumiaSinghal! I'm closing this in favor of #2795.

2019-01-21 19:31 UTC, closed without merging