Fetch available google spreadsheets and display in a dialog when setting fallback submission url
getodk/collect pull request #2570
Opened 2018-09-22 17:45 UTC by shobhitagarwal1612

Closes #1773 

#### What has been done to verify that this works as intended?
I have verified the following cases:
 1. The user hasn't provided google drive access to the app
 2. No internet availability
 3. There is an internet connection available and the user gives access to google drive
 4. Changing the server type to `Google Drive` when there is already a Google account saved

#### Why is this the best possible solution? Were any other approaches considered?
Provides an easy and user-friendly way to set fallback submission URLs

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Yes, it changes the way the user sets a fallback submission URL. Until now, one has to manually enter the URL or copy/paste from mobile's browser/drive app. Now, all of the available sheets are shown within the app in a dialog when trying to set fallback submission URL

#### Do we need any specific form for testing your changes? If so, please attach one.
I used the All-Widgets form for testing

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
Yes (waiting until the approach is accepted)

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2018-09-25 10:21 UTC, grzesiek2010 requested changes
It's a nice feature and I really like it but we should keep the possibility to add any URL because you should be able to send data to a public sheet even if it's not your sheet or shared with you.

2018-09-25 11:22 UTC, shobhitagarwal1612 commented
Thanks for your suggestions! I will update the PR with the capability to manually enter URL as well

2018-09-26 17:09 UTC, lognaturel commented
I want to reiterate my concerns from the issue since no one reacted to them! Perhaps I wasn't specific enough. Making it easier to specify a fallback URL seems like a great usability improvement but it can lead to problems because it makes it easier for different data collectors to send data to different sheets. That's why it's very strongly encouraged that the URL be included in the form itself and this is only to be used as a fallback. By making it easier, we encourage users to consider it the primary way of setting a destination sheet.

2018-09-27 04:59 UTC, shobhitagarwal1612 commented
@lognaturel I totally agree with your concerns. I just wanted to make a proof of concept see how much efforts it was going to take and it ended up being pretty easy. If you think that it's worth to tackle the concern then let's do it otherwise we can close this PR :smiley:

2018-09-27 11:17 UTC, grzesiek2010 commented
> it can lead to problems because it makes it easier for different data collectors to send data to different sheets

If they have a form with an included URL they can specify whatever they want in settings the included URL is more important so it's still safe.

2018-10-01 16:55 UTC, lognaturel commented
> If they have a form with an included URL they can specify whatever they want in settings the included URL is more important so it's still safe.

Absolutely. My concern is more about users generally gravitating towards the option that seems easier. If specifying a fallback URL is super convenient, they may want to use that as their primary way of setting the value without considering the implications. I'm not totally sure this is a valid concern and if there are a few people supporting this change, I'm happy to go with it!

2018-10-01 18:30 UTC, shobhitagarwal1612 commented
Should I post this on forum/slack to ask people for their opinions?

2018-10-01 18:37 UTC, lognaturel commented
Starting with Slack sounds like a great idea, @shobhitagarwal1612! Depending on the feedback there it could also be taken to users. I'm hesitant to go to the forum first because there are lots of large-ish features that are pending feedback.

2018-10-01 23:54 UTC, yanokwa commented
Fallback URLs were added to rescue campaigns who put in a bad or empty URL in their form. I agree with @lognaturel that the easier we make that, the more likely folks are going to use that as some default URL.

And even if we did want to make that process easier, tying it to the account on the phone may not work. That is, the account might not have write privileges to the sheet at the time you want to configure it. And as @grzesiek2010 noted, this PR doesn't give you the option of manually entering that URL so we have to add that field back in addition to what's being done with this PR.

For that reason, I propose this PR should be closed. We are all maintainers on this thread. Do you all agree with my proposal?

Going forward, I propose we automatically close PRs that are submitted to issues that are tagged "needs discussion" because it puts an undue burden on maintainers. That is, we *must* have a discussion first and agree to proceed before we should even look a PR. This is especially true because we have a lot of pending user issues and roadmap issues that need work...

2018-10-02 05:09 UTC, shobhitagarwal1612 commented
I understand your concern and agree with it. 
Also, not submitting a PR for issues tagged as "needs discussion" would be a really good idea. 

Closing the PR and the issue

Thanks :smile:

2018-10-02 05:09 UTC, closed without merging

2018-10-02 16:33 UTC, lognaturel commented
Thanks, all! One thing I know I need to work on is being a little more confident and direct in these kinds of situations. I get caught going back and forth and I know that's not helpful. Thanks, @shobhitagarwal1612, @yanokwa, @grzesiek2010 -- I think we're coming to a good resolution here and some good process changes!