Fix #2649
getodk/collect pull request #2796
Opened 2019-01-13 10:06 UTC by ravi-kishan

Closes #2649 

#### What has been done to verify that this works as intended?
Manually tested both the cases of Send Finalized Form and Get Blank From. Also it does not affect the behavior in Settings-> Server -> Google account

#### Why is this the best possible solution? Were any other approaches considered?
As the code for the changed function is shared by different sources, this approach seems good. Also in choseAccount() function similar logic has been used.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
When account access is denied user is sent back to previous activity in Send Finalized Form and Get Blank Form

#### Do we need any specific form for testing your changes? If so, please attach one.
No

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
Don't think so

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2019-01-14 11:05 UTC, grzesiek2010 requested changes

2019-01-14 11:05 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java
> +                        if (activity instanceof GoogleSheetsUploaderActivity || activity instanceof GoogleDriveActivity) {
Looks good but could you just use one if statement instead?

2019-01-14 19:09 UTC, grzesiek2010 requested changes

2019-01-14 19:09 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java
> +                    if (activity != null && (activity instanceof GoogleSheetsUploaderActivity || activity instanceof GoogleDriveActivity)) {
Ohh sorry I didn't catch it before but in fact, you don't need that first null check here:
https://stackoverflow.com/questions/2950319/is-null-check-needed-before-calling-instanceof

your IDE should highlight that check and let you know it's not needed.

2019-01-15 06:28 UTC, ravi-kishan commented on collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java
> +                    if (activity != null && (activity instanceof GoogleSheetsUploaderActivity || activity instanceof GoogleDriveActivity)) {
Thanks for pointing the mistake. I had used the null check earlier because it was used in chooseAccount() function written just below this function.

2019-01-15 08:49 UTC, grzesiek2010 approved these changes

2019-01-17 14:11 UTC, mmarciniak90 commented
@yanokwa @ravi-kishan 
I noticed that the problem is not fixed when I changed a device orientation if the permission dialog was visible. 
This case is related to https://github.com/opendatakit/collect/issues/2574. Based on a decision from https://github.com/opendatakit/collect/issues/2574#issuecomment-426838431 I do **not ask** to fix this issue.

**Tested with success.**

Verified on Android: 8.1, 7.0, 6.0. 
I checked also on Android 5.1 and I did not notice regression.

**Preconditions:**
1. User goes to General Settings > Server > Type: Google Drive
2. User kills the app
3. User reopens the app

**Use case 1:**
1. User click `Send Finalized Form`
2. User selects some forms and click Send Selected
3. A dialog appears which is asking for access to contacts
4. User chooses `Deny`
5. User sees `Get account permission` dialog and clicks OK
6. **User is moved to form list in `Send Finalized Form`**

**Use case 2:**
1. User click `Get Blank Form`
2. A dialog appears which is asking for access to contacts
3. User chooses `Deny`
4. User sees `Get account permission` dialog and clicks OK
5. **User is moved to main menu**

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2019-01-17 19:59 UTC, grzesiek2010 commented
Yes, it's the issue in the library we use not on our side. Thanks!

2019-01-17 19:59 UTC, merged

2019-01-17 20:03 UTC, grzesiek2010 commented
@ravi-kishan 
Thanks for your contribution and congrats on your merged pr!