Internalize all user facing strings
getodk/collect pull request #284
Opened 2016-12-06 10:21 UTC by mapkon

This PR handles #102 

**Work done**

- Extracted hard coded strings to the strings.xml file. I have tried to keep the changes to one commit per file, but where the context is the same, I merged the commits.

- Refs #279, fix about string concatenation using the "+" operator 

- Refs #279, fix the verbatim use of `foo.toString()` function, as that does not respect the user locale. I have attempted to fix all these issues.

**Testing**

Given the lack of test structure, I kept the testing at loading the different pages and checking that the strings and formats are the same

2016-12-06 13:49 UTC, lognaturel requested changes
Looking good! There were some strange ones in there. Let me know if you have any questions about my comments. Some are questions I didn't yet look deeply into so we can discuss if needed. 🙏

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +								this.createErrorDialog(getString(R.string.bad_uri) + uri, EXIT);
Instead of hardcoding the order of the text and URI, the URI should be a parameter so that RTL languages can change the order.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +							this.createErrorDialog(getString(R.string.bad_uri) + uri, EXIT);
Instead of hardcoding the order of the text and URI, the URI should be a parameter so that RTL languages can change the order.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +					this.createErrorDialog(getString(R.string.unrecognized_uri) + uri, EXIT);
Instead of hardcoding the order of the text and URI, the URI should be a parameter so that RTL languages can change the order.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +		      title = "<".concat(getString(R.string.no_form_loaded)).concat(">");
I would tend to put the <> in the string resource. I don't feel strongly about it but I think it does make the code a bit cleaner.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +<string name="corrupt_settings_file_notification">Settings successfully loaded from file</string>
Should be Sorry, settings file is corrupt and should be deleted or replaced

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/DecimalWidget.java
> +            mAnswer.setText(String.format("%d", d.toString()));
I think you need to remove the call on toString() for it to be an improvement. I'm surprised that this works -- %d doesn't require the param to be an int? I think %f is for a double.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/ExDecimalWidget.java
> +            mAnswer.setText(String.format("%d", d.toString()));
I think you need to remove the call on toString() for it to be an improvement. I'm surprised that this works -- %d doesn't require the param to be an int? I think %f is for a double.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/ExIntegerWidget.java
> +            mAnswer.setText(String.format("%d", i.toString()));
I think you need to remove the call on toString() for it to be an improvement. I'm surprised that this works -- %d doesn't require the param to be an int? I think %f is for a double.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/IntegerWidget.java
> +            mAnswer.setText(String.format("%d", i.toString()));
I think you need to remove the call on toString() for it to be an improvement. I'm surprised that this works -- %d doesn't require the param to be an int? I think %f is for a double.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +<string name="parser_exception">XPathParser Exception: " %s"</string>
Extra space between " and % in " %s"

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +<string name="gps_result" formatted="false">Latitude: %1$s\nLongitude: %2$s\nAltitude: %3$sm\nAccuracy: %4$sm</string>
Do you know what the formatted="false" does in this context? I expected it to not do the substitution but evidently it does!

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java
> -                                        selectionText.setText(context.getString(R.string.selected)
This seems like a really strange way to build a comma-separated string from an array. Couldn't it be something like `context.getString(R.string.selected, TextUtils.join(", ", answer_items))`? `%1$s, %2$s` doesn't really make any sense as a resource.

2016-12-06 13:49 UTC, lognaturel commented on collect_app/src/main/res/layout/two_item_image.xml
> +            android:text="@string/text1"/>
Is it required to have text here? It's just a placeholder so I'm wondering whether it could be omitted instead.

2017-01-09 21:17 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
> +					formatGps(Double.parseDouble(sa[0]), "lat"),
The components need to be parameters to the GPS formatting string so "lat" and "lon" can also be translated.

2017-01-10 01:42 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
> +					formatGps(Double.parseDouble(sa[0]), "lat"),
Ah, just kidding, those are used to determine the cardinal direction (N / S or E / W). What needs to be localized are the cardinal direction strings in `formatGps`. That will require some refactoring and Lint doesn't see that those are eventually user-facing strings so I've filed at #329

2017-01-10 01:44 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +								this.createErrorDialog(getString(R.string.bad_uri) + uri, EXIT);
Fixed in 4a7631d

2017-01-10 01:44 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +							this.createErrorDialog(getString(R.string.bad_uri) + uri, EXIT);
Fixed in 4a7631d

2017-01-10 01:44 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +					this.createErrorDialog(getString(R.string.unrecognized_uri) + uri, EXIT);
Fixed in 4a7631d

2017-01-10 01:45 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +		      title = "<".concat(getString(R.string.no_form_loaded)).concat(">");
Changed in ffa85a6

2017-01-10 01:45 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +<string name="parser_exception">XPathParser Exception: " %s"</string>
Fixed in d5fb1ab

2017-01-10 01:46 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/DecimalWidget.java
> +            mAnswer.setText(String.format("%d", d.toString()));
Fixed in efb4d93

2017-01-10 01:46 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/ExDecimalWidget.java
> +            mAnswer.setText(String.format("%d", d.toString()));
Fixed in efb4d93

2017-01-10 01:51 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/ExIntegerWidget.java
> +            mAnswer.setText(String.format("%d", i.toString()));
Fixed in efb4d93

2017-01-10 01:52 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/IntegerWidget.java
> +            mAnswer.setText(String.format("%d", i.toString()));
Fixed in 948e6cc

2017-01-10 02:37 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java
> -                                        selectionText.setText(context.getString(R.string.selected)
Addressed by c1db9e2. I tried to leave as much as possible untouched but it was such a strange way of building the string I had to do some surgery.

2017-01-10 02:47 UTC, lognaturel commented
@batkinson, it's all yours! I'm not sure why some files ended up with spacing and other formatting changes. It's not a ton so hopefully you don't find it too distracting. 

I tried to be very explicit about the issues I saw and how I addressed them. I'd recommend looking through the diff first, then reading through the issues I had originally spotted. There are still a couple of questions I couldn't answer. I'd like to get this reviewed by the 1/17 code freeze if possible but it's worth looking at carefully. The first set of changes broke both the Decimal and Integer Widgets and we have to be really careful to catch any remaining such issues.

2017-01-13 08:35 UTC, lognaturel approved these changes

2017-01-16 13:42 UTC, batkinson commented on collect_app/src/main/res/layout/two_item_image.xml
> +            android:text="@string/text1"/>
Have you ever used the ['tools' namespace](https://developer.android.com/studio/write/tool-attributes.html) before? You can use tools:text="text1 which exposes the value only to Android Studio at design time.

2017-01-17 10:05 UTC, batkinson approved these changes
Despite my natural reaction to a PR like this, I am approving it. The string changes by themselves were a fairly straight forward, consistent with the issue's intent and complexity fairly low. However, the later commits seem to change the point of the PR from one of externalizing strings for translation to fixing other loosely related issues. What's worse is that the commits are higher in complexity and more likely to have unintended side-effects. These kinds of changes are better to be tracked separately and reviewed on their own. By doing so, the reason for the change is clear and review intensity can match the likelihood of unintended side effects, rather than being diluted by seemingly unrelated work. Commit c1db9e227df is relatively small, and easy to inspect. However, without tests we really should be making it easy for reviewers to test the behavior in lieu of another solution. For example, an issue with a test form would allow almost anyone to checkout the branch, load the form, and confirm the problem and failure.

2017-01-17 10:48 UTC, lognaturel commented on collect_app/src/main/res/layout/two_item_image.xml
> +            android:text="@string/text1"/>
I had no idea! That's great, will do that.

2017-01-17 11:02 UTC, lognaturel commented
@batkinson Thanks so much for reviewing -- I know it's a beast. You are very right that we should aim to make verifying behavior as easy as possible and including test forms is a great idea. I'll add that to the contribution guide. 

I made a small change thanks to your suggestion. Could you please take a quick look at that and then do the merge? I think for this one we don't want to squash since the commit messages are insightful. Rebase and merge is probably the right approach?

2017-01-17 11:05 UTC, lognaturel commented
I should add that I do apologize for those more complex later commits! c1db9e2 definitely had me scratching my head on what to do. Do you think I should have perhaps reverted the original change (it wasn't really giving valid translation strings) and then done a separate PR?

2017-01-17 12:45 UTC, merged