New appearance of the button holder
getodk/collect pull request #2981
Opened 2019-04-01 17:23 UTC by grzesiek2010

Closes #2971

#### What has been done to verify that this works as intended?
I tested the behavior of the new button holder.

#### Why is this the best possible solution? Were any other approaches considered?
I followed the material design as described in the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It just implements the new appearance of the button holder used in forms for navigation. It's not very risky and we can just test that element.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2019-04-02 20:12 UTC, cooperka requested changes
Style suggestions based on eyeing it (you can find an official implementation at the Material UI JavaScript [`MobileStepper` component](https://material-ui.com/demos/steppers/#mobile-stepper) if you want to see their specs):

- Add extra padding around the buttons, especially top/bottom
- Don't bold the button text
- Make the shadow lighter and spread further
- Make sure the shadow doesn't take up any actual space (you can use the very first screen of the All Widgets form to verify this, the shadow currently has an opaque white background)

Ours:
<img width="336" alt="Screen Shot 2019-04-02 at 15 59 37" src="https://user-images.githubusercontent.com/2047062/55432721-a4685380-5561-11e9-970f-c1cf338031b5.png">

Theirs:
<img width="336" alt="Screen Shot 2019-04-02 at 16 00 04" src="https://user-images.githubusercontent.com/2047062/55432736-aa5e3480-5561-11e9-9b8b-20f9576faba7.png">

2019-04-02 20:12 UTC, cooperka commented on collect_app/src/main/res/values/strings.xml
> +    <string name="next">NEXT</string>
Instead of adding new strings, can we use the existing ones and programatically capitalize them? It doesn't look like 'Prev' is currently used anywhere except for right here so it can probably be changed to be 'Back' instead.

```xml
    <string name="form_forward">Next</string>
    <string name="form_backward">Back</string>
```

2019-04-02 20:12 UTC, cooperka commented on collect_app/src/main/res/drawable/shadow_up.xml
> +    <!-- intended for lollipop and above -->
"Intended" is unclear here; **must** it only be used `>= Lollipop` or will it just look different when `< Lollipop`?

2019-04-02 20:12 UTC, cooperka commented on collect_app/src/main/res/layout/form_entry.xml
> +            <TextView
Being `TextView`, these don't have any ripple animation or tap feedback. Can we make them `Button`s or something else interactive?

2019-04-04 13:13 UTC, grzesiek2010 commented on collect_app/src/main/res/layout/form_entry.xml
> +            <TextView
TextView can have ripple animation as well, fixed.

2019-04-04 13:13 UTC, grzesiek2010 commented on collect_app/src/main/res/values/strings.xml
> +    <string name="next">NEXT</string>
Fixed.

2019-04-04 13:14 UTC, grzesiek2010 commented on collect_app/src/main/res/drawable/shadow_up.xml
> +    <!-- intended for lollipop and above -->
My mistake, it works well on older devices too. I removed the comment.

2019-04-04 15:15 UTC, cooperka approved these changes
LGTM 🥇

2019-04-08 13:54 UTC, mmarciniak90 commented
I started testing from devices with the newest Android version. When I started testing on Android 4.4 and 4.2 I noticed the crash.
@grzesiek2010 could you look at it? [crash.txt](https://github.com/opendatakit/collect/files/3054602/crash.txt)

2019-04-10 19:09 UTC, grzesiek2010 commented
> I started testing from devices with the newest Android version. When I started testing on Android 4.4 and 4.2 I noticed the crash.

Fixed.

2019-04-11 13:54 UTC, mmarciniak90 commented
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 8.1 

Verified cases
- turn on/off buttons during filling form
- used buttons only
- used buttons and swipes

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2019-04-13 16:43 UTC, shobhitagarwal1612 approved these changes

2019-04-13 16:50 UTC, merged