Removed the mappings present in the CollectContentTypeMapping enum wh…
getodk/collect pull request #3256
Opened 2019-07-27 11:30 UTC by arun-y99

…ich are already handled by the MimeTypeMap mapper.

Closes #3173 

Changes:
All the mappings that are covered in the MimeTypeMap.java file  (https://android.googlesource.com/platform/frameworks/base/+log/61ae88e/core/java/android/webkit/MimeTypeMap.java) have been removed in the custom map.

2019-07-31 01:02 UTC, lognaturel commented
Hello and welcome, @arun-y99! It looks like one of the tests is failing. Could you please take a look at that?

2019-08-07 03:58 UTC, lognaturel commented
Hi @arun-y99! If you have any questions about tests, consider hopping into #collect-code [in Slack](https://slack.opendatakit.org/).

2019-08-07 06:03 UTC, arun-y99 commented
Hi @lognaturel , I am just trying to figure out why the MimeTypeMap is not handling the mappings removed by me in the custom mapping.
For e.g. the "text/xml","xml" mapping is handled by MimeTypeMap, but the value returned is "application-octet-stream", which is the default string returned if no mapping is found.

2019-08-07 17:08 UTC, lognaturel commented
The failure I'm seeing is `expected:<a[udio/3gpp]> but was:<a[pplication/octet-stream]>`. This makes sense because 3gpp was defined in the custom map but not in Android. You removed it from the custom map so there's no support anymore. 

How did you pick which mappings to remove? The ones that are in Android should be removed. The ones that are not in Android should be maintained.

2019-08-12 21:00 UTC, seadowg requested changes
Hey @arun-y99 👋 

Android may well handle the mappings you've removed but our tests use a mock `MimeTypeMap` and basically don't make any assumptions around what mappings it may handle. It'd be great as part of this PR if you'd be able to link some documentation about what mappings Android handles and then remove those mappings from both the object and the test. If we know Android handles a file extension then we don't need a test to check our code handles it - the test `whenExtensionIsNotRecognized_returnsTypeFromAndroid` covers us falling back to Android. If you have questions [our Slack](https://slack.opendatakit.org/) (as @lognaturel linked to) is good place to reach out!

It'd also be helpful if you could make sure to include the answers to the questions and the checkboxes that our [PULL_REQUEST_TEMPLATE](https://github.com/opendatakit/collect/blob/master/.github/PULL_REQUEST_TEMPLATE.md) should have prompted you with. This helps us understand the changes and lets us know that the PR is ready to review.

2019-12-09 20:25 UTC, lognaturel commented
Closing due to inactivity. Please reopen if you'd like to address the comments above, @arun-y99!

2019-12-09 20:25 UTC, closed without merging