Automate versionCode increments
getodk/collect pull request #328
Opened 2017-01-09 09:51 UTC by grzesiek2010

This PR is in reference to resolve #238

2017-01-09 15:24 UTC, lognaturel requested changes

2017-01-09 15:24 UTC, lognaturel commented on collect_app/build.gradle
>  ant.condition(property: "os", value: "windows") { os(family: "windows") }
I don't believe these two lines are used since the property is directly accessed in the switch statements below.

2017-01-09 15:24 UTC, lognaturel commented on collect_app/build.gradle
> +def getMasterCommitCount = { ->
Add a quick reference to StackOverflow so someone can get more context. E.g.:
// Based on http://stackoverflow.com/questions/17097263#24121734

2017-01-09 16:02 UTC, grzesiek2010 commented on collect_app/build.gradle
> +def getMasterCommitCount = { ->
Done.

2017-01-09 18:38 UTC, lognaturel approved these changes

2017-01-17 12:04 UTC, batkinson approved these changes
I took a quick look at this and it appears to work as described in the stack overflow article. I moved master, built/installed then moved master back and repeated to check that the version code decrements as you'd expect.

While this makes it slightly easier to handle releases from master, it makes handling releases from other branches more complicated. The reason is that relevant changes are only counted in relation to the master branch. If you fix a bug in 1.2.3 (on a maintenance branch 1.2.x) and there's an alpha of 2.0 (from master) the version code won't count the change on 1.2.x since it's only counting commits on master.

From my perspective, the overall utility vs the complexity it adds may not be worth it if we expect to ever do these types of things.

2017-01-17 13:56 UTC, lognaturel commented
I believe the build number is mostly important for Google Play Store releases and I believe these would all be from master. @yanokwa? The thing that will be user-facing moving forward is the versionName which is now the result of `git describe`. You can see that at work now by looking at the version on the landing screen. It will give you the short hash for the latest commit so you can easily find the corresponding code.

As I understand it, build number is what is used to determine whether there's an upgrade path between app installs. So having the build number based on number of commits from master means that it's always possible to install from all active branches derived from master.

2017-01-18 05:08 UTC, lognaturel commented
I understand the usefulness of maintenance branches but I must say I've never used such a structure myself and I don't believe Collect has either. 

How is build number typically assigned in that case? Let's say I have 2.3 with build number 2341 and 1.7 with build number 1281. I then want to release 1.7.1. Presumably 1282 already corresponds to something so would I go with 2342 and make sure not to reuse it when I release the next 2.x version?

I'm still not convinced this causes any problems. If there's a maintenance branch at some point in the future, we'd have to explicitly think about build number anyway so removing this code in that branch so that build number is manually managed seems to totally fine.

2017-01-18 05:12 UTC, lognaturel commented
Ah, is the problem that I could manually assign some build numbers and then get a collision when this automatic calculation happens? I still don't think that's an issue -- they wouldn't be released as the same Play Store app and having the same build number is ok for local installs.

2017-01-26 05:31 UTC, lognaturel commented
Just noticed @mitchellsundt answered the question of what to do with build number when updating builds for older devices [here](https://github.com/opendatakit/collect/issues/293#issuecomment-270260767):

> If you think there might be a need to update two or more of [the versions for older devices], you should add a gap to the versionNumber of the build. Visibility of builds is ranked by versionNumber not the version String. So if you release a 1.4.13 that targets API 14+, and you might still maintain the branch for API 9+, you should jump the version number for 1.4.13 so you have a range of version numbers that can be used for the API 9+ branch.

> If you don't do that, then your API 14+ devices will see the API 9+ builds as newly available builds when they come out, which is definitely not desirable.

2017-02-23 21:34 UTC, lognaturel commented
@batkinson and @yanokwa I'd like to give this a try unless you really don't think we should. I think that the fact that it will force gaps in build numbers between releases will be good. I propose we try it for a few releases and pull it if it's not working for some reason.

2017-02-27 14:52 UTC, merged