Fixed Expression tree is too large error
getodk/collect pull request #3308
Opened 2019-08-13 21:58 UTC by grzesiek2010

Closes #3296 

#### What has been done to verify that this works as intended?
I tested:
1. uploading >1k forms to Google Sheets
2. uploading >1k forms to Aggregate
3. uploading >1k forms using `auto send` option
4. uploading >1k forms to Aggregate with `delete after send` option

#### Why is this the best possible solution? Were any other approaches considered?
The problem was that in some places we didn't handle that case when we have too large expression tree. We did that uploading form to Aggregate but not uploading forms to Google Sheet or using auto-send.
I extracted the code used during uploading to Aggregate and used it in other places.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Cases I described above should be tested. Generally, it's not a very risky pr, changes are only related to creating a result message (after uploading forms) so just that functionality might be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2019-08-14 09:48 UTC, seadowg requested changes
Totally agree with extracting the logic here to a shared helper. I think as we're moving this code it would be a good time to add tests (for the helper method). This would help us catch any future regressions and also provide some documentation/specification around the method's behaviour.

2019-08-19 16:25 UTC, grzesiek2010 commented
> I think as we're moving this code it would be a good time to add tests

Done.

2019-08-20 09:48 UTC, seadowg requested changes
Ah I had actually thought about this as a Robolectric/pure Java test but looking at the `InstancesDao` it doesn't seem like that would have been that easy so I can see why you went for an instrumented test. I think it'd be good to rework this in the future but good to get this in as it fixes an issue.

One thing: I'm worried it's not entirely clear in the test why it sends 1000 instances. I think a rename for the test method (`whenX...` for example) or a comment would be good before this goes in.

2019-08-28 12:12 UTC, grzesiek2010 commented
> One thing: I'm worried it's not entirely clear in the test why it sends 1000 instances. I think a rename for the test method (whenX... for example) or a comment would be good before this goes in.

I added a comment.

2019-08-28 13:09 UTC, seadowg approved these changes

2019-08-30 03:35 UTC, lognaturel commented
Nice to see the reduced redundancy!

@seadowg, I'm going to replace you with a CI task that comments "WRITE TESTS" on every PR without tests. 😉 (Just kidding, it's really very helpful to have a real person keeping us all accountable, especially when you have suggestions about how to improve testability or what kind of test to write. 🙏)

2019-09-03 12:58 UTC, mmarciniak90 commented
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1, 9.0

**Verified cases:**
* 1k submissions sent to Google Sheet
* 1k submissions sent to Aggregate
* scroll
* dialog with messages about successfully sending
* dialog with messages about failed sending
* dialog opened from a notification
* auto-sent and auto-delete

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2019-09-03 14:23 UTC, merged