Add view guidelines section to CONTRIBUTING.md
getodk/collect pull request #3400
Opened 2019-10-18 00:54 UTC by seadowg

Motivated by [this write up](https://gist.github.com/seadowg/93f33419460bcc7895990dab5c5958c5) of pains experienced during a refactor.

Interested to see if people agree with the guidelines!

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2019-10-23 02:03 UTC, lognaturel requested changes

2019-10-23 02:03 UTC, lognaturel commented on CONTRIBUTING.md
> +- View's shouldn't interact with other layers of your application (repositories, network etc). They should be able to take in and render data (via setters) and emit "meaningful" events via listeners.
"View's" -> "Views"

2019-10-23 02:03 UTC, lognaturel commented on CONTRIBUTING.md
> +- Views would ideally have just one setter for data but more complex views (often that have many subviews) that take in data at different times may have more - less setters is better as it's less cha
total nitpick but "less setters" -> "fewer setters"

2019-10-23 02:03 UTC, lognaturel commented on CONTRIBUTING.md
> +- Views that render more than one kind of data (and that have more than one setter) might benefit from `render` method that encapsulates all the logic around displaying the state of a view.
"benefit from" -> "benefit from a"

2019-10-25 15:55 UTC, lognaturel approved these changes

2019-11-04 23:34 UTC, lognaturel commented
@seadowg can you please resolve conflicts and we can merge?

2019-11-07 09:31 UTC, grzesiek2010 approved these changes

2019-11-07 09:31 UTC, merged