Rework layouts for QuestionWidget and ODKView
getodk/collect pull request #3483
Opened 2019-12-02 17:00 UTC by seadowg

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2019-12-05 09:06 UTC, seadowg commented
Closing this for the moment.

2019-12-06 17:18 UTC, seadowg commented
Reopened this now we're at code freeze. Closing was honestly just a piece of metnal self help but will definitely be coming back for this now!

2020-01-20 23:25 UTC, lognaturel commented
Ooh, I completely lost track of this, sorry. Will try to review soon so it can stop accumulating conflicts.

2020-01-21 10:11 UTC, seadowg commented
@lognaturel conflicts fixed!

2020-01-21 19:20 UTC, lognaturel requested changes
Couple of tiny catches that don't affect behavior.

The medium emphasis color for the hint text is not high-enough contrast, I think.

It also looks like something happened to the question text. Did the font change? It looks "more bold" and that makes it harder to read to me.

I'm a bit disappointed by the rendered views in Android Studio since one of the stated goals for this change is to make the tooling more useful. I thought this might get to a point where we could see something that looks like a question. It's certainly a step in the right direction but do you think there's more that can be done (at another time)? `odk_view` just shows the hierarchy label because the widgets and dividers are still added programmatically. `audio_video_image_text_label` shows the label and the media placeholders and I'd expect that to show up in `question_widget` but it doesn't.

2020-01-21 19:20 UTC, lognaturel commented on collect_app/src/main/res/layout/activity_capture_selfie_new_api.xml
> +        android:id="@+id/question_widget_container"
I think this is unintentional.

2020-01-21 19:20 UTC, lognaturel commented on collect_app/src/main/res/layout/activity_capture_selfie_video_new_api.xml
> +    android:id="@+id/question_widget_container"
I think this is unintentional.

2020-01-21 19:20 UTC, lognaturel commented on collect_app/src/main/res/values/refs.xml
> +<?xml version="1.0" encoding="utf-8"?>
remove?

2020-01-22 09:34 UTC, seadowg commented
> The medium emphasis color for the hint text is not high-enough contrast, I think.

I'll have a look at this. It's the recommended our surface color being grey doesn't work well this I think.

> It also looks like something happened to the question text. Did the font change? It looks "more bold" and that makes it harder to read to me.

Yeah it's always been bold but now it's using our Headline 6 style **and** is bold which I think pushed the letter spacing to close. Generally it seems like bolding isn't as much a thing in the Material typography. I'm glad you noticed this as I agree (but didn't want to bring it up and have everyone obsess over it). I'll look at taking the bold out!

2020-01-22 13:38 UTC, seadowg commented
@lognaturel great catch on the medium emphasis text having too low a contrast! Basically our `colorSurface` attribute was set to `#DE000000` which is black with an alpha of 0.87. This is the correct color for ["High Emphasis" in Material](https://material.io/design/color/text-legibility.html#text-backgrounds) but what I hadn't realized is that when we apply our "filter" (alpha of 0.6) to this color we get an alpha of 0.6 * 0.87 rather than an alpha of 0.6. 

Really the `colorOnSurface` should just be` #000000` (for light theme) anyway as it will be used for other things than text (like icons) so I've set it to that and introduced a "high emphasis" color in the same way that we had "medium emphasis" before and just used that as the default color for the typography styles.

2020-01-22 16:33 UTC, lognaturel submitted a review, later dismissed
Thanks for making those last subtle improvements!

2020-01-22 16:36 UTC, lognaturel commented
Wait a minute. The hint text is now the same size as the group text. There can be quite a lot of very useful text there so that seems too small.

2020-01-22 17:24 UTC, seadowg commented
![Screenshot_1579700016](https://user-images.githubusercontent.com/556280/72917422-b8bd4d00-3d3b-11ea-962a-97782451d409.png)

@lognaturel you're talking about the "This is optional, of course" right? It doesn't seem to small to me necessarily and it's the standard body size (16sp). Do you think the group text should be smaller or do you think the hint needs bumped up?

2020-01-22 17:27 UTC, lognaturel commented
> Do you think the group text should be smaller or do you think the hint needs bumped up?

The previous hint size seemed about right to me. But I know you'll tell me it's non-standard. I'll run it by @yanokwa to see what he thinks.

2020-01-22 17:29 UTC, seadowg commented
@lognaturel yeah good to get some other opinions. The current size is the standard body text but I could see that the text should be more important than that.

2020-01-22 18:10 UTC, lognaturel commented
Sounds great. QA can let us know their opinion and start looking for other regressions while we decide.

2020-01-23 09:08 UTC, seadowg commented
@lognaturel we've got that work coming up (new widget framework and then changes to actual widgets). Maybe once we've got the new framework in we can pritoritize which widgets/elements we think should get changed first?

2020-01-29 14:50 UTC, mmarciniak90 commented
@seadowg I set RTL language and I see one potentially unexpected appearance
Screenshots are from Android 7.0 and 8.1

| v1.25.1 | pr/3483 |
|---|---|
|![Screenshot_20200129-154041](https://user-images.githubusercontent.com/3907554/73366803-d4ca6c80-42ae-11ea-8bb9-b4c7063f268f.png) |![Screenshot_20200129-154037](https://user-images.githubusercontent.com/3907554/73366837-deec6b00-42ae-11ea-8441-750de06a00fb.png)|

2020-01-29 15:39 UTC, seadowg commented
@mmarciniak90 hmm I feel like we've run into this before. Let me take a look at it!

2020-01-29 17:14 UTC, seadowg commented
@mmarciniak90 I've fixed the layout. It doesn't really feel like the previous one is great but I think we should keep it unchanged for the moment.

2020-01-29 17:30 UTC, lognaturel commented
I think that the modified layout was actually more accurately RTL than the 1.25.1 one. Question labels showing to the right of the options seems like it would be the expected behavior in a RTL language.

That said, I think it's also fine to leave until a RTL user provides specific requirements for that layout.

> It doesn't really feel like the previous one is great 

These grids are inherently inappropriate for narrow devices and that's ok. Is that what you're referring to? It would look good on e.g. a tablet. We actually made a change to wrap hints at one point and immediately got the feedback that this was not what users wanted.

2020-01-30 09:04 UTC, seadowg commented
> These grids are inherently inappropriate for narrow devices and that's ok. Is that what you're referring to? It would look good on e.g. a tablet. We actually made a change to wrap hints at one point and immediately got the feedback that this was not what users wanted.

Huh. Interesting. Yeah I've not personally seen any complaints about the widget so it doesn't make sense to change it. I think our example is just a little weird probably!

2020-01-31 13:30 UTC, mmarciniak90 commented
@lognaturel, @seadowg thanks!

**Tested with success**

Verified on Android 4.4, 6.0, 7.0, 8.1

2020-01-31 13:34 UTC, kkrawczyk123 commented
*Tested with success!*
Verified on 4.2, 5.1, 9.0 and 10

I haven't noticed anything suspicious.

Verified cases:
All widgets in light mode
All widgets in dark mode
All widgets in RTL language (There are always weird things on Android 4.2)
All widgets in different font sizes
autoplay widget
grid widgets with autoplay
select one and multi: all kinds, no appearance, compact, column-flex
form with questions on OnePage
fieldlist form.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2020-01-31 17:24 UTC, lognaturel approved these changes

2020-01-31 17:24 UTC, merged