Aggregate server history dropdown
getodk/collect pull request #351
Opened 2017-01-22 23:19 UTC by grzesiek2010

This PR is in reference to resolve #255

2017-01-23 11:55 UTC, lognaturel requested changes
In terms of behavior, this is perfect! The only thing I'd like to explore is whether it's possible to have a slightly bigger down arrow icon. I see you used a material design icon which is great. Is its size just determined by its container and the margin on the image itself?

Can you say a little bit about why you decided to use json for persisting the list rather than, for example, a set (which can be saved directly) or serializing an arraylist? I just want to make sure we've considered the tradeoffs.

2017-01-23 11:55 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesActivity.java
> +    @TargetApi(Build.VERSION_CODES.HONEYCOMB)
This is just a way to block Lint so I believe that the new code which uses features of an API level > 9 will result in a hard crash if the preferences screen is opened on devices that run Android versions below Honeycomb. Is that right?

2017-01-23 11:56 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesActivity.java
> +    @TargetApi(Build.VERSION_CODES.HONEYCOMB)
This is not necessarily a problem but I do want to understand it. I'm hoping we can address #293 before the next release anyway.

2017-01-23 12:41 UTC, grzesiek2010 commented
I added bigger icons. 
I decided to use json because the Set interface does not provide any ordering guarantees. I saw this solution too: http://stackoverflow.com/a/7057858/5479029 but it reqires ObjectSerializer class so I think my solution is ok.

2017-01-23 12:44 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesActivity.java
> +    @TargetApi(Build.VERSION_CODES.HONEYCOMB)
Yes we should wait for #293 an then remove above targetapi.

2017-01-25 05:34 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesActivity.java
> +    private List<String> mUrlList;
Does this need to be a field or can it be a local variable?

2017-01-25 05:36 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesActivity.java
> +    private List<String> mUrlList;
And actually, same question for mAdapter. Would be better to have local variables wherever possible.

2017-01-25 05:53 UTC, lognaturel commented
Icon looks great. I didn't notice this before but on lines 166 and 168 of AggregatePreferencesActivity.java, the latest server URL goes to position 1 rather than 0 which "protects" the default https://opendatakit.appspot.com server. It should not have any special status, though and new URLs should bump it like any other.

I made a note of this inline but also verified it, `mAdapter` and `mUrlList` can both be local variables (without the `m`). Just make sure `mUrlList` is declared final in `onCreate` so you can use it in `onItemClick`.

I know the existing code is not very well organized but when adding new features it would be great to start breaking it up into methods. I'm seeing a good `addUrlToPreferencesList` method and something like `urlDropdownSetup` (might be better to break that one even further).

2017-01-25 11:25 UTC, grzesiek2010 commented
@lognaturel I made some changes please review again.

2017-02-23 21:14 UTC, lognaturel commented
@grzesiek2010 I'm not really sure what happened on CircleCI but I can't rerun the build. Can you please get that passing and then I think this is ready to merge.

2017-02-23 21:28 UTC, grzesiek2010 commented
@lognaturel it's ready

2017-02-23 21:45 UTC, merged