show a warning Toast if trouble getting start-geopoint
getodk/collect pull request #3575
Opened 2020-01-07 06:09 UTC by chidauri

Closes #3427 

#### What has been done to verify that this works as intended?
Tested by turning location off and on, android 9.
I have not translated the warning Toast yet for different languages, i wanted to ask what is the go-to way for that.

#### Why is this the best possible solution? Were any other approaches considered?
I agree with @lognaturel that since `setgeopoint` manages its own location client we don't need to set the priority before asking `isLocationAvailable()` here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
If the user enters a form that does not audit location but needs start geo-point, a warning toast will appear that says "Trouble getting start geo-point..." if the location is turned off in settings.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-01-21 01:03 UTC, lognaturel requested changes
We discussed in the issue and decided to show the same dialog as in the background audit location case for simplicity.

2020-01-21 16:43 UTC, lognaturel approved these changes

2020-01-21 16:43 UTC, lognaturel commented
Thank you, @chidauri! 🎉

2020-01-23 14:48 UTC, kkrawczyk123 commented
**Tested with success!**
Verified on Androids 4.2, 4.4, 5.1, 7.1, 8.1, 9.0 and 10. 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2020-01-23 18:31 UTC, merged