Used Number Picker to change line width in Annotate and Draw Widget
getodk/collect pull request #3585
Opened 2020-01-11 13:28 UTC by SaumiaSinghal

Closes #3089 

#### What has been done to verify that this works as intended?
 I tested it on Android 9.0.

![Issue#3089](https://user-images.githubusercontent.com/35730054/72205000-221f9f00-34a4-11ea-8b3f-4b9ca22d645c.gif)

#### Why is this the best possible solution? Were any other approaches considered?
I added a `floatingActionButton`, that allows the user to change stroke width and choose any value from 1 to 100, using the standard NumberPicker android widget. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No regression risks, as of now.

#### Do we need any specific form for testing your changes? If so, please attach one.
AllWidgetsForm or any form having draw or annotate widget.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-01-13 14:54 UTC, seadowg commented
@SaumiaSinghal thanks for looking at this! 

I think the general flow in this solution makes sense but I do think we should alter the design a bit. 

I think the issue (#3089) really should have had a `needs discussion` label on it so we could have discussed designs before you did any work so apologies about that.

P.S. I don't really think we should be using a FAB for the list of options here as they are generally meant to represent the primary action on any given page (like composing a new email on an inbox screen for example). Given that is already in the app I'll add it to our list of [potential design changes](https://docs.google.com/document/d/1X_YYYziaW58tacGSHIpNbDlbRjAtGNzduJ6X1pyw19M/edit).

2020-01-13 15:02 UTC, seadowg commented
@SaumiaSinghal thanks for looking at this! 

I think the general flow in this solution makes sense but I do think we should alter the design a bit. For me, the problem here is that it will be hard for an enumerator to get a sense of line width they are selecting based on the number (How big is 100? How small is 10?). I think a way to solve this is to give the enumerator a limited number of options and name them Small, Medium, Large. These could still be presented in a dialog but we could use Confirmation Dialog with selection (the Material examples are [here](https://material.io/components/dialogs/#confirmation-dialog)).

I also think it would be good for a new feature like this to have tests driving it out. Personally I'd look at testing `DrawView` to drive out the flow and checking selecting an option changes the line width.

I think the issue (#3089) really should have had a `needs discussion` label on it so we could have discussed designs before you did any work so apologies about that.

P.S. I don't really think we should be using a FAB for the list of options here as they are generally meant to represent the primary action on any given page (like composing a new email on an inbox screen for example). Given that is already in the app I'll add it to our list of [potential design changes](https://docs.google.com/document/d/1X_YYYziaW58tacGSHIpNbDlbRjAtGNzduJ6X1pyw19M/edit).

2020-01-13 15:08 UTC, seadowg requested changes
As above.

2020-01-14 04:02 UTC, SaumiaSinghal commented
Thanks @seadowg for reviewing the PR. Yes, it is not convenient to get the sense of line width by selecting from an enumerator. How about I look into how we can implement this feature in the app, keeping in mind your suggestion of providing the user a number of options like Small, Medium, Large and so on, through a confirmation dialog, and present the UI here. And then, after finalizing, maybe I can finally implement it in the app. 

I also agree with your idea of not using FAB for the mentioned reason, but that can be addressed later in a separate PR.

2020-01-14 09:54 UTC, seadowg commented
@SaumiaSinghal that sounds great!

2020-01-14 10:55 UTC, grzesiek2010 commented
Don't you think it would be good to have color picker and line weight picker as a one dialog?
The lib we use https://github.com/martin-stone/hsv-alpha-color-picker-android doesn't seem to provide such an option but maybe there is a different one we could use, or maybe we could file an issue there to add it?

2020-01-14 11:43 UTC, seadowg commented
@grzesiek2010 that's a good idea. I think looking into existing solutions like that makes sense as well @SaumiaSinghal. Once you have some ideas about the design/flow we can all discuss!

2020-01-14 16:05 UTC, seadowg commented
@SaumiaSinghal just to keep everything organized I'm going to close this PR. Let's move any more discussion to #3089 and I'll add the "needs discussion" label there.

2020-01-14 16:05 UTC, closed without merging