Fixes Issue#3493: Created getStandardMargin() in WidgetViewUtils to fix Margins
getodk/collect pull request #3630
Opened 2020-02-10 00:05 UTC by SaumiaSinghal

Closes #3493 

#### What has been done to verify that this works as intended?
I tested it on Android 9.0.

Before adding margin           |     After adding margin
:-------------------------:|:-------------------------:
![Screenshot_20191230_034615](https://user-images.githubusercontent.com/35730054/71579492-d32c4e00-2b22-11ea-896d-655686503322.jpeg)  |  ![Screenshot_20191230_033317](https://user-images.githubusercontent.com/35730054/71579501-dcb5b600-2b22-11ea-95ef-6d2df49ed301.jpeg)

#### Why is this the best possible solution? Were any other approaches considered?
I used the default margin value, that is being used in the other widgets, for uniformity. It adds the margin to the answer layout, where the answer field will appear. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I don't think there are any regression risks.

#### Do we need any specific form for testing your changes? If so, please attach one.
Allwidges form

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-02-10 13:29 UTC, seadowg requested changes
This mostly looks good to me. I've left one comment for something I'd like changed. Also, it looks like adding margins to the Grid Widget hasn't quite worked when it's in a minimal appearance:

![Screenshot_1581341179](https://user-images.githubusercontent.com/556280/74153827-51434080-4c09-11ea-8358-d6cd2a7149bb.png)

Found this in the `AllWidgetsForm.xml` which is nice for testing this stuff out!

2020-02-10 13:29 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/formentry/questions/WidgetViewUtils.java
> +        return marginStandard - FIELD_HORIZONTAL_MARGIN_MODIFIER;
Would be good to move this contstant to this file and name it something like `WIDGET_ANSWER_STANDARD_MARGIN_MODIFIER`.

2020-02-10 15:04 UTC, SaumiaSinghal commented
Hie @seadowg! Thanks for reviewing! I did the mentioned changes and also I removed the margin from grid widgets. It mostly looks good to me now than before.

2020-02-10 15:11 UTC, seadowg commented
@SaumiaSinghal looks like there is still some PMD issues. If you fix them and make sure to run `./gradlew checkAll` I think we're all good!

2020-02-10 15:30 UTC, SaumiaSinghal commented
Yes done! Sorry @seadowg. :sweat_smile:

2020-02-10 17:53 UTC, seadowg approved these changes

2020-02-11 15:07 UTC, mmarciniak90 commented
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1, 9.0, 10.0

**Verified cases:**
- all widgets from `All widgets` form
   - margin is visible on widgets with button(s), range widget, likert widget
- all widgets from `Birds` form
- RTL language
- light/dark mode
- horizontal/vertical device orientation

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

2020-02-11 15:59 UTC, merged