#241 Reset app state
getodk/collect pull request #373
Opened 2017-02-02 18:16 UTC by grzesiek2010

This PR is in reference to resolve #241

2017-02-07 09:50 UTC, lognaturel requested changes
Looks great! Since resetting is dangerous, all of the options should be unchecked so that the user has to think about which ones to check. It should also be more clear that the action is destructive and cannot be undone. That could be done with a message in the existing dialog or perhaps with an additional confirmation dialog (or both). 

When I try to delete blank forms, I get the error_occured text. I'm not getting a stack trace so it seems the number deleted just doesn't match for some reason. It doesn't look like anything was actually deleted.

This currently has options for saved forms (XML), blank forms (XML) and databases. This hasn't been sufficiently thought through but it would be good to consider whether having saved forms (XML and database) and blank forms (XML and database) would make more sense. It's not clear what happens if the XML and not the corresponding database is deleted or the other way around.

@yanokwa also mentioned that this should be tested with external itemsets to make sure all itemset data for the deleted blank forms are also removed.

2017-02-07 09:50 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/ResetDialogPreference.java
> +    private static final String ACTION_RESULT = "%s :: %s\n";
This won't work for right-to-left languages like Arabic. It's ok to have redundant string resources (e.g. "Settings" and "Settings :: %s")

2017-02-07 09:50 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/ResetDialogPreference.java
> +        final boolean resetPreferences = mPreferences.isChecked();
In this case, I think adding the local variables makes it a bit harder to see what's going on. `if (mPreferences.isChecked())` is very comfortable to read.

I think this might be left over from when you had an `||` in which case having the variables did help with readability.

2017-02-13 08:17 UTC, lognaturel commented
Getting very close! I like the scary red message at the top. I don't think "WARNING!!!" is needed, though, I'd make it just "All selected data will be deleted permanently. There is no undo."

Settings, Offline map layers, Form load cache, OSM tiles all behave exactly as I would expect. 

I think Saved forms and Blank forms is the right split but they don't work as I expect. The goal is to get to a known state in case of weird behavior but I still have empty directories left over (from I don't know what) and .bad forms when I clear either forms or instances. I think Saved forms should recursively delete everything in the instances/ directory and drop all rows in the instances db. Similarly, Blank forms should recursively delete everything in the forms/ directory and drop all rows in the forms db and the itemsets db. If it's possible to reset the _id columns to 1 when you do the DB resets, even better.

2017-02-14 07:36 UTC, lognaturel commented
I don't think `DatabaseReader` is needed anymore! Please remove it and I'll merge.

2017-02-14 08:38 UTC, grzesiek2010 commented
Done!

2017-02-14 08:42 UTC, lognaturel approved these changes

2017-02-14 08:42 UTC, merged