Update JavaRosa to v2.17.1
getodk/collect pull request #3753
Opened 2020-04-01 21:56 UTC by lognaturel

This PR fixes various bugs that were reported by users and recently addressed in JavaRosa. Several of these fixes came in just as the Collect release was getting prepared so it wasn't a good time to update. JavaRosa has gone through a lot of changes so instead of releasing off master, I'm proposing we do a point release with only low-risk bug fixes. 

Addresses javarosa#131, javarosa#509, javarosa#540, javarosa#498, javarosa#547

The branch this PR uses a JavaRosa snapshot. The sequence I propose here is:
- [ ] @seadowg or @grzesiek2010 reviews [the JavaRosa diff](https://github.com/opendatakit/javarosa/compare/v2.17.x) with the notes I've made below
- [ ] QA verifies the fixes and regression risks
- [ ] We iterate on JavaRosa as needed
- [ ] We release JR v2.17.1
- [ ] We update this PR to use the final release
- [ ] Someone does a quick sanity check to make sure that JR v2.17.1 matches the last snapshot code that was QAed and merges
- [ ] We do a Collect point release off a v1.26.x branch also including the fix for https://github.com/opendatakit/collect/issues/3751.

javarosa#131 / javarosa#efe171f: exclusively an error message change so should pose no risk. It could help with troubleshooting so I figure it's good to get out.

javarosa#509 / javarosa#5fc1012, javarosa#6cb87e4, javarosa#3f22f7e: only the first commit has a code change and it is limited to the `count-not-empty` function. The other two commits are tests. I see no regression risk with this one.

javarosa#540 / javarosa#8bc3362: I cherry-picked javarosa#26cdfa2838ce1768f301411eb365e880579a01aa and fixed spacing conflicts. Then I verified the diff against master. I didn't bring the tests in because the ones added in https://github.com/opendatakit/javarosa/pull/546 rely on new testing infrastructure. This one is riskier and there's a regression risk around any relative path expression with parenting steps (`../`) and multiplicities. However, I think the logic is straightforward enough to review. The only change is the addition of the `if (i + refLevel <= newRef.size())` condition. This means that the behavior only changes in the case where `i + refLevel > newRef.size()` in which case multiplicities aren't copied. I think the tests document this sufficiently. We know that this only affects forms with nested repeats which are relatively rare. However, this bug is a showstopper for those who want to use complex expressions in nested repeats.

javarosa#498 / javarosa#0fe85cf: I cherry-picked javarosa#eb8cfd1f because the tests added by https://github.com/opendatakit/javarosa/pull/551 rely on new testing infrastructure. It's similar in nature to the one above in that it will only affect relative references and these will only be generated by pyxform for nested repeats. I think the regression risk here is even lower because `contextualize` does nothing with absolute references. The tests are also comprehensive (https://github.com/opendatakit/javarosa/pull/551/files#diff-68d926706ca036914f632b04878da9ca). Still, there's a regression risk to the `indexed-repeat` function and it would be good to verify it in single repeats and nested repeats.

javarosa#547 / javarosa#4fdc453, javarosa#6b28fd5: only the first commit changes code. The second removes a test that relies on updated test infrastructure. This is like the `count-not-empty` change above. It only changes the `digest` function so that should be the only place where there's risk of regression.

2020-04-02 10:59 UTC, seadowg commented
@lognaturel I've had a look through and haven't spotted anything that scares me. Looks like unit tests are passing and I'll give this a run through test lab as well.

2020-04-02 13:17 UTC, seadowg commented
All green on test lab!

2020-04-02 15:47 UTC, lognaturel commented
🎉 @seadowg Are you comfortable with this going to QA, then?

2020-04-02 16:22 UTC, seadowg commented
@lognaturel yeah seems good to get there as soon as we can!

2020-04-03 15:31 UTC, kkrawczyk123 commented
@lognaturel I have started testing this pr on Androids 5.1 and 10 and I have already tested some cases like:
- digest function form
- count-non empty form
- indexed repeats forms, nested repeats forms 
I think I must have misunderstood something or maybe do something wrong as I didn't notice any differences between this pr and master when using the form attached in https://github.com/opendatakit/javarosa/issues/498 Should I change something in the form manually?

I also have a question, how this one https://github.com/opendatakit/javarosa/issues/540 should be verified. 

Definitely testing should be continued here with @mmarciniak90 and her devices :)

2020-04-04 21:42 UTC, lognaturel commented
@kkrawczyk123 I've updated the form for #498 at https://github.com/opendatakit/javarosa/issues/498#issuecomment-608754074 so that hopefully it makes a little more sense. If you can, it'd be great for you to build your own form with a nested repeat that uses `indexed-repeat` and/or look at the possible reproduction from the forum. The tricky thing is that you won't be able to use the online form converter to convert an XLSForm with `indexed-repeat` in a nested repeat because it won't pass validation. That's why I had used another expression in the calculation for form conversion and then replaced it manually in the XML.

As I was getting you a good form to verify opendatakit/javarosa#540, I realized that the fix doesn't get all cases so thanks for your help discovering that. 😊 I have issued https://github.com/opendatakit/javarosa/pull/565. @seadowg since we want to get this out quickly, I've tagged you there for review in case @ggalmazor doesn't have time. I don't think it will require a ton of context to verify.

2020-04-06 13:01 UTC, seadowg submitted a review, later dismissed
Sorry forgot to mark this when I reviewed it last week!

2020-04-06 14:56 UTC, kkrawczyk123 commented
@lognaturel thanks for the tips, I have run through it once again. I was able to reproduce the issue with the form that you have attached and also another with nested repeats and indexed-repeat on master. I was not able to reproduce on PR, I haven't noticed any regression too. Please let me know if there is anything more on your mind that should be also verified here.

@mmarciniak90, go ahead!

2020-04-06 22:34 UTC, lognaturel commented
A user just reported the additional issue with opendatakit/javarosa#540 at forum.opendatakit.org/t/infinite-loop-and-dynamically-delete-already-selected-options-from-list/25902/3 so it's great we're getting this ready to ship soon. The additional fix has been merged and the snapshot updated so please try it out. I encourage you to try the form shared on the forum as well. Thank you!

2020-04-07 13:47 UTC, mmarciniak90 commented
@lognaturel here are the results of my today's tests. Please take a look at 540 because it's still a challenge for us and maybe you will be able to help us.

---

* opendatakit/javarosa#131

   * form: [internal_empty_select.xml.txt](https://github.com/opendatakit/collect/files/4444574/internal_empty_select.xml.txt)
   * Error contains question name without choices

|master| pull request|
|---|---|
|![Screenshot_2020-04-07-15-21-09-132_org odk collect android](https://user-images.githubusercontent.com/3907554/78674334-bce11b80-78e3-11ea-97db-4df6a3db1ad6.jpg)|![<img height="80%" width="80%" src="https://user-images.githubusercontent.com/3907554/78674332-bbafee80-78e3-11ea-8f27-e7eabf72a6f3.png">|

---
* opendatakit/javarosa#509

   * form : [count-non-empty.xml.txt](https://github.com/opendatakit/collect/files/4444113/count-non-empty.xml.txt)
      * Error does not appear
      * User is able to add group
      * On `Other info` question, empty and filled groups are counted
---
* opendatakit/javarosa#540
   
   * form: [indefinite.xml.txt](https://github.com/opendatakit/collect/files/4444124/indefinite.xml.txt)
      * Form from the forum was converted but it's not possible to fill it. 
      * @lognaturel we see this error and we are not sure how to fix it.
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/78668476-0bd68300-78db-11ea-8639-7ada463edf51.png">

---
* opendatakit/javarosa#498

   * form: [indexed-repeat-nested.xml.txt](https://github.com/opendatakit/collect/files/4444115/indexed-repeat-nested.xml.txt)
      * Error does not appear
      * Questions have auto-filled answers.

   * form: [nestedTest.xml.txt](https://github.com/opendatakit/collect/files/4444117/nestedTest.xml.txt)
      * Error does not appear
---
* opendatakit/javarosa#547

   * form: [dynamic-digest.xml.txt](https://github.com/opendatakit/collect/files/4444119/dynamic-digest.xml.txt)
      * Error contains more information
      * I saw two different errors - I was not able to detect why

|master |pull request| pull request|
|---|---|---|
|![Screenshot_2020-04-07-14-44-13-637_org odk collect android](https://user-images.githubusercontent.com/3907554/78672511-0714cd80-78e1-11ea-98dc-de8607adb782.jpg)|<img height="80%" width="80%" src="https://user-images.githubusercontent.com/3907554/78672516-07ad6400-78e1-11ea-9f3e-baceb933f92d.png">|
![Screenshot_20200407-153502](https://user-images.githubusercontent.com/3907554/78676478-c91aa800-78e6-11ea-83b7-df40f3ca09d9.png)|

2020-04-07 17:12 UTC, lognaturel commented
As we discussed in Slack, the snapshot had not actually been updated which explains the existing error with opendatakit/javarosa#540.

The middle digest issue is expected -- it's stating that the 'aa' algorithm isn't supported. I can't reproduce the third error. It's a strange one because it's implying an issue with the `if` function call. Unless you can reproduce it systematically, I don't think there's much we can do about it.

2020-04-08 23:01 UTC, lognaturel commented
@mmarciniak90 pointed out that there's still a problem related to opendatakit/javarosa#540. I believe I have fixed it and updated the snapshot. I just tried this branch with the forms from forum.opendatakit.org/t/infinite-loop-and-dynamically-delete-already-selected-options-from-list/25902 and forum.opendatakit.org/t/error-in-indefinite-repeat-group-inside-another-repeat-group/24729 and I was able to get them to work. Take a look and see if you can come up with any other creative ways to break it!

2020-04-09 10:18 UTC, mmarciniak90 commented
Yeah! I was able to open forms!
 * [indefinite-repeat-inside-other-repeat.xml.txt](https://github.com/opendatakit/collect/files/4455516/indefinite-repeat-inside-other-repeat.xml.txt)
* [indefinite.xml.txt](https://github.com/opendatakit/collect/files/4455540/indefinite.xml.txt)

But... I see a crash when I click on the JUMP icon to open the hierarchy view.

`04-09 12:05:55.661 25230-25230/org.odk.collect.android E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-09 12:05:55.661 25230-25230/org.odk.collect.android E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0`

@seadowg, @grzesiek2010  any ideas?

2020-04-09 13:25 UTC, seadowg commented
Hmmm not sure about that error. Can have a look with the form later if @grzesiek2010 doesn't get to it first.

2020-04-09 14:19 UTC, grzesiek2010 commented
> if @grzesiek2010 doesn't get to it first.

I've just reproduced it but there is nothing obvious in logs at first glance. You can take a look if you want.

2020-04-09 17:28 UTC, lognaturel commented
From Slack: I did some interactive review with @seadowg of the last chunk of work that I thought would fix javarosa#540 and it turns out there are several problems with it. It does work for the sample forms but it's not a general or correct solution, unfortunately.

I'm going to do a point release without the JR update so we can get #3755 out. Then we can do a separate point release with the JR change when ready.

2020-04-20 16:06 UTC, seadowg requested changes
Sorry forgot to update the status here!

2020-04-27 22:23 UTC, lognaturel commented
The snapshot has now been updated with the latest updates to fix #1540. I have verified this by trying the species form from the forum. I have also run all tests on the v1.17.1 JR branch and here.

Here are some additional test forms to try:
- the original ones from the issue
- [indefinite-repeat-nested-relative.xml.zip](https://github.com/getodk/collect/files/4542193/indefinite-repeat-nested-relative.xml.zip) expected behavior: outer repeat has one instance initially and user is prompted to add more. Inner repeat has one instance initially and another one is added if user types "yes" (all lowercase). Inner repeat exists if any other text is included.
- [predicate-trigger-change.xml.zip](https://github.com/getodk/collect/files/4542216/predicate-trigger-change.xml.zip) expected behavior: specify a number for the first question. On the second screen you should see a sum of numbers 1-6 that are greater than the number from the first question. For example, enter 5 and you should see 6. Only the first outer repeat has pre-populated values 1-6. You can add another outer repeat and specify your own inner repeat values to verify the same behavior.
- [predicate-current.xml.zip](https://github.com/getodk/collect/files/4542226/predicate-current.xml.zip) similar to above but there are always exactly 5 items that come from an external list and the list labels are concatenated. For example, enter in 4 and you should get "Item5" or enter in 2 and you should get "Item2, Item3, Item4, Item5"

These might give you other ideas of form types to try.

2020-04-29 22:08 UTC, mmarciniak90 commented
@lognaturel I added noticed issues and thoughts.

All cases were verified on Android 6.0, 7.0, 8.1, 9.0

Verified cases:
* forms:
   * _indefinite-repeat-inside-other-repeat.xml_ and _indefinite.xml_
      *  **I noticed a crash mentioned previously - when I click on the JUMP icon to open the hierarchy view.**
      * when I reopen form after the crash I have another crash because app wants to recover data and open hierarchy view - and it happens again and again
   * _indefinite-repeat-nested-relative.xml_
   * _predicate-trigger-change.xml_
       * **the sum is not re-counted dynamically after removing repeat for repeats added manually**
       <img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/80650955-42846100-8a75-11ea-973c-04bb3a43cab4.gif">
   * _predicate-current.xml_
      * > For example, enter in 4 and you should get "Item5" or enter in 2 and you should get "Item2, Item3, Item4, Item5"
       * I see a small difference but I guess there is misleading in the description - When I enter 2 I see "Item3, Item4, Item5"
* removing repeats
* removing repeats via trash icon in the hierarchy view
* opening hierarchy view

2020-04-29 23:39 UTC, lognaturel commented
Thank you, @mmarciniak90!

> I noticed a crash mentioned previously - when I click on the JUMP icon to open the hierarchy view.

Yes, that's expected. The infinite loop happens on finalization as well.

> the sum is not re-counted dynamically after removing repeat for repeats added manually

Is that only the case if you delete the last repeat? I suspect you're experiencing #3016

> When I enter 2 I see "Item3, Item4, Item5"

Whoops, yes, that's exactly right.

2020-04-30 20:58 UTC, mmarciniak90 commented
> Is that only the case if you delete the last repeat? I suspect you're experiencing #3016

Yes, you are totally right. It's not related to manually added repeat but to the last one! Sorry!

I retested cases described in https://github.com/getodk/collect/pull/3753#issuecomment-610396844
I don't have anything more to add to this PR. 

@lognaturel, I remember you mentioned it's high priority PR because of a point release. Testing on 4 devices from 6 is finished. We can wait for Kasia's confirmation or check it even after the merge (Android 5.1, 10.0). On the other hand, this PR seams to be quite risky.

2020-04-30 21:11 UTC, lognaturel commented
Thank you, @mmarciniak90! I wouldn't want to release on a Friday anyway so the earliest we would do the point release is your Monday evening. If @kkrawczyk123 can take a quick look before then that'd be great. There's nothing dependent on Android version here so I think it's more about getting another brain to review the cases you and I have tried and see if any other ideas come up.

Happy May Day!

2020-05-04 15:16 UTC, kkrawczyk123 commented
I haven't found anything weirder that @mmarciniak90 has mentioned above on Androids 5.1 and 10. I have checked forms attached and also made some regression checks with all widgets and repeats forms - so I guess we have success here!

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2020-05-04 15:39 UTC, seadowg approved these changes

2020-05-04 15:39 UTC, merged