Update links
getodk/collect pull request #3857
Opened 2020-05-21 22:08 UTC by yanokwa

2020-06-04 10:58 UTC, seadowg requested changes
Just a couple of changes needed I think.

@lognaturel  One thing that we should probably change is the Google Drive root folder we're using (https://github.com/getodk/collect/blob/b41f4bc6fcb4290f22cde48990192128ec9589b4/collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/DriveHelper.java#L39). I'm thinking we'd need to create a migration for this as well though?

2020-06-04 10:58 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> +        // populateDynamicChoices. See https://github.com/github.com/getodk//javarosa/issues/436
Little find and replace typo there I think

2020-06-04 10:58 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/application/Collect.java
> + * The ODK Collect application.
I think we can get rid of this comment. Doesn't seem like it adds anything.

2020-06-04 18:22 UTC, lognaturel commented
> One thing that we should probably change is the Google Drive root folder we're using

I figured it wasn't worth changing but I guess that with a migration it's relatively painless? Can two folders in the same container have the same name? I think it's entirely possible someone would already have an 'ODK' folder. Seems right to treat this as its own issue, anyway.

2020-07-06 22:45 UTC, lognaturel approved these changes

2020-07-06 22:46 UTC, lognaturel commented
@seadowg I went through the diff and things look good to me. Please merge -- I can't do it unless you update your review.

2020-07-07 13:09 UTC, seadowg approved these changes

2020-07-07 13:09 UTC, merged