Fix crash when user removes all repeat groups and presses back button
getodk/collect pull request #3859
Opened 2020-05-22 10:08 UTC by SaumiaSinghal

Closes #3799 

#### What has been done to verify that this works as intended?
I tested it for both the cases mentioned in the issue.

#### Why is this the best possible solution? Were any other approaches considered?
When the tree element of the form is null, the user is directed to the beginning of the form to create a new repeat.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No regression risks, as such now.

#### Do we need any specific form for testing your changes? If so, please attach one.
[nested-repeats.xml.txt](https://github.com/getodk/collect/files/4667376/nested-repeats.xml.txt)
[repeatTest.xml.txt](https://github.com/getodk/collect/files/4667377/repeatTest.xml.txt)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-06-04 11:57 UTC, grzesiek2010 requested changes
I think this is not a perfect solution. You catch that case and call `createViewForFormBeginning` that means if you have let's say a form with 10 questions and then a repeatable group and you reproduce the steps on that group you will be moved to the begging of the form.
I know that understanding and dealing with indexes might be difficult (it's still not easy for me) so let me know if you need help I can dig deeper into possible solutions.

2020-06-04 13:53 UTC, SaumiaSinghal commented
Thanks @grzesiek2010! yes please go ahead. I understand the problem with my solution. I will search more on how this can be fixed without simply going to the beginning of the form, each time this problem is encountered.

2020-06-08 13:01 UTC, grzesiek2010 commented
@SaumiaSinghal  here is my proposal: https://github.com/getodk/collect/pull/3912 please take a look.

2020-06-08 22:16 UTC, lognaturel commented
Good team work here!

2020-06-08 22:16 UTC, closed without merging