Add tests for QR sharing and import
getodk/collect pull request #3886
Opened 2020-06-01 12:20 UTC by seadowg

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-06-11 20:44 UTC, lognaturel commented
We expect debug builds not to work on Android < 7 for the same reasons as https://github.com/getodk/collect/pull/3772#issuecomment-642876177.

2020-06-16 05:09 UTC, lognaturel requested changes
I went through this relatively quickly and focused on the high-level patterns. As noted in the description, the PR is a bit all over the place but it's relatively easy to follow the reasoning going commit by commit so I'm comfortable with it.

I didn't take the time to review the circleci rework in detail. Things look reasonable, I like the references to the CircleCI docs, and I trust that if it doesn't work we'll know immediately. 

I also don't know much about Kotlin Coroutines so it's hard for me to evaluate `CoroutineScheduler`. It certainly looks straightforward, but I don't know if there are any tradeoffs to consider. @seadowg were there any particular decisions you had to make? Like is Dispatchers.IO the only viable background scope? It would also be good for @grzesiek2010 to take a quick look to know this is coming and have a chance to raise objections or questions. The good news is that with the `Scheduler` interface it's not a big deal to swap out the implementation if needed for some reason. Is there any impact on APK size? In the last version we already went up by 1mb for some reason so we should be careful about watching for bumps.

`PreferencesProvider` is a positive change to me.

Other than that the QRCodeViewModel and testing changes look good to me with a couple small things inline.

2020-06-16 05:09 UTC, lognaturel commented on collect_app/src/test/java/org/odk/collect/android/utilities/CachingQRCodeGeneratorTest.java
> +    @SuppressWarnings("PMD.UseAssertEqualsInsteadOfAssertTrue")
Did you try `assertThat(messageDigest, is(cachedMessageDigest))`? I'm pretty sure that just works.

2020-06-16 05:09 UTC, lognaturel commented on collect_app/src/test/java/org/odk/collect/android/utilities/CachingQRCodeGeneratorTest.java
> +        assertEquals(data, result);
Ah, you're not going all-in on Hamcrest these days?

2020-06-16 05:09 UTC, lognaturel commented on collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
> +        inputText("blah");
should be `password`

2020-06-16 05:09 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeViewModel.java
> +                    warning.setValue(null);
Shouldn't this be `qrcode_without_passwords`?

2020-06-16 05:09 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/audio/AudioPlayerViewModel.java
> +    private Cancellable postitionUpdatesCancellable;
postition typo

2020-06-16 05:09 UTC, lognaturel commented on docs/STATE.md
> +* Removing Rx (and other async work) with LiveData + Scheduler abstraction
Removing -> Replacing

2020-06-16 07:58 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/utilities/CachingQRCodeGeneratorTest.java
> +    @SuppressWarnings("PMD.UseAssertEqualsInsteadOfAssertTrue")
I think this must have come from old code as I don't remember adding this annotation. I'm pretty sure you're right so I'll fix this.

2020-06-16 07:59 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/utilities/CachingQRCodeGeneratorTest.java
> +        assertEquals(data, result);
Yeah again this is old code. Will update though.

2020-06-16 08:00 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/utilities/CachingQRCodeGeneratorTest.java
> +    @SuppressWarnings("PMD.UseAssertEqualsInsteadOfAssertTrue")
Oooops. This actually isn't in the final changes.

2020-06-16 08:01 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/utilities/CachingQRCodeGeneratorTest.java
> +        assertEquals(data, result);
This also isn't in the final changes.

2020-06-16 08:01 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
> +        inputText("blah");
😆

2020-06-16 08:03 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeViewModel.java
> +                    warning.setValue(null);
No we don't show a warning where there aren't any passwords available to show in the QR. `qrcode_without_passwords` is only shown when the user actively removes the admin and server password.

2020-06-16 08:04 UTC, seadowg commented on docs/STATE.md
> +* Removing Rx (and other async work) with LiveData + Scheduler abstraction
Ach nice catch

2020-06-16 08:14 UTC, seadowg commented
@lognaturel in terms of coroutines I'm honestly not that experienced either. As far as decisions go:

* I followed the docs on Coroutine performance for making decisions about dispatchers (https://developer.android.com/kotlin/coroutines-adv#main-safety). We can definitely do even better and have coroutines run in the specific `viewModelScope`/`lifecycleScope` and also start using the `Dispatchers.Default` where appropriate. I think this really requires the call site to be Kotlin however so that's a bit down the line.
* There is the Espresso trade off - Espresso is unable to sync with Coroutine dispatchers in the same way it does for AsyncTask's thread pool. I've built tooling (the `CountingScheduler` etc) around this however.
* There probably is an impact to APK size: I think we might need to make sure our submodules are proguarded as it looks like they aren't right now. I don't think we'll see a large increase other than that as it looks like we were already pulling in the Kotlin standard lib as part of Android deps. I'd prefer to not add anything to this PR though and suggest we measure that and fix after merge.

2020-06-16 20:31 UTC, lognaturel commented on collect_app/src/test/java/org/odk/collect/android/utilities/CachingQRCodeGeneratorTest.java
> +        assertEquals(data, result);
Ooops, sorry. I usually go back and check when I go commit by commit but didn't with these.

2020-06-16 20:34 UTC, lognaturel commented
I'm satisfied by those answers. It can be iterated on, anyway.

> I think we might need to make sure our submodules are proguarded as it looks like they aren't right now

That likely explains the size increase with the last release. Could you please file an issue for the v1.28 milestone?

When you make those couple small changes above it's an accept from me.

2020-06-17 12:48 UTC, seadowg commented
@lognaturel ach I made those changes and then didn't push them. My bad. They're up now.

2020-06-18 16:03 UTC, lognaturel approved these changes

2020-06-24 10:10 UTC, seadowg commented
I'm going to set this to "needs testing" as I'm starting to get into problems where I want to work on top of some of this stuff AND other PRs that are in review. @grzesiek2010 if you have any comments happy to chat here or on Slack!

@getodk-bot label "needs testing"

2020-06-24 10:41 UTC, grzesiek2010 approved these changes

2020-06-24 14:03 UTC, kkrawczyk123 commented
@seadowg I have started testing but unfortunately Collect is crashing when open Configure via QR code from both menu and admin settings on Android 7 and 10 - it is not on Android 5.1 so it is connected to permissions. When I enabled Camera permissions through App settings I was able to open it and the crash was not visible. 
stacktrace:
`2020-06-24 15:54:56.090 17945-17945/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 17945
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.odk.collect.android.preferences.qr.QRCodeMenuDelegate.onCreateOptionsMenu(android.view.MenuInflater, android.view.Menu)' on a null object reference
        at org.odk.collect.android.preferences.qr.QRCodeTabsActivity.onCreateOptionsMenu(QRCodeTabsActivity.java:107)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4093)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2830)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`
 
I have also checked the master where the crash does not occur.

2020-06-24 17:47 UTC, seadowg commented
@kkrawczyk123 ach I see the problem. Pushing a fix now.

2020-06-26 08:20 UTC, kkrawczyk123 commented
**Tested with success!**
Verified on Androids: 5.1, 7.0, 8.1, 9.0 and 10.

Tested cases:
- configure via QR code
- scan
- valid
- invalid
- inverted
- generate
- import from QR code file
- invalid 
- valid 
- Admin password
- different Admin password and server password - they are not mixed
- checked all permission dialogs: no crashes
- barcode widget
- front barcode widget
- audio widget
- selfie widget
- selfie video widget

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2020-06-29 08:00 UTC, merged