Refractor jar in libs with gradle dependency (#296)
getodk/collect pull request #399
Opened 2017-02-09 13:04 UTC by shobhitagarwal1612

2017-02-09 23:23 UTC, grzesiek2010 commented
You should start your branch from master. As you can see now there is an extra commit here.

2017-02-09 23:24 UTC, grzesiek2010 requested changes

2017-02-09 23:24 UTC, grzesiek2010 commented on collect_app/build.gradle
> +
Remove these unnecessary lines.

2017-02-09 23:26 UTC, grzesiek2010 commented
As I noticed guava library is unnecessary so I think you can remove this jar in this pr (but in separate commit) or am I wrong?

2017-02-09 23:28 UTC, grzesiek2010 commented
What about the others jars? Here is a dependency for for osmdroid for example: // https://mvnrepository.com/artifact/org.osmdroid/osmdroid-android
compile group: 'org.osmdroid', name: 'osmdroid-android', version: '4.2'

2017-02-10 05:10 UTC, shobhitagarwal1612 commented
@grzesiek2010 Sorry for the extra commit. I will fix it.

2017-02-10 05:11 UTC, shobhitagarwal1612 commented
Also, the http-client is deprecated now, so its gradle dependency gives deprecated warning

2017-02-10 06:40 UTC, shobhitagarwal1612 commented
For this library `osmbonuspack_v4.6.jar` I found out its gradle `'com.github.MKergall:osmbonuspack:6.2'` (https://github.com/MKergall/osmbonuspack). But this library uses minSdkVersion 10 and project's minSdkVersion is 9.
Since v4.6 is not available now so only alternative is to change minSdkVersion to 10. Also some of the methods used in v4.6 are deprecated in v6.2

2017-02-10 08:13 UTC, merged

2017-02-10 08:16 UTC, lognaturel commented
Thank you very much, @shobhitagarwal1612! 😊 You did the right thing with leaving `http-client` and `osmbonuspack` as they are. Can you please copy your notes on both of them and any other interesting findings from libraries you couldn't move to maven control on #296? That will help us continue the process.

I'm also going to file a quick issue for style of the gradle file. That might be a good one for you to take @shobhitagarwal1612 since you've just been in that file so I'll tag you on it in case you want to do it.