Remove Answer Text View in Url Widget
getodk/collect pull request #4025
Opened 2020-08-11 21:48 UTC by SaumiaSinghal

This PR updates the UI of the URL widget. As discussed in ODK forum [here](https://forum.getodk.org/t/use-materialcardview-to-update-the-ui-of-url-widget/27500/6), answer text view is removed and user simply sees the button to open the url in the widget.  

I still need to decide upon some issues regarding the behavior of URL widget. According to the current implementation, url button is not shown when the widget is `readonly`, but as the user is not allowed to change the answer anytime, so the widget is readonly at all times. I feel like not showing/disabling the url button when the url is empty.

![WhatsApp Image 2020-08-12 at 03 13 53](https://user-images.githubusercontent.com/35730054/89952154-57fb5080-dc4a-11ea-85c9-377859c648c9.jpeg)

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I changed the value fo the string resource `open_url` to `Visit Website`, and that change is not migrated to all the other languages of Collect, so this change won't appear good in when the user views the form in a language other than English. 

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form having URL Widget like AllWidgetsForm.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-08-12 15:07 UTC, seadowg commented
> I still need to decide upon some issues regarding the behavior of URL widget. According to the current implementation, url button is not shown when the widget is readonly, but as the user is not allowed to change the answer anytime, so the widget is readonly at all times. I feel like not showing/disabling the url button when the url is empty.

My thinking here is that in the `readonly` case the widget should be no different as the "answer" is never changeable. Would be good to get second opinions from @grzesiek2010 and @lognaturel on that though.

2020-08-12 15:14 UTC, seadowg commented
Another point to make here is that it's been really hard to make calls about the URL widget as we don't have a clear picture of how it is used or even if it is used at all. I think as part of this change it would be nice to add an analytics call that gets made when a URL widget is included in a form. 

We could probably have the `WidgetFactory` make a call whenever it creates a `URLWidget`. I'd imagine this could use the "Prompt" category (that audio labels are using) and pass the form analytics ID (`QuestionDetails#getFormAnalyticsID()`) to make sure we can answer the question "how many forms contain URL widgets?" rather than just "how many times is a URL widget rendered?". @SaumiaSinghal could you look at adding that in as part of these changes?

2020-08-25 11:16 UTC, seadowg requested changes

2020-08-25 11:16 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/widgets/UrlWidgetTest.java
> +        assertThat(widget.binding.urlButton.getVisibility(), equalTo(View.GONE));
As discussed the URL widget should behave exactly the same in read only mode (as it is always "read only"). That being the case you shouldn't need any tests for read only for the widget.

2020-08-25 11:16 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
>          if (prompt.isReadOnly()) {
As in other comments: lets remove any change in behaviour based on `isReadOnly`

2020-08-25 11:16 UTC, seadowg commented on collect_app/src/main/res/values/strings.xml
> +    <string name="open_url">Visit Website</string>
Lets not change this text at the moment.

2020-08-25 15:58 UTC, seadowg approved these changes

2020-09-09 15:45 UTC, seadowg requested changes
Just a couple of small changes to go in!

2020-09-09 15:45 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.java
> +    public static final String URL_WIDGET = "Prompt";
This doesn't seem right as it's the same as the `AUDIO_QUESTION`. I think the `AUDIO_QUESTION` naming and description is just wrong here and probably should be `PROMPT` and really be used to just track any kind of question/widget.

2020-09-09 15:45 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
> +                            analytics.logEvent(URL_WIDGET, "UrlWidget", questionDetails.getFormAnalyticsID());
I think the action here should just be `"Url"`. What we care about is that the user saw a url question.

2020-09-10 12:22 UTC, seadowg approved these changes

2020-09-10 12:23 UTC, seadowg commented
@lognaturel I think this would be nice to include in the release as it adds analytics. What do you think?

2020-09-28 11:53 UTC, mmarciniak90 commented
@SaumiaSinghal please take a look at my test results. 

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/94428567-29e9b580-0191-11eb-873c-9b2f71a656a0.png">

>I changed the value fo the string resource open_url to Visit Website

:red_circle: **Visit Website** text on the button is not visible

> I feel like not showing/disabling the url button when the url is empty.

:red_circle: I added a screenshot where url is empty and as you can see, button is visible and it's clickable. Toast with message appears

:large_blue_circle:  website address is not visible under the button -> the result is that the user has no idea whether the URL is set or not until the user clicks on button or open hierarchy view. It seems ok but it is worth paying attention to.
:green_circle: remove reponse dialog is not available for readonly url widget
:green_circle: readonly url widget has button and visit website is possible

2020-09-28 12:35 UTC, SaumiaSinghal commented
Hi @mmarciniak90! Thanks for testing the PR. I am sorry, I forgot to change the description of this PR. We decided not to change the button text for the moment, as we have to look into the string translations then. Also, we will not be showing the answer textview of the widget as mentioned in the header of the PR. Regarding the case when there is no answer set, I'll confirm about that case with my mentor and update the PR. Thanks!

2020-09-29 08:58 UTC, seadowg commented
I think for the no answer case we can just go with the current behaviour (that @mmarciniak90 is seeing). I think we're very unlikely to see that case in real life as it would be a mistake in the form and the current behaviour is actually pretty good for bubbling that mistake up to the user without interrupting the form.

2020-10-01 05:48 UTC, kkrawczyk123 commented
**Tested with success!**
Verified on Androids: 5.1, 7.0, 7.1, 8.1, 9.0 and 10

Tested cases:
- light/dark mode
- read only
- open url
- minimize app
- screen rotation
- RTL language 
- try to remove answer

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2020-10-01 05:49 UTC, kkrawczyk123 commented
@getodk-bot label "behavior verified"

2020-10-05 08:19 UTC, seadowg commented
@SaumiaSinghal looks like we've got conflicts and failing checks.

2020-10-06 06:06 UTC, SaumiaSinghal commented
Done!

2020-10-06 07:00 UTC, merged