Match exactly tweaks and polish
getodk/collect pull request #4038
Opened 2020-08-24 12:14 UTC by seadowg

Blocked by #4020 

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-08-27 16:17 UTC, seadowg commented on collect_app/src/main/res/drawable/ic_baseline_refresh_error_24.xml
> +      android:pathData="M3,12c0,2.21 0.91,4.2 2.36,5.64L3,20h6v-6l-2.24,2.24C5.68,15.15 5,13.66 5,12c0,-2.61 1.67,-4.83 4,-5.65L9,4.26C5.55,5.15 3,8.27 3,12zM11,17h2v-2h-2v2zM21,4h-6v6l2.24,-2.24C18.
This icon is intended for representing sync problems in Material. Perfect!

2020-08-27 16:45 UTC, seadowg commented on async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt
> +    override fun immediate(foreground: java.lang.Runnable) {
This ended up not being needed for anything but will be nice to have in the future I think.

2020-08-27 18:03 UTC, lognaturel requested changes
Great! Currently the form update icon is still visible when searching. Not a deal breaker but probably shouldn't be maintained.

2020-08-27 18:03 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +    <string name="manually">Manual</string>
While here, can I ask you to change the resource name. 🙈

2020-08-27 18:03 UTC, lognaturel commented on collect_app/src/main/res/values/strings.xml
> +    <string name="form_update_complete">Form update complete</string>
How about "Form update succeeded" or "Form update completed successfully"?

2020-08-28 10:10 UTC, seadowg commented
> Currently the form update icon is still visible when searching. Not a deal breaker but probably shouldn't be maintained.

This is a little awkward to fix but I'll see if I can squeeze it into this PR!

2020-08-28 17:44 UTC, seadowg commented
@lognaturel ok fixed! Ran into some nasty Robolectric/Support library problems with testing but think I might have a slightly less Robolectric intense process for testing menu delegates now.

2020-08-28 21:13 UTC, lognaturel approved these changes

2020-08-28 22:03 UTC, lognaturel commented
Just needs a rebase on master and then can be tagged for testing. 👍

2020-08-29 00:21 UTC, lognaturel requested changes
I just realized that this changes all progress bars. I don't think that's right. E.g. there's a progress bar shown each time a form list loads. Generally this should be instant and there's only ever work done if there are new files on disk to be scanned. Now the progress bar makes it feel like something is happening each time.

2020-08-30 18:57 UTC, seadowg commented
@lognaturel yeah I agree it felt right at first but after playing with it more I'm not liking it either.

2020-08-31 13:34 UTC, lognaturel approved these changes

2020-09-02 14:07 UTC, mmarciniak90 commented
> Show progress bar for a minimum amount of time so on form list pages so it's obvious to the user things are happening

@seadowg could you give me some clue about this? To be honest, I can't notice a difference.

Verified cases:
* refresh button when there has been an error
* size of other icons in app bar on all pages
* "Manual" instead of "Manually" 
*  toast when the match exactly sync is successful 
* light/dark mode
* RTL language

|![Screenshot_20200902-154551](https://user-images.githubusercontent.com/3907554/91993755-0d935e00-ed36-11ea-9ea7-4530b71be723.png)|![Screenshot_20200902-154611](https://user-images.githubusercontent.com/3907554/91993758-0ec48b00-ed36-11ea-970c-b881e6709ddb.png)|![Screenshot_20200902-154625](https://user-images.githubusercontent.com/3907554/91993760-0ec48b00-ed36-11ea-8e19-4c421c092e00.png)|![Screenshot_20200902-154519](https://user-images.githubusercontent.com/3907554/91993763-0f5d2180-ed36-11ea-858d-13824b7fe6f6.png)|
|---|---|---|---|

2020-09-02 14:11 UTC, seadowg commented
@mmarciniak90 just that when you hit refresh (🔃) in "Fill Blank Form" with match exactly enabled the progress bar should show for a half second even if the network request is faster than that. Nothing to verify there other than that the progress bar doesn't seem to be broken in any way!

2020-09-03 11:25 UTC, mmarciniak90 commented
>  the progress bar should show for a half second

@seadowg hmm, I can see this progress bar for even 10 seconds when I click on refresh icon when all forms are in device. 

> progress bar doesn't seem to be broken in any way!

Agree

2020-09-03 11:27 UTC, seadowg commented
> hmm, I can see this progress bar for even 10 seconds when I click on refresh icon when all forms are in device.

That's fine (I'm assuming the server has a lot of forms or is slow). The problem was that if the server was very fast it looked like nothing had happened.

2020-09-04 11:13 UTC, kkrawczyk123 commented
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 10.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2020-09-04 11:16 UTC, merged