Fixed strange bug with mixing answers in field-list
getodk/collect pull request #4063
Opened 2020-09-03 12:34 UTC by grzesiek2010

Closes #4062

#### What has been done to verify that this works as intended?
I tested the solution manually.

#### Why is this the best possible solution? Were any other approaches considered?
I haven't seen anything so confusing for a very long time. At first when I saw the issue I said to myself ok I must have made some stupid bugs implementing changes in selects, it happens I will fix it in 30 minutes but then I started investigating the issue and I wasn't able to find any bug.
After debugging, playing with other widgets that use view binding my gut said try to just use a different view element to display answers and bingo it turned out that the issue happens when we use `EditTexts`.
I have no idea why. What's interesting the problem occurs only if we rotate a device, if we navigate to another question and then back everything is fine despite the fact that exactly the same methods are called building widgets in both cases.
@seadowg @SaumiaSinghal can you maybe explain that magic?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
this fix shouldn't cause any change or risk so testing only the issue would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
The forms attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-09-03 15:46 UTC, seadowg commented
@grzesiek2010 I think this could be because the Activity will automatically save the text of `EditText` views in the `onSaveInstanceState` bundle and then restore it after rotation using the view ID. Here the view ID for all the `EditText`s would be the same, so I guess it would restore every one of them with the same value. This is just a theory though and finding docs on `EditText` behaving like this is really hard (there is an SO [here](https://stackoverflow.com/questions/12420396/how-to-retain-edittext-data-on-orientation-change) though). I guess we can verify by checking the bundle in `onSaveInstanceState` and `onCreate` in the debugger.

If that is the case then an alternative fix might be to use a `View.generateViewId()` in the widget to set a different ID to on the `EditText`. One advantage of that is that it'd be testable but I'm worried it could cause problems for view binding?

2020-09-03 16:12 UTC, seadowg commented
Ok partly confirmed. I used the `FieldListUpdateTest` form to quickly get a Select Minimal widget and if I rotate after selecting "Mango" I do end up with an item in the bundle with `"Mango"` which I think is what ends up getting loads into the view:

<img width="1438" alt="Screenshot 2020-09-03 at 17 10 22" src="https://user-images.githubusercontent.com/556280/92140067-8c58cb80-ee08-11ea-99d7-6ec17da55875.png">

2020-09-03 16:41 UTC, grzesiek2010 commented
Oh right I knew but somehow forgot about that tricky behavior. In that case I think we can just disable it using [saveEnabled="false"](https://developer.android.com/reference/android/view/View#attr_android:saveEnabled)
We also need to remember about it because once we refactor text widgets to use view binding we will have the same issue.

2020-09-03 16:46 UTC, seadowg commented
@grzesiek2010 hah that's a nicer solution. Yeah it's scarily subtle and not something you expect.

2020-09-03 16:54 UTC, seadowg requested changes
As @grzesiek2010 suggested.

2020-09-04 09:24 UTC, seadowg approved these changes
Nice!

2020-09-04 12:25 UTC, mmarciniak90 commented
**Tested with success**

Verified on Android versions: 7.0, 8.1, 9.0

Verified cases:
* both forms
* rotate device orientation several times (on a new and edited form)
* light/dark mode
* RTL language

2020-09-04 12:42 UTC, kkrawczyk123 commented
Tested on Androids: 5.1, 7.1 and 10.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2020-09-04 12:44 UTC, merged