Fixed checking for spaces in underlying values
getodk/collect pull request #4082
Opened 2020-09-14 10:51 UTC by grzesiek2010

Closes #4078

#### What has been done to verify that this works as intended?
I tested implemented changes manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I moved checking for spaces in underlying values to the main ItemsWidget class what is the best solution because all widgets that need the warning extend that class, so we have everything in one place and we can test it easily.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We need to test the form attached to he issue and I think it would be enough since the change is pretty safe and we have automated tests.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue is ok.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-09-14 21:54 UTC, lognaturel requested changes
It's ok to have spaces in single-select question types so I think this is too aggressive.

This regression shows the tests were clearly not covering enough -- it's important to have a test that verifies the check for spaces is actually done. I wonder whether passing in the `SpacesInUnderlyingValuesWarning` to each relevant widget type is the best way, though. Did you consider a Robolectric test that checks for the warning text in the view? I think it may then be ok for the `SpacesInUnderlyingValuesWarning` dependency to be an implementation detail (managed internally). That does mean you'd have to have an explicit, separate test for each question type that allows multiple selections. Might be worth a quick sanity check with @seadowg on the approach.

2020-09-14 21:54 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/items/RankingWidget.java
> +        getOrderedItems();
This is not a new change but a getter that mutates is dangerous, I think. A rename to `buildOrderedItems` would help.

2020-09-16 11:15 UTC, grzesiek2010 commented
@lognaturel you are right I made a mistake implementing the warning for all selects. I prepared a new solution, please review.

2020-09-16 16:37 UTC, lognaturel approved these changes
Thanks, looks great! For QA, the risk here is forgetting one of the multi select types. I double checked and I think all are accounted for.

2020-09-17 08:58 UTC, kkrawczyk123 commented
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 9.0

Tested scenarios:
- form from issue
- select one questions
- select multiple questions
- column pack form
- light/dark mode 
- screen rotation/minimize

2020-09-17 09:03 UTC, mmarciniak90 commented
Tested with success on Androids 7.0, 8.1, 10.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2020-09-17 09:08 UTC, merged