Prevent crash when updating buttons on Main Menu
getodk/collect pull request #4330
Opened 2020-12-21 14:22 UTC by seadowg

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2020-12-21 14:27 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> -    private int completedCount;
We don't need to keep any of this state in the Activity any longer.

2020-12-21 14:28 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> -            finalizedCursor.requery();
`requery` is deprecated. The advise is to just open a new cursor.

2020-12-21 14:29 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
> -            startManagingCursor(viewSentCursor);
`startManagingCursor` is deprecated. Instead of doing this I've switched it to using `try-with-resource` to manage opening/closing.

2020-12-21 23:40 UTC, lognaturel requested changes
I'm totally with you for the first 3 commits. But I'm having a little trouble with the 4th. It means that if the migration were running and `updateButtons` were called, an error dialog would be shown to the user, right? Seems to me that you had the right idea before with silently catching that exception. I'd just let the counts be 0 in that case and next time the user gets back to the main menu the buttons would be updated using the new counts. I think this is the right thing to do for any exception that comes out of getting those counts because it's not essential functionality. We can do a `Timber.e` to track frequency if you want but even that doesn't seem critical. If there's a real db issue then it'll manifest when the user tries to get a form list, open a form, etc.

2020-12-22 14:22 UTC, seadowg commented
> I'm totally with you for the first 3 commits. But I'm having a little trouble with the 4th. It means that if the migration were running and updateButtons were called, an error dialog would be shown to the user, right?

Not my intention. I just moved the error handling over that was there before in `countSavedForms` when it did the db queries. I wouldn't expect the crash we were seeing to happen again as the 3rd commit removes the code that was holding onto `Cursors`.  Totally agree that `catch` clauses probably don't even need to be there though. Let's chat this through and work out which version we want to put out there.

2020-12-22 17:39 UTC, lognaturel commented
@seadowg and I talked about adding a (maybe overly) defensive `!storageMigrationRepository.isMigrationBeingPerformed()` wrap around `updateButtons` and also ignoring any exceptions and letting counts be 0.

2020-12-22 17:57 UTC, lognaturel approved these changes

2020-12-22 17:57 UTC, merged