Form downloader
getodk/collect pull request #4339
Opened 2021-01-11 11:01 UTC by seadowg

Closes #4044

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2021-01-11 13:15 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDetails.java
> +    public ServerFormDetails(String formName, String downloadUrl, String formID, String formVersion, String hash, boolean isNotOnDevice, boolean isUpdated, ManifestFile manifest) {
We don't need a manifest url in here any longer as the manifest is fetched before creating this object.

2021-01-13 20:06 UTC, lognaturel requested changes
I think while we're here, "The server (<url>) returned status code XXX" and "The server (<url>) provided an invalid response" followed by the standard "if it continues, talk..." would be helpful in `FormSourceExceptionMapper`.

I'm happy other than that so please mark as `needs testing` once that's in. It will be hard to try the error cases in QA since that would require a server with bad responses so @seadowg's comment about generally doing regression checks on download seem right.

2021-01-14 15:47 UTC, lognaturel approved these changes

2021-01-19 15:35 UTC, mmarciniak90 commented
**Tested with success**

Verified on Android versions: 7.0, 8.1, 10.0

Verified cases:
- download forms with success
- download forms with and without media
- download a lot of forms
- download failed because required credentials are missing
- download failed because of invalid credentials
- download failed because invalid URL
- plane mode turned on during downloading
    - Android 10 returned status code 0
- no internet connection
- downloading from Aggregate
- downloading from Central
    - status code 400 when URL has a letter at the end instead of project number
    - invalid project number
- downloading from KOBO
- downloading from ONA
- local server - download forms, send submissions, match exactly
   - HTTPS issue - expected error
   - wrong port number - status code 0
- regression check for Google Drive

2021-01-19 15:36 UTC, kkrawczyk123 commented
Verified also on Androids 5.1, 7.1 and 9.0.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2021-01-19 15:55 UTC, lognaturel commented
One thing I notice is that "status code 0" is not very helpful since that's not an HTTP code. Haven't looked in detail what an easy alternative would be. Maybe identifying 0 and throwing a `Unreachable` instead? (Side note, I notice that should really be `UnreachableError`)

2021-01-19 17:57 UTC, seadowg commented
@lognaturel @mmarciniak90 hmm yeah I'll check out and try and fix those status 0 cases before merging.

2021-01-19 18:11 UTC, seadowg commented
@mmarciniak90 are you able to post reproduction steps for one of the status 0 cases? I'm having a little trouble making it happen.

2021-01-19 19:24 UTC, mmarciniak90 commented
> are you able to post reproduction steps for one of the status 0 cases?

I needed to investigate a bit to define repro steps. @seadowg please, try these steps:

Steps:
1. Default server (where the anonymous user is allowed) is set and march exactly is turned on
2. Sync is finished with success
3. I changed the default server to https://agg-17.appspot.com where the anonymous user is NOT allowed. I added credentials.
4. I opened the `Fill Blank Form` page and clicked the refresh button, then I turned on plane mode

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/105081718-d75f3c80-5a92-11eb-8d0e-1b769218b25f.png">

2021-01-20 10:31 UTC, seadowg commented
Looks like the problem was timeouts. I've fixed it, so you should now see the generic error message when this happens.

@mmarciniak90 Definitely useful if you could check the cases you found out again to make sure we're not seeing that 0 status code anywhere.

@lognaturel I think we may want an error message/analytics event for timeouts. What do you think? I think if so we can create an issue so as not to hold this up.

2021-01-20 12:12 UTC, kkrawczyk123 commented
@seadowg I have re-tested:
- status code 0 not visible for both cases: wrong port number on local aggregate and airplane mode scenario
- quick regression check on other errors 

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

2021-01-20 17:00 UTC, lognaturel commented
> I think we may want an error message/analytics event for timeouts.

Yes! A separate issue sounds great.

2021-01-20 17:00 UTC, lognaturel approved these changes

2021-01-21 09:17 UTC, merged