Return to free-plan defaults
getodk/collect pull request #4563
Opened 2021-05-13 19:38 UTC by yanokwa

2021-06-02 12:56 UTC, seadowg requested changes

2021-06-02 12:56 UTC, seadowg commented on .circleci/gradle.properties
> +org.gradle.jvmargs=-Xmx3686M -Dkotlin.daemon.jvm.options\="-Xmx3686M"
I think the container probably needs a little more mem for itself. Maybe try 3072m?

2021-06-02 16:46 UTC, yanokwa commented
Seems to be working now. This PR builds in 10 minutes (~0/month) while master builds in 6-8 minutes (~100/month)

2021-06-02 21:32 UTC, yanokwa commented
I re-ran it and mine is 8 minutes and Grzegorz's PRs off master are 10 minutes, so 🤷🏾‍♂️

2021-06-03 21:00 UTC, seadowg approved these changes

2021-06-03 21:13 UTC, merged