Prompt for confirmation when duplicate project configured
getodk/collect pull request #4697
Opened 2021-07-15 06:38 UTC by lognaturel

When multiple projects with identical connection settings are configured, it's possible to get in bad states like having some submissions in one duplicate project that never get sent. This PR checks for matching connection settings and prompts the user to either switch to the existing project or actually create a duplicate.

#### What has been done to verify that this works as intended?
Added and ran automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I am not very satisfied with the control flow but couldn't come up with anything I liked better. I wanted to use some kind of view model but I don't see a reasonable way to communicate UI actions back to the configuration dialogs.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Everything around project creation is at risk. I think the worst outcome would be that users are prompted for confirmation to create non-duplicate projects.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Yes. https://github.com/getodk/docs/issues/1365

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2021-07-15 15:03 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
> +    @Provides
Don't need to inject

2021-07-15 15:08 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/projects/DuplicateProjectConfirmationDialog.kt
> +    lateinit var listener: DialogInterface.OnClickListener
Use a specific interface instead of this generic one

2021-07-15 15:22 UTC, seadowg requested changes

2021-07-15 15:22 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/projects/SettingsConnectionMatcherTest.kt
> +        inMemProjectsRepository.deleteAll()
Every test gets a new object so you don't these these clean ups.

2021-07-15 15:22 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/projects/SettingsConnectionMatcherTest.kt
> +    fun `returns a match when urls match`() {
`returns matching project...`

2021-07-15 15:22 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
> +    public SettingsConnectionMatcher providesSettingsConnectionMatcher(ProjectsRepository projectsRepository, SettingsProvider settingsProvider) {
Don't think you need this?

2021-07-15 15:22 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/projects/DuplicateProjectConfirmationDialog.kt
> +        listener = parentFragment as DialogInterface.OnClickListener
I think this would be nicer with a specific interface

2021-07-15 15:22 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
> +                        DialogUtils.showIfNotShowing(DuplicateProjectConfirmationDialog::class.java, childFragmentManager)
You could pass the `lastScannedJson` and `lastMatchingUuid` into the dialog here using as args. `showIfNotShowing` can take args in as a `Bundle`.

2021-07-15 15:22 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
> +                        DialogUtils.showIfNotShowing(DuplicateProjectConfirmationDialog::class.java, childFragmentManager)
And then pass those values back on clicks.

2021-07-16 08:43 UTC, seadowg approved these changes

2021-07-16 09:18 UTC, merged