Collect 4710
getodk/collect pull request #4713
Opened 2021-07-21 10:48 UTC by grzesiek2010

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2021-07-21 12:44 UTC, seadowg requested changes
I'm wondering if a simpler implementation (which would also need less testing) would be to just have the `ProjectDeleter` clear the general and admin settings for the project directly. That way we only need to make changes to `ProjectDeleter`. It could also be tested pretty easily using the `InMemSettingsProvider` - the general and admin could be set up with any keys (`foo`, `bar` etc) and then checked to see that they are gone after project deletion.

I guess that would leave references to old settings objects around in `SharedPreferencesSettingsProvider` but they're just in-mem and I don't think would cause any problems?

What do you think?

2021-07-21 16:30 UTC, lognaturel approved these changes, later dismissed
Great! I think the most compelling reason to do this ends up being not to leave user credentials lying around.

2021-07-21 16:34 UTC, lognaturel commented
Sigh, hadn't noticed @seadowg's change request. Simpler and more easily testable is certainly nice. I agree it wouldn't be an issue to temporarily leave settings in memory. But I don't feel strongly about making the change.

2021-07-22 11:05 UTC, grzesiek2010 commented
> What do you think?

Yeah it makes the fix a bit smaller so here you go.

2021-07-22 12:00 UTC, seadowg approved these changes
Looks great! One comment about a line I don't think we need, but nothing blocking this getting merged for me.

2021-07-22 12:00 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/projects/ProjectDeleterTest.kt
> +@RunWith(AndroidJUnit4::class)
I don't think you need the Android test runner here right?

2021-07-22 12:22 UTC, merged