Move ToastUtils to androidshared
getodk/collect pull request #4827
Opened 2021-09-21 12:37 UTC by seadowg

This is prep for #4768 (need to move some files that depend on `ToastUtils` between modules)

#### What has been done to verify that this works as intended?

Ran tests

#### Why is this the best possible solution? Were any other approaches considered?

I did consider just deprecating `ToastUtils` and removing it from the files that I needed to move, but after discussing with @grzesiek2010 we decided to hold on to it. The main reason for this is that we believe the ability to hide the last toast when displaying a new one is helping keep our UI tests stable.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Shouldn't be any change in behaviour as it's just moving code around. Don't think we need QA on this.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

2021-09-23 21:01 UTC, grzesiek2010 requested changes

2021-09-23 21:01 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
> +            ToastUtils.showShortToast(Collect.getInstance(), R.string.no_connection);
Why not `this`? You do that in many places so I'm not going to comment every single one. It doesn't have to be application context right? So why do you still using `Collect.getInstance()` when we wanted to get rid of it?

You use it to pass as a parameter calling `makeToast` but the documentation says:

` The context to use. Usually your android.app.Application or android.app.Activity object.`

so it doesn't have to be application context.

2021-09-24 10:37 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
> +            ToastUtils.showShortToast(Collect.getInstance(), R.string.no_connection);
Ah I used refactoring tools to pull that parameter out. I went through and changed a few of the `Collect.getInstance()` calls that called pulled up to whatever local contexts there was, but I probably missed a few. I'll go through it again.

2021-09-24 15:26 UTC, grzesiek2010 approved these changes

2021-09-24 18:10 UTC, merged