Add user property to track adoption of Match Exactly
getodk/collect pull request #4848
Opened 2021-10-05 17:02 UTC by seadowg

Closes #4779

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2021-10-06 14:26 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/support/CollectHelpers.java
> -    public static FormController waitForFormController() throws InterruptedException {
Not using these any longer!

2021-10-06 14:27 UTC, seadowg commented on collect_app/src/main/AndroidManifest.xml
> +            <meta-data  android:name="org.odk.collect.android.application.initialization.UserPropertiesInitializer"
We only ever need to specify `Initializer`s explicitly if no others depend on them.

2021-10-06 14:27 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/application/Collect.java
> +        singleton = this;
This needs to move here for anything that might need access to it before `onCreate`

2021-10-06 14:29 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
> +            WorkManager.initialize(context, new Configuration.Builder().build());
We just call `WorkManager.initialize` lazily now.

2021-10-06 14:30 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/application/RobolectricApplication.java
> +        Robolectric.setupContentProvider(InitializationProvider.class);
Robolectric doesn't automatically boot up providers

2021-10-14 18:49 UTC, lognaturel requested changes
Change request: I think we should only count projects where the server URL is not https://demo.getodk.org/. I suspect a number of people are just leaving the demo project and that could possibly really skew the results.

General comments/questions: Unfortunately, I'm having some trouble convincing myself that using the app startup library is a win. The approach here seems ok but it is adding another dependency and another layer so I do want to make sure the benefits have been considered.

I've read through the [App Startup](https://developer.android.com/topic/libraries/app-startup) docs and worked on understanding its purpose. My understanding is that its biggest value is in replacing [`ContentProvider`-based initialization for libraries that need `context`](https://andretietz.medium.com/auto-initialize-your-android-library-2349daf06920) or to avoid having an `Application` subclass. I'm not seeing either of these applying to Collect. It also feels like more initialization could happen as part of dependency creation/injection (or maybe this is part of moving away from Dagger one day?).

Wish I'd thought through this a little earlier so we had a chance to quickly discuss! I can hand off to @grzesiek2010 here to do a final review. It's likely I'm just overlooking a benefit and/or not seeing how App State enables future improvements. If @seadowg and @grzesiek2010 see value to introducing it then I approve once the small change described above is implemented.

2021-10-14 18:49 UTC, lognaturel commented on collect_app/build.gradle
> +    implementation("androidx.startup:startup-runtime:1.1.0")
For consistency, this feels like it should be in `Dependencies` and grouped with other androix-prefixed dependencies.

2021-10-14 18:49 UTC, lognaturel commented on collect_app/build.gradle
> +    implementation Dependencies.androidx_startup
This should go with other dependencies that have an `androidx` prefix. I think it's not just for aesthetics -- there's value to knowing all the androidx "stuff" we're carrying around at a glance. I'd also tend to order `Dependencies` the same way but that's probably just aesthetic.

2021-10-14 18:54 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
> +            WorkManager.initialize(context, new Configuration.Builder().build());
This makes a lot of sense and is what I mean by letting DI do more initialization. Am I correctly understanding that this wasn't possible before because WorkManager used ContentProvider initialization and now because it uses App Startup we can explicitly disable its automatic initialization? That seems like a very compelling use of the library by `WorkManager`.

2021-10-15 09:47 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
> +            WorkManager.initialize(context, new Configuration.Builder().build());
We can explicitly disable it with or without using App Startup ourselves, but it's an example of how we're technically already opted in to this system with some Android libraries.

2021-10-15 09:47 UTC, seadowg commented
> Change request: I think we should only count projects where the server URL is not https://demo.getodk.org/. I suspect a number of people are just leaving the demo project and that could possibly really skew the results.

Ah good point. I had completely missed the fact that the demo projects are using manual downloads. Will change.

> General comments/questions: Unfortunately, I'm having some trouble convincing myself that using the app startup library is a win. The approach here seems ok but it is adding another dependency and another layer so I do want to make sure the benefits have been considered.

For me it comes down to the fact that I was slowly building our own framework for initialization so that we could have a "list" of initialization steps (that are testable independently). The main benefit in my mind is having a documented, non-custom version of that. This also explicitly moves our initialization away from `Application#onCreate` which will hopefully decrease the noise inside our application object and gives us control of what actually kicks off initialization (we can't control when `Application#onCreate` is called during tests for instance). We did have that with `ApplicationInitializer` but, again, it's a pretty messy custom component.

>  It also feels like more initialization could happen as part of dependency creation/injection (or maybe this is part of moving away from Dagger one day?).

Generally I'd like to keep as much crucial stuff out of the Dagger module declarations as it's easy for details to get hidden in there. I think we still want to be doing things as "lazily" as possible however and on that we should be looking for opportunities to take initialization code and move it elsewhere (like we just did with storage initialization). I'd love to move away from Dagger one day though!

2021-10-15 12:34 UTC, grzesiek2010 requested changes
The implementation is fine itself but I don't understand why a pr that should solve one issue (https://github.com/getodk/collect/issues/4779) in 90% is about something completly else.
Maybe you both discussed it when I was off but still I feel like it should be divided into two prs and the one about using App Startup discussed.

as @lognaturel said:

> Unfortunately, I'm having some trouble convincing myself that using the app startup library is a win. The approach here seems ok but it is adding another dependency and another layer so I do want to make sure the benefits have been considered.

I also have concerns about it. Nice implementation but much more complex for understanding for someone who hears of that library for the first time. 
Apart from the structure (whether is better or not) does it bring any improvement regarding performance in our case?

2021-10-15 12:34 UTC, grzesiek2010 commented on collect_app/src/main/AndroidManifest.xml
> +        <!-- disable WorkManager initializer and let startup take care of that -->
Shouldn't we add this to as a meta like in: https://developer.android.com/topic/libraries/app-startup#disable-individual?
something like:
```
<meta-data android:name="androidx.work.impl.WorkManagerInitializer"
              tools:node="remove" />
```

2021-10-15 12:34 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/application/initialization/AnalyticsInitializer.kt
> +        analytics: Analytics,
Would it be possible to have default values here that take it's implementations from DaggerUtils.getComponent? so that we don't have both injects and this constructor but only the constructor? Something like in StoragePathProvider where we have:

```
class StoragePathProvider @JvmOverloads constructor(
    private val currentProjectProvider: CurrentProjectProvider = DaggerUtils.getComponent(Collect.getInstance())
        .currentProjectProvider(),
    val odkRootDirPath: String = Collect.getInstance().getExternalFilesDir(null)!!.absolutePath
) {
```

2021-10-15 13:06 UTC, seadowg commented
I feel like the response to using App Startup is pretty negative here so going to just pull that out, and we can discuss it separately.

2021-10-15 13:58 UTC, lognaturel approved these changes
Thank you and sorry!

2021-10-15 14:07 UTC, lognaturel commented
Really the rejection of App Startup can be seen as a compliment. What y’all have come up with doesn’t seem that messy to me (maybe I’m missing messiness) and the thing I like most about it is that it’s explicit and straightforward. Will be interesting to discuss briefly.

2021-10-15 14:40 UTC, grzesiek2010 approved these changes

2021-10-15 15:45 UTC, merged

2021-10-15 15:47 UTC, seadowg commented
I've added `UsingLegacyFormUpdate` as a custom dimension in Firebase.