v2021.3 analytics
getodk/collect pull request #4861
Opened 2021-10-14 14:11 UTC by seadowg

Closes #4847

Definitely best to go through this commit by commit as removing a constructor param changed a bunch of test files.

#### What has been done to verify that this works as intended?

Ran tests to check nothing had broken. No tests for analytics.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Shouldn't have any effect on behaviour. Can skip QA.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2021-10-18 14:04 UTC, seadowg commented on analytics/src/main/java/org/odk/collect/analytics/Analytics.kt
> +        fun setParam(key: String, value: String) {
I'm basically emulating `Timber` with the style of this static interface. Why is it ok for this state to be static? In my mind, these kinds of "ancillary" features like logging and analytics can use static references and state for the following reasons:

1. They are never essential to the parts of the code that call them
2. Given the above reason, interactions with them should never need to be tested
3. No app behaviour is in any way reliant on the static state being held
4. We're only storing a reference to data (a `String`) rather than a reference to a shared component (like `FormController` or a UI component)

And also, storing the form hash statically like this will allow us to stop passing analytics specific information down to components which hopefully reduces the noise added by analytics.

2021-10-18 14:05 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/formentry/questions/QuestionDetails.java
> -    public String getFormAnalyticsID() {
No longer need this as the form hash will be stored statically.

2021-10-18 16:46 UTC, lognaturel approved these changes
I like this.

2021-10-19 10:09 UTC, merged

2021-10-19 10:11 UTC, grzesiek2010 requested changes

2021-10-19 10:11 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoWidgetUtils.java
> +    public static void logAllowMockAccuracy(FormEntryPrompt prompt) {
Wouldn't it be easier to log this event in `ActivityGeoDataRequester`? This is the only place where you check if the option is enabled and then it would be in one place instead of in every geo widget.

2021-10-19 10:13 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoWidgetUtils.java
> +    public static void logAllowMockAccuracy(FormEntryPrompt prompt) {
Yeah I thought about that. So in that case the even would only fire if the button is tapped, so we might not see it for optional questions? It's not a big deal but felt like having it fire when the widget is displayed made more sense.