Test register for context menu
getodk/collect pull request #4877
Opened 2021-10-21 17:49 UTC by grzesiek2010

#### What has been done to verify that this works as intended?
I just reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
This is what we discussed in https://github.com/getodk/collect/pulls?q=is%3Apr+is%3Aclosed

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2021-10-25 10:26 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
> +        if (context instanceof Activity && !questionDetails.isReadOnly()) {
Good change. Anything we can do to severe the dependency from Widgets on `FormEntryActivity` is a step forward!

2021-10-25 10:35 UTC, seadowg requested changes
Looks great! Just a couple of wee tweaks and one thing to discuss before moving on.

2021-10-25 10:35 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/support/TestScreenContextActivity.kt
> +class TestScreenContextActivity : FragmentActivity(), ScreenContext {
We can probably just call this `WidgetTestActivity` now it has a couple of different features for testing widgets with.

2021-10-25 10:35 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/support/TestScreenContextActivity.kt
> +    val viewsRegisterForContextMenu: MutableList<View> = ArrayList()
It's the same thing, but you could just use `mutableListO<View>()` here.

2021-10-25 10:35 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
> +                childView.setTag(childView.getId());
Do you think we should really be using the tag instead of ID as a way to propagate the widget ID? Overriding the ID feels pretty dodgy. It feels like a warning sign that you had to add the original ID to the tag here.

Maybe that's not a change we want to make in this PR as it would need a lot of QA or more testing, but I think it'd be good to discuss quickly here.

2021-10-27 12:32 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
> +                childView.setTag(childView.getId());
Our:
```
    @Override
    public boolean onContextItemSelected(MenuItem item) {
        if (item.getItemId() == DELETE_REPEAT) {
            DialogUtils.showIfNotShowing(DeleteRepeatDialogFragment.class, getSupportFragmentManager());
        } else {
            ODKView odkView = getCurrentViewIfODKView();
            if (odkView != null) {
                for (QuestionWidget qw : odkView.getWidgets()) {
                    if (item.getItemId() == qw.getId()) {
                        createClearDialog(qw);
                        break;
                    }
                }
            }
        }

        return super.onContextItemSelected(item);
    }
```

is based on ids but I agree that changing them (like we do now) is error prone. We could swap it, set tags for every view we register for context menu and use tags in `onContextItemSelected()`. Is that what you meant?

2021-10-27 12:33 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/support/TestScreenContextActivity.kt
> +class TestScreenContextActivity : FragmentActivity(), ScreenContext {
Done.

2021-10-27 12:33 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/support/TestScreenContextActivity.kt
> +    val viewsRegisterForContextMenu: MutableList<View> = ArrayList()
Done.

2021-10-27 12:44 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
> +                childView.setTag(childView.getId());
Yeah exactly: use the tags as the identifier rather than view ID. Unless you disagree I think that's something we should do another time though? Just good to chat about it so that we've got it in mind for next time we touch that area.

2021-10-27 12:46 UTC, seadowg approved these changes

2021-10-28 09:56 UTC, seadowg commented
Whoops. Must have been on autopilot when I added "needs testing" to this. Sorry if you already looked at it @kkrawczyk123 @mmarciniak90.

2021-10-28 09:56 UTC, merged