Fixed starting activities
getodk/collect pull request #4878
Opened 2021-10-26 08:09 UTC by grzesiek2010

Closes #4876 

#### What has been done to verify that this works as intended?
I have tested staring some external apps.

#### Why is this the best possible solution? Were any other approaches considered?
I had to reimplement the way we check if an activity we want to star is available. Before we used our [ActivityAvailability](https://github.com/getodk/collect/pull/4878/files#diff-214f3bcddf9d06f60193bd716bc979fa1fe2e92c273b8c7ea36da9684934dd42L8) which used `queryIntentActivities()`. According to https://developer.android.com/about/versions/11/privacy/package-visibility?authuser=2 that method will return an empty array on android 11 if we don't declare <queries> in our AndroidManifest.xml like https://stackoverflow.com/a/63246789

We could do that but that would open a lot of room for error since we can easily forget something so we agreed that a better option would be to get rid of it and just try to start activities and catch exceptions that are thrown if they are not available.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test:
- taking pictures
- recording videos
- recording audio
- attaching arbitrary files
- opening media files in Collect (recorded using our widgets but also media files attached to questions)
- starting external widgets
- choosing files (fore example qr codes for configuring the app)

plus please test the behavior when an external app is not available (there should be a toast in most cases).

It's difficult to list everything so basically everything that is related to staring external apps might be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2021-10-27 12:42 UTC, seadowg requested changes
This is looking really good! I still need to go through the new widget intent launchers, but I've got a few tweaks that we could make that I'll just share now so that I'm not holding you up!

2021-10-27 12:42 UTC, seadowg commented on androidshared/build.gradle
> +    implementation Dependencies.dagger
Not sure that I understand why we're adding Dagger `androidshared`. I'm guessing you added for something you ended up not needing?

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/main/java/org/odk/collect/androidshared/utils/IntentLauncherImpl.kt
> +object IntentLauncherImpl : IntentLauncher {
Huh. I'd never thought about this pattern of having an `object` implement an interface for stateless implementations. As far as I can see it's a nice idea! Really useful for pulling out related helper functions as an interface that don't need really need a class. I guess we'd need to be careful about not adding any state to an implementation like this (as that would be static).

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +@RunWith(AndroidJUnit4::class)
It looks like you won't need this as the all the Android objects are being mocked.

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    lateinit var context: Context
You can call `mock` at test construction you can actually just have `val` for all these fields with inline assignments, and then you don't need `setup` at all.

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `onError should not be called if no exception occurs when calling IntentLauncher#launch(context, intent, onError)`() {
The assertions in this test double up the one above. I think you can either keep both and remove `verifyNoMoreInteractions(onError)` in the first test or just have the one test for the "positive" case (I think I prefer the former at a "unit" level like this).

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `onError should not be called if no exception occurs when calling IntentLauncher#launchForResult(context, intent, requestCode, onError)`() {
Same doubling up here as far as I can see!

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `startActivity with given intent should be called on the context when calling IntentLauncher#launchForResult(resultLauncher, intent, onError)`() {
Description is a little off here. Should probably mention activity result launcher instead of `startActivity`

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `startActivity with given intent should be called on the context when calling IntentLauncher#launchForResult(context, intent, requestCode, onError)`() {
"`startActivityForResult` with given..."

2021-10-27 12:42 UTC, seadowg commented on androidshared/src/main/java/org/odk/collect/androidshared/utils/IntentLauncherImpl.kt
> +package org.odk.collect.androidshared.utils
This could go in the `system` package I reckon? Also, I think the file should just be named after the interface in these cases where you have a default implementation as well.

2021-10-27 12:42 UTC, seadowg commented on testshared/src/main/java/org/odk/collect/testshared/FakeIntentLauncher.kt
> +class DummyIntentLauncher : IntentLauncher {
Looks like this isn't being used?

2021-10-27 13:12 UTC, seadowg requested changes
I think we can maybe revise the naming for the external widget intent launchers to follow the existing external data interfaces we have like `GeoDataRequester`. For instance `ExFileWidgetIntentLauncher` could be `FileRequester`. 

I also think we could simplify the interfaces a little for these by giving the implementations constructors (and making them `class` not `object`). Right now we have to pass dependencies like `IntentLauncher` into the widgets (increasing reliance on the class hierarchy here) whereas really they could be detached through these interfaces. For example, `ExStringWidgetIntentLauncher#launch` could just take a `FormEntryPrompt` and the `onError` callback (and I think the request code) while the other dependencies could be passed in at construction in `WidgetFactory`. 

Thoughts?

2021-10-27 17:55 UTC, grzesiek2010 commented on androidshared/build.gradle
> +    implementation Dependencies.dagger
Fixed.

2021-10-27 17:55 UTC, grzesiek2010 commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    lateinit var context: Context
Fixed.

2021-10-27 17:56 UTC, grzesiek2010 commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +@RunWith(AndroidJUnit4::class)
Fixed.

2021-10-27 17:56 UTC, grzesiek2010 commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `onError should not be called if no exception occurs when calling IntentLauncher#launch(context, intent, onError)`() {
Fixed.

2021-10-27 17:56 UTC, grzesiek2010 commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `onError should not be called if no exception occurs when calling IntentLauncher#launchForResult(context, intent, requestCode, onError)`() {
Fixed.

2021-10-27 17:56 UTC, grzesiek2010 commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `startActivity with given intent should be called on the context when calling IntentLauncher#launchForResult(resultLauncher, intent, onError)`() {
Fixed.

2021-10-27 17:56 UTC, grzesiek2010 commented on androidshared/src/test/java/org/odk/collect/androidshared/utils/IntentLauncherImplTest.kt
> +    fun `startActivity with given intent should be called on the context when calling IntentLauncher#launchForResult(context, intent, requestCode, onError)`() {
Fixed.

2021-10-27 17:56 UTC, grzesiek2010 commented on androidshared/src/main/java/org/odk/collect/androidshared/utils/IntentLauncherImpl.kt
> +package org.odk.collect.androidshared.utils
Fixed.

2021-10-27 17:56 UTC, grzesiek2010 commented on testshared/src/main/java/org/odk/collect/testshared/FakeIntentLauncher.kt
> +class DummyIntentLauncher : IntentLauncher {
Fixed.

2021-10-27 17:57 UTC, grzesiek2010 commented
> I think we can maybe revise the naming for the external widget intent launchers to follow the existing external data interfaces we have like GeoDataRequester. For instance ExFileWidgetIntentLauncher could be FileRequester.

> I also think we could simplify the interfaces a little for these by giving the implementations constructors (and making them class not object). Right now we have to pass dependencies like IntentLauncher into the widgets (increasing reliance on the class hierarchy here) whereas really they could be detached through these interfaces. For example, ExStringWidgetIntentLauncher#launch could just take a FormEntryPrompt and the onError callback (and I think the request code) while the other dependencies could be passed in at construction in WidgetFactory.

I agree with that and it's now implemented.

2021-10-28 09:54 UTC, seadowg approved these changes
One tweak but this is great!

2021-10-28 09:54 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
> +    IntentLauncher intentLauncher;
Don't think this is being used anywhere - can just be deleted. As far as I can see, we're passing an `IntentLauncher` in at the constructor everywhere we need it.

2021-10-29 07:53 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
> +    IntentLauncher intentLauncher;
Right, fixed.

2021-11-02 10:47 UTC, mmarciniak90 commented
@grzesiek2010, I checked external widgets on a separate page without CollectAnswerProvider installed and I see unexpected message in toast.

Form to test: [external_widgets](https://test.getodk.cloud/#/projects/270/forms/external_widgets) or `All widgets`

|incorrect toast|expected toast|
|---|---|
|![Screenshot_20211102-113758_ODK Collect](https://user-images.githubusercontent.com/3907554/139832088-a0dc4210-fbe6-41ee-8e72-b8632f137ff1.jpg)|![Screenshot_20211102-113835_ODK Collect](https://user-images.githubusercontent.com/3907554/139832142-5cfc9b09-5089-4be0-8080-2358e9e67600.jpg)|

2021-11-02 13:56 UTC, grzesiek2010 commented
@mmarciniak90 The problem should be solved now.

2021-11-03 11:24 UTC, kkrawczyk123 commented
**Tested with success!**
Verified on Androids: 5.1, 9.0 and 11

Tested cases:
- video widget: attach, record, play
- image widget: attach, take a picture
- selfie widgets
- audio widget
- draw widget
- signature widget
- annotate widget
- barcode widget
- file widget
- URL widget 
- use external widgets with app 
- toasts when there is no external app have been fixed
- numerical widget with video attachment
- play audio and video attachments in form 
- Collect counter app
- Collect Tester app
- edited project via imported QR code file
- added new project via imported QR code file

2021-11-03 11:47 UTC, mmarciniak90 commented
Tested with success on Android versions: 8.1, 10.0

2021-11-03 11:48 UTC, merged