Make json schema identifiers more specific
getodk/collect pull request #5076
Opened 2022-03-28 21:20 UTC by lognaturel

I talked to @grzesiek2010 and @seadowg briefly about this and figured I'd make the change instead of filing an issue. Happy to entertain alternatives, though. The `title` is intended to stand more on its own. The idea with changing the URI is to have a story in case we have other kinds of settings we want to specify. None of this has been released yet so the change should have no impact.

2022-03-29 15:18 UTC, seadowg requested changes

2022-03-29 15:18 UTC, seadowg commented on settings/src/main/resources/settings_schema.json
> +  "$id": "https://getodk.com/client-settings.schema.json",
Can we set up a forward or DNS for this so that it resolves to the file? I think changing the name of the file itself would be good as well.

2022-04-05 16:45 UTC, lognaturel commented on settings/src/main/resources/settings_schema.json
> +  "$id": "https://getodk.com/client-settings.schema.json",
Yes

2022-04-05 17:36 UTC, lognaturel commented
@seadowg Resources that are going to be accessed through `R.` need to have filenames that are valid Java identifiers. I can't see any reason for a restriction on this filename.

2022-04-06 08:31 UTC, seadowg commented
> Resources that are going to be accessed through R. need to have filenames that are valid Java identifiers. I can't see any reason for a restriction on this filename. I have tried this on a real device as well.

Ah I think the file originally lived in `res` so would have been subject to those restrictions. Definitely nicer to have the name it has.

2022-04-06 08:31 UTC, seadowg approved these changes

2022-04-06 08:32 UTC, merged