Refactors Preference Activities
getodk/collect pull request #510
Opened 2017-03-05 23:41 UTC by shobhitagarwal1612

- Adds PreferenceFragments for each PreferenceActivity to reduce deprecated methods
- Adds ToastUtils in utilities 
- Deletes AppPreferenceActivity

2017-03-06 00:39 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +/**
I can’t speak for the project, but I find these noisy and wish Studio wouldn’t put them in by default. Git tells us what we need to know.

2017-03-06 00:42 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +        Toast.makeText(Collect.getInstance(),message, Toast.LENGTH_SHORT).show();
Space after comma. A better name might be makeShortText. Perhaps there should a third, private method that factors out the common code.

2017-03-06 00:43 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/preferences/AggregatePreferencesFragment.java
> +                    ToastUtils.shortDuration(String.valueOf(R.string.url_error));
An overloaded ToastUtils.makeShort/LongText method that takes the “R” value would save a lot of “String.valueOf”s in the callers.

2017-03-06 00:58 UTC, dcbriccetti commented on collect_app/src/main/res/xml/other_preferences.xml
>  </PreferenceScreen>
I would add the newline here at the end of the file if for no other reason than to remove the warning.

2017-03-06 01:02 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +        Toast.makeText(Collect.getInstance(),message, Toast.LENGTH_SHORT).show();
Agreed

2017-03-06 01:04 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +/**
It’s not visible here, but I’m referring to the “Created by x” excretions.

2017-03-06 01:10 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +        Toast.makeText(Collect.getInstance(),message, Toast.LENGTH_SHORT).show();
Correction: showShortText might be better. I missed the show() at the end. What do you think?

2017-03-06 01:17 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +        Toast.makeText(Collect.getInstance(),message, Toast.LENGTH_SHORT).show();
What if we use showShortToast?

2017-03-06 01:30 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +        Toast.makeText(Collect.getInstance(),message, Toast.LENGTH_SHORT).show();
OK with me. It’s sort of implied by the “ToastUtils.” but it would add clarity for someone who statically imported the methods.

2017-03-06 16:56 UTC, lognaturel commented
@dcbriccetti @shobhitagarwal1612 Let me know when this is ready for my review, please!

2017-03-06 18:01 UTC, shobhitagarwal1612 commented
@lognaturel Please review the changes

2017-03-06 18:37 UTC, nribeka commented on collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
> +            AlertDialog.Builder b = new AlertDialog.Builder(getActivity());
I'm not a fan of one char variable. But it could be just a preference for some.

2017-03-06 18:41 UTC, nribeka commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
> +    private static final String t = "PreferencesActivity";
Use TAG and you can use the simple class name instead of hard coding the String.

`PreferencesActivity .class.getSimpleName()`

2017-03-06 18:42 UTC, nribeka commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesFragment.java
> +    private static final String t = "PreferencesActivity";
I would do the same here with TAG and simple name.

2017-03-06 18:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
> +    private static final String t = "PreferencesActivity";
We can't do that because of proguard.

2017-03-06 18:44 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
> +            AlertDialog.Builder b = new AlertDialog.Builder(getActivity());
I agree with @nribeka on this. Especially when it’s in scope for so long.

2017-03-06 18:44 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
> +    private static final String t = "PreferencesActivity";
https://medium.com/@elye.project/the-danger-of-using-class-getsimplename-as-tag-for-fragment-5cdf3a35bfe2#.yiz5an5eb

But I do agree that the constant name should be TAG. The codebase is inconsistent so we can just change this when we do a style check across all classes.

2017-03-06 18:45 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
> +            AlertDialog.Builder b = new AlertDialog.Builder(getActivity());
Agreed.

2017-03-06 18:46 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +    private static final int LENGTH_SHORT = Toast.LENGTH_SHORT;
No need for these. “void toaster(...)” can use the Toast ones.

2017-03-06 18:48 UTC, nribeka commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
> +    private static final String t = "PreferencesActivity";
Ah the dang proguard. I guess I need to change my code then.

2017-03-06 18:49 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +    private static final int LENGTH_SHORT = Toast.LENGTH_SHORT;
:+1:

2017-03-06 18:50 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +    private static final int LENGTH_SHORT = Toast.LENGTH_SHORT;
Should I use `Toast` instead of `toaster`?

2017-03-06 18:51 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +    private static void toaster(int messageResource, int duration) {
Method names should be a verb or verb phrase.

2017-03-06 18:53 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
> +            AlertDialog.Builder b = new AlertDialog.Builder(getActivity());
Yes, good point by @dcbriccetti. We should be picky style-wise about new code but it's ok to leave old things alone to minimize invasive changes.

2017-03-06 18:55 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +    private static void toaster(int messageResource, int duration) {
showToast would be a good name.

2017-03-06 18:56 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
> +    private static final String t = "PreferencesActivity";
@lognaturel @nribeka So we can safely use `class.getSimpleName()` for the `PreferenceActivity`?

2017-03-06 18:57 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesFragment.java
> +    private static final String t = "PreferencesActivity";
:+1:

2017-03-06 19:00 UTC, shobhitagarwal1612 commented on collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
> +            AlertDialog.Builder b = new AlertDialog.Builder(getActivity());
@dcbriccetti The name of this builder variable was not changed by me. But I will change that to `builder`

2017-03-06 19:03 UTC, dcbriccetti commented on collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
> +            AlertDialog.Builder b = new AlertDialog.Builder(getActivity());
No, I think a small consensus formed that we wouldn’t change it.

2017-03-06 19:04 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
> +    private static final String t = "PreferencesActivity";
Unfortunately, no.

2017-03-06 19:04 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesFragment.java
> +    private static final String t = "PreferencesActivity";
Ah, I see. Sorry, I didn't respond to this one. Doesn't work here either.

2017-03-06 19:07 UTC, nribeka commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
> +    private static final String t = "PreferencesActivity";
Yeah, proguard will obfuscate this class name and then the log will ended up with "A", or "B", or "C" instead of "PreferenceActivity".

2017-03-07 02:58 UTC, lognaturel requested changes
In the future, please do try to keep your pull requests as focused as possible. In this case, you should only have been touching preference-related classes and in fact it might have been better to do separate PRs for admin and general settings. When a PR includes unrelated changes across many files, errors are more likely to sneak in!

2017-03-07 02:58 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesFragment.java
> +import static org.odk.collect.android.preferences.PreferenceKeys.ARRAY_INDEX_GOOGLE_MAPS;
In the case of static constant imports like these, I think it's better to do a single wildcard import.

2017-03-07 02:58 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
> +    private static final int LENGTH_SHORT = Toast.LENGTH_SHORT;
Please remove these constants. You should just refer directly to `Toast.LENGTH_xx`. There is no value to saving their values locally.

2017-03-07 05:04 UTC, shobhitagarwal1612 commented
@lognaturel I am sorry for the inconvenience caused. Will strictly follow to keep PRs ' focused' from now on. I have done all the requested changes.

2017-03-07 15:03 UTC, lognaturel approved these changes

2017-03-07 15:04 UTC, merged