Fixed clearing features
getodk/collect pull request #5128
Opened 2022-04-28 19:06 UTC by grzesiek2010

Closes #5127 

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2022-04-28 19:54 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
> -        map.getOverlays().clear();
I don't know why it was implemented in this way... clearing everything not just features like it is in google and mapbox and like I implemented it now.

2022-04-28 19:54 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
> -    public void onDestroy() {
I had to remove that because it caused NPEs in OSM I don;t think it's needed, at least I'm not seeing any leaks.

2022-05-04 10:47 UTC, seadowg requested changes

2022-05-04 10:47 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
> +        if (map != null) {  // during Robolectric tests, map will be null
Do we need this check here? We don't have any Robolectric tests for this class as far as I'm aware.

2022-05-04 15:15 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
> +        if (map != null) {  // during Robolectric tests, map will be null
Yes if we have tests that require checks like that it's probably only for Google maps so here it's not needed. Fixed.

2022-05-04 15:15 UTC, seadowg approved these changes

2022-05-06 12:34 UTC, kkrawczyk123 commented
I have noticed a delay with showing/deleting single points from geopoint widget with map appearance when adding point by placement on map and when delete point using delete button. I was comparing with store version and I can see delays like 2-6s on both my devices. @grzesiek2010 Could you please take a look?

2022-05-06 12:50 UTC, grzesiek2010 commented
> Could you please take a look?

ok I'm on it.

2022-05-06 13:26 UTC, grzesiek2010 commented
Ok the problem has been fixed. Please continue testing.

2022-05-06 14:02 UTC, srujner commented
**Tested with Success!**
Verified on android 10 and 11

Verified Cases:
- #5127 is no longer reproducing;
- Regression checks on Geowidgets using OSM layer;
- Offline layers;
- Adding/Removing single points;
- Zero leaks at Canary Leaks app;
- screen rotation, minimize app, using backward button

2022-05-09 08:10 UTC, kkrawczyk123 commented
Verified also on Androids 5.1 and 8.1

2022-05-09 08:38 UTC, merged