Protect the app from importing keys and values that are not supported according to the json scheme
getodk/collect pull request #5154
Opened 2022-05-31 14:00 UTC by grzesiek2010

Closes #5096 
Closes #4939 
Closes #5176

#### What has been done to verify that this works as intended?
I've tested the app manually and improved automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
I've extended `JsonSchemaSettingsValidator` and added methods to verify if existing keys/values are supported.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please verify the case form the issue https://github.com/getodk/collect/issues/5096

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2022-06-28 14:34 UTC, seadowg commented
@grzesiek2010 is this meant to close https://github.com/getodk/collect/issues/4939?

2022-06-28 14:59 UTC, grzesiek2010 commented
> @grzesiek2010 is this meant to close https://github.com/getodk/collect/issues/4939?

Yes, I've just fixed the description.

2022-06-29 10:33 UTC, seadowg requested changes

2022-06-29 10:33 UTC, seadowg commented on settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
> +                    IOUtils.toString(schemaStream, Charset.defaultCharset())
Kotlin has [extensions for `InputStream`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-input-stream/) that let you avoid depending on Commons here. In general, we should be able to replace all the Guava and Commons calls with Kotlin standard library.

2022-06-29 10:33 UTC, seadowg commented on settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
> +            schemaProvider().use { schemaStream ->
We're now reading the `schemaProvider` `InputStream` in a whole bunch of times, so I think it makes sense to cache it. To my mind, the simplest thing to do is to have a `lazy` property for the schema as a `String` and another as a `JSONObject` (that relies on the first).

2022-06-29 10:33 UTC, seadowg commented on settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
> +                    for (i in 0 until supportedValues.length()) {
This could use `supportedValues.contains` instead I think?

2022-06-29 10:33 UTC, seadowg commented on settings/src/test/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidatorTest.kt
> +    fun `isValidreturns false when json is invalid based on schema`() {
Missing a space here.

2022-06-30 14:58 UTC, grzesiek2010 commented on settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
> +                    for (i in 0 until supportedValues.length()) {
`JSONArray` does not provide such a method.

2022-06-30 15:25 UTC, grzesiek2010 commented on settings/src/test/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidatorTest.kt
> +    fun `isValidreturns false when json is invalid based on schema`() {
Fixed.

2022-06-30 15:25 UTC, grzesiek2010 commented on settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
> +                    IOUtils.toString(schemaStream, Charset.defaultCharset())
Done.

2022-06-30 15:25 UTC, grzesiek2010 commented on settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
> +            schemaProvider().use { schemaStream ->
Done.

2022-07-01 08:35 UTC, seadowg commented on settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
> +                    for (i in 0 until supportedValues.length()) {
Ach, sorry. Of course.

2022-07-01 11:47 UTC, seadowg approved these changes

2022-07-01 11:47 UTC, seadowg commented on settings/build.gradle
> +    implementation Dependencies.commons_io
Shouldn't need this any longer

2022-07-04 15:30 UTC, grzesiek2010 commented on settings/build.gradle
> +    implementation Dependencies.commons_io
Right, done.

2022-07-07 13:15 UTC, dbemke commented
**Tested with Success!**

Verified on Android 8.1, 11

**Verified cases:**

- importing QR code from a file, Google Drive and Central
- exporting QR code via Google Drive and email
- scanning QR code in horizontal and vertical way
- resetting all settings
- reconfiguring settings with QR code
- reconfiguring settings with big sized image
- reconfiguring settings with QR code containing sensitive information- admin and server password on Aggregate and ODK
- scanning valid, invalid QR code and inverted QR code
- updating settings from older versions
- adding duplicate project
- switching to existing project

2022-07-07 13:20 UTC, srujner commented
**Tested with Success!**

Verified on Android 10 and 12

Today I found one strange issue related to Android 5.1 only: #5178

2022-07-07 14:12 UTC, grzesiek2010 commented
@seadowg there are new changes (for https://github.com/getodk/collect/issues/5176) here so you might want to take a look.

In the issue @lognaturel asked if https://github.com/getodk/collect/issues/5176 is a fix for [this Crashlytics report](https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8d842445557fcf3942b4e99ba2f89aec?time=last-ninety-days&types=crash&sessionEventKey=62C64C2A033400015E5E410BADE4B60A_1695905622417877922). I said that the issue was probably responsible for just a part of the reports.
Now I'm thinking more about those crashes and I think that it might be caused by similar problems with QR codes that we are not able to detect and our scheme validator also does not deal with.

I wanted to propose one additional improvements which is wrapping [this](https://github.com/getodk/collect/blob/master/settings/src/main/java/org/odk/collect/settings/ODKAppSettingsImporter.kt#L31) into `try-catch` and catch anything there. My thinking is that the mentioned method consists of many steps that could potentialy fail (for example creating `JSONObjects`). 
If that method somehow throws an exception we end up with that problem with no project id. So although we do not now for sure what might throw such exceptions it seeps to be possible.

What do you think @seadowg @lognaturel?

2022-07-08 09:16 UTC, seadowg commented
> I wanted to propose one additional improvements which is wrapping [this](https://github.com/getodk/collect/blob/master/settings/src/main/java/org/odk/collect/settings/ODKAppSettingsImporter.kt#L31) into try-catch and catch anything there. My thinking is that the mentioned method consists of many steps that could potentialy fail (for example creating JSONObjects).
If that method somehow throws an exception we end up with that problem with no project id. So although we do not know for sure what might throw such exceptions it seeps to be possible.

This probably makes sense. I think we'd also want to clear the new shared preferences bucket in the `catch` as well. A potentially nicer alternative would be to wrap `ProjectCreator#createNewProject`'s implementation in a "catch all" `try-catch`. Then we could remove the `try-catch` at `QrCodeProjectCreatorDialog#createProjectOrError` and just show an error when `createNewProject` returns `false` (which simplifies our UI code).

2022-07-08 10:24 UTC, grzesiek2010 commented
> A potentially nicer alternative would be to wrap ProjectCreator#createNewProject's implementation in a "catch all" try-catch (and perform project repo/shared prefs clean up in the catch). Then we could remove the try-catch at QrCodeProjectCreatorDialog#createProjectOrError and just show an error when createNewProject returns false (which simplifies our UI code).

I already removed `try-catch` from `QrCodeProjectCreatorDialog#createProjectOrError` in this pr.
I think we should rather use `try-catch` in `ODKAppSettingsImporter#fromJSON` because this methods is the only place where `SettingsImporter.fromJSON` (the risky one) is called but `ODKAppSettingsImporter#fromJSON` itself is called from different places so i think it should catch exceptions and return false.

Then in `ProjectCreator#createNewProject` we can delete project / clear prefs if the returned value is false.

What do you think?

2022-07-08 10:32 UTC, seadowg commented
@grzesiek2010 ah sorry I just realized I was looking at the current `master`. Yeah that sounds good!

2022-07-08 12:51 UTC, grzesiek2010 commented
@seadowg new changes have been added. Please review.

2022-07-12 12:17 UTC, seadowg approved these changes

2022-07-12 12:50 UTC, merged