Fix checking supported abis
getodk/collect pull request #5194
Opened 2022-07-20 07:24 UTC by grzesiek2010

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2022-07-20 11:40 UTC, seadowg requested changes
Just one wee tweak!

It's fascinating that the virtual device returns x86 and arm arches - hard to imagine a device that would do that out in the wild.

I'm also wondering if we should just attempt to load the library ourselves and catch the exception instead of trying to inspect the supported architectures here. How would you feel about that?

2022-07-20 11:40 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/application/MapboxClassInstanceCreator.kt
> +        return createMapboxMapFragment() != null && mapboxAbis.contains(Build.SUPPORTED_ABIS.first())
This feels very unlikely, but can we protect from `SUPPORTED_ABIS` being empty here? I guess adding `!Build.SUPPORTED_ABIS.isEmpty()` as part of the `&&` expression would do.

2022-07-20 14:02 UTC, grzesiek2010 commented
> I'm also wondering if we should just attempt to load the library ourselves and catch the exception instead of trying to inspect the supported architectures here. How would you feel about that?

I don't have any strong feelings. Maybe... I've just added a fix with that approach so please take a a look if you like it I'm ok with it too.

2022-07-20 17:55 UTC, seadowg commented
> I don't have any strong feelings. Maybe... 

Same. Both approaches don't feel quite right, but I think I like using `System.loadLibrary` more. It's pretty consistent with how we detect if Mapbox is on the class path as well - seeing if something breaks.

2022-07-20 17:55 UTC, seadowg approved these changes

2022-07-24 15:20 UTC, seadowg commented
Marked this as `high priority` as other regression fixes rely on it

2022-07-24 15:21 UTC, seadowg commented
Marked this as `high priority` as other regression fixes rely on it

2022-07-25 10:06 UTC, srujner commented
**Tested with Success!**
Verified on Android 5.1, 10, 12

**Verified Cases:**
- Opening Mapbox on each device;
- Quick regression check on GeoWidgets;

2022-07-25 10:43 UTC, dbemke commented
Tested with Success!
Verified on Android 8.1, 11

2022-07-25 10:50 UTC, merged