Redesign map buttons
getodk/collect pull request #5199
Opened 2022-07-21 12:25 UTC by seadowg

- Switch to Material3 button for selection summary sheet
- Bump margin between button and title
- Add note about Material 3 to STATE.md
- Fix test reference
- Change map buttons in selection map to MMaterial 3 FAB
- Rework geopoint map layout with Material 3 buttons
- Use surface color for location info section
- Format geopoly layout
- Convert geopoly map buttons to Material 3 FAB
- Convert geopoly layout to ConstraintLayout
- Move primary actions to bottom of screen
- Remove map button custom style
- Make sure there is only one primary FAB on map views
- Add content description to FABs

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2022-07-21 17:47 UTC, lognaturel commented
The button changes look good to me. It's hard for me to judge how disruptive the changes to order will be so as you suggested, let's merge early in the next release cycle and get feedback. I think a good outcome is that save is always at the bottom near the thumb.

Since we're not pushing to get this into the current release, how about also updating the look of the "Record a Point" button in geotrace/shape manual selection? Also fine if you'd rather file a separate issue, maybe there's more thinking to do there.

Not sure whether it's related to these changes but placement by tapping doesn't work with osmdroid at all. Not in `placement-map`, not in geotrace/shape. Haven't tried other engines.

Again, not sure it's related but the `placement-map` appearance has accuracy at the top with a while background whereas trace and shape use the primary color. I prefer the white background.

2022-07-21 18:08 UTC, lognaturel commented
One change this makes is not allowing vertical scroll on buttons to accommodate short screens.

I think that's ok. We know there are folks using small devices but my guess is that the would be less likely to do map-related work: it's just not practical to view maps without a little bit of context. This is something we can ask about when we do our first beta for the next release.

2022-09-07 15:45 UTC, grzesiek2010 requested changes

2022-09-07 15:45 UTC, grzesiek2010 commented on geo/src/main/res/layout/selection_map_layout.xml
> -        <org.odk.collect.androidshared.ui.multiclicksafe.MultiClickSafeImageButton
Here we used `MultiClickSafeImageButton` probably becasue it was possible to open form filling twice? I think we should protect users from doing that.

2022-09-07 15:46 UTC, grzesiek2010 commented
In landscape mode or probably in case of small screens it doesn't look good:
![Screenshot_1662565554](https://user-images.githubusercontent.com/3276264/188921946-0defc36e-f995-41c9-9a17-c38d98804dd5.png)

2022-09-12 10:41 UTC, seadowg commented
> In landscape mode or probably in case of small screens it doesn't look good:

Good catch. I played around with smaller screens a lot, but not landscape. Interestingly, Google Maps seems to show/hide FABs selectively in different UIs (map vs location etc) in landscape. I'll have a play with doing something like that.

2022-09-12 11:13 UTC, seadowg commented
@lognaturel @grzesiek2010 I've added a layout specifically for landscape for geoshape/geotrace that puts the larger FABs in a horizontal row rather than a vertical column. Let me know what you think - I can do the same thing for the other map views if we feel like this works well.

2022-09-12 13:06 UTC, grzesiek2010 commented
> I've added a layout specifically for landscape for geoshape/geotrace that puts the larger FABs in a horizontal row rather than a vertical column. Let me know what you think - I can do the same thing for the other map views if we feel like this works well.

It looks good to me.

2022-09-12 13:18 UTC, grzesiek2010 commented on geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
> +            binding.newItem.setMultiClickSafeOnClickListener {
I would also fix `binding.layerMenu` above. There it's probably also possible to open multiple dialogs?

2022-09-12 19:14 UTC, grzesiek2010 approved these changes

2022-09-14 08:34 UTC, dbemke commented
I’ve noticed that a disabled button is barely visible if the dark mode is applied when the map in the background is grey or light green or if the light mode is applied on e.g. Control room offline layer which is dark. 
![darkmodebindisabled2](https://user-images.githubusercontent.com/56479916/190103960-2fe15cf6-4659-4d53-a291-18abd827bc1d.jpg)
![darkmodegreenbackground2](https://user-images.githubusercontent.com/56479916/190103963-e617b3c9-a68c-4497-aa57-a29ae70bd5e5.jpg)
![lightmodebindisabled2](https://user-images.githubusercontent.com/56479916/190103966-b196d3cc-19d4-4c09-8b5e-bf8e6240f204.jpg)

2022-09-14 12:56 UTC, dbemke commented
Record a point button has the previous design (different style than other map buttons).
![recordpoint](https://user-images.githubusercontent.com/56479916/190159698-26e3ed1d-bef5-43a9-ad2b-7ea4da281a34.jpg)

2022-09-15 09:14 UTC, seadowg commented
@dbemke ah this is fascinating. We don't actually switch theming on the maps, so dark theming really doesn't work on the buttons. Event the visible map buttons look really out of place. I'll have a quick look at seeing if we can switch theming for the maps, but I doubt we'll be able to for all 3 engines. I think we'll probably need to look at forcing a light theme on screens with maps.

2022-09-15 12:51 UTC, seadowg commented
@dbemke ok I've made it so that the map buttons use light theming even when dark theme is enabled (as the map itself is always light). The one exception is the manual record button in geo shape/trace. That currently uses an old button style, and I think we'd need to redesign it for it to be worth forcing the light theme.

2022-09-16 10:24 UTC, dbemke commented
On light maps the light theme looks nice and a disabled button is visible but it possible to change the style of the map e.g. in Google maps satellite or hybrid style there's dark green in the background.
![stylesattelite2](https://user-images.githubusercontent.com/56479916/190618341-e9f01f93-7465-4335-a49f-ce851524ba21.jpg)
![stylehybrid2](https://user-images.githubusercontent.com/56479916/190618348-98d9aa24-e7ef-4942-a954-3b150036a434.jpg)

2022-09-16 11:15 UTC, seadowg commented
@dbemke I've tweaked the transparency of disabled buttons to hopefully make them more (but not too) visible on in geo shape/trace. Take a look and let me know what you think. If it's good enough, I can make that change in the other map views as well.

2022-09-16 12:12 UTC, dbemke commented
@seadowg I've checked different backgrounds (light and dark) and now disabled buttons are visible in every case.

2022-09-16 13:31 UTC, seadowg commented
@dbemke ok that's fixed everywhere now.

2022-09-19 13:15 UTC, srujner commented
**Tested with Success!**

Verified on Emulator with Android 13

Verified Cases:

- Issue from the comments is no longer reproducing;
- All map views;
- Enabled and Disabled buttons;
- Different map sources;
- Light and Dark mode;
- Horizontal and Vertical View;
- Buttons arrangement; 
- Overall UI look;
- Quick regression check on GeoPoint widgets, Submissions Select map and External map widgets;
- Offline Layers 
- RTL language

2022-09-19 13:16 UTC, dbemke commented
**Tested with Success!**

Verified on Android: 10

2022-09-19 22:22 UTC, merged