Avoid adding duplicate points in polylines/polyshapes
getodk/collect pull request #5275
Opened 2022-09-02 14:11 UTC by grzesiek2010

Closes #5186 

#### What has been done to verify that this works as intended?
I've tested the fix manually.

#### Why is this the best possible solution? Were any other approaches considered?
We discussed possible options in the issue. I think blocking duplicate points is the best one it not only fixes the issue but also improves the flow by reducing the number of points in polylines/polyshapes.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Adding duplicate points (manually or automatically) should be not possible so if the last point equals the one we try to add it's ignored. I can't see any risk here but please test this change carefully.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2022-09-12 17:15 UTC, seadowg requested changes
We need a test (in `GeoPolyActivityTest` most likely) to make sure this stays fixed. I reckon a short comment explaining why we do this is probably a nice idea on the test or in the implementation as well.

2022-09-12 17:16 UTC, seadowg commented
@getodk/testers just needs test coverage changes, so this is ready to look at despite the "Request Changes" status.

2022-09-14 06:44 UTC, dbemke commented
**Tested with Success!**

Verified on Android 10

**Verified cases:**

    • issue #5186 is no longer reproducing
    • regression check on Geo widgets with Google Maps, OSM, Mapbox
    • placement by tapping, manual and automatic location recording
    • adding, moving, removing points in Geo widgets with maps
    • saving and changing points in Geo widgets
    • fake GPS
    • editing and sending submissions to Central
    • offline layers
    • view submissions on map
    • don’t keep activities enabled/disabled
    • collecting location in the background – checking location in the audit log
    • forms with displaying markers: Select one from map, Internal map selects, Geojson 
    • screen rotation, minimizing the app, using backward button

2022-09-14 09:06 UTC, srujner commented
**Tested with Success!**

Verified on Android 13 on emulator

2022-10-05 14:06 UTC, seadowg approved these changes

2022-10-05 14:06 UTC, merged