Support colors and symbols for select one from map
getodk/collect pull request #5280
Opened 2022-09-09 10:08 UTC by grzesiek2010

Closes #5278
Closes #5279

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2022-09-09 10:56 UTC, grzesiek2010 commented
I've decided to create one pull request for the two issues since they are related and it will save us some time not only during implementing the feature but also during testing.

There are some things to discus:
1. So far we have used marker icons with a transparent hole it's something that doesn't look well of course with symbols so I had to add a new marker (without that hole) for markers that we use in select one from map. Please take a look at it and let me know if there is something you do not like about them. They seem to be a bit bigger but I can change it if it's a problem (we might need to first check how it looks like on different screens)
2. As I said above the new marker without a hole is used only for select one from map no matter if there is a symbol specified or not. There are a couple of options here:
     - We can leave it as is (use the new icon for select one form map and the old ones with holes in the map of forms)
     - We can use the new icon without a hole only if there is a symbol specified and in all the other cases use the old ones.
     - We can use the new icon everywhere 
I'm not sure, I think that it looks a bit weird to have that icon without a hole even if there is no symbol so maybe the second option would be the one I like more...
3. As I understand there is no need to display that new properties (marker-color, marker-symbol) in the bottom sheet? They should be only used to customize markers right?  

| Current version | New markers no color/symbol | New markers with color/symbol |
| ------------- | ------------- | ------------- |
| ![Screenshot_1662719740](https://user-images.githubusercontent.com/3276264/189331861-61371b60-7972-43c9-aa48-83af6296694c.png) |  ![Screenshot_1662719592](https://user-images.githubusercontent.com/3276264/189331841-a72366b2-c4f9-4f09-96c1-d264023ad384.png) | ![Screenshot_1662719611](https://user-images.githubusercontent.com/3276264/189331855-01108579-3958-4550-aa6e-5f3ad53a9411.png) |

@seadowg @lognaturel please let me know what you think.

2022-09-12 09:11 UTC, seadowg commented
> So far we have used marker icons with a transparent hole it's something that doesn't look well of course with symbols so I had to add a new marker (without that hole) for markers that we use in select one from map.

Looks good!

> We can use the new icon everywhere

It feels like it would be good to keep the marker shape as consistent as possible across our maps. I'd vote for this option I think.

> As I understand there is no need to display that new properties (marker-color, marker-symbol) in the bottom sheet? They should be only used to customize markers right?

Unless @lognaturel has a good reason, I don't think we should do the extra work to filter out properties.

2022-09-12 12:23 UTC, grzesiek2010 commented
> Unless @lognaturel has a good reason, I don't think we should do the extra work to filter out properties.

I thought it was the expected behavior so I've already done that extra work. If you agree we can keep it.

2022-09-13 20:28 UTC, grzesiek2010 commented
This is how it looks now:

| Emoji / brown color  | W symbol / red color | No symbol / no color | P symbol / white color |
| ------------- | ------------- | ------------- | ------------- |
| ![Screenshot_1663100223](https://user-images.githubusercontent.com/3276264/190002298-f5a0362c-44a8-406a-8ada-814634d430c3.png)  | ![Screenshot_1663100227](https://user-images.githubusercontent.com/3276264/190002305-198ab948-3d53-483c-8e06-7d6caa52d3cf.png)  | ![Screenshot_1663100230](https://user-images.githubusercontent.com/3276264/190002306-0098cbcc-6888-4350-969e-9932090c64e3.png)  | ![Screenshot_1663100234](https://user-images.githubusercontent.com/3276264/190002313-f4cc2c1d-249f-4e52-a7f6-9ae93291ed85.png)  |

2022-09-26 11:16 UTC, seadowg requested changes
I'll make changes based on my comments as @grzesiek2010 is away, but wanted to make sure it was clear what changes I was requesting to explain my follow ups.

2022-09-26 11:16 UTC, seadowg commented on geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
> +                map.setMarkerIcon(featureId, MarkerIconDescription(item.largeIcon, item.color, item.symbol))
As far as I can see, there aren't any tests to check that the map markers are set up with the correct color and symbol (or that they are retained when switching icon).

2022-09-26 11:16 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragment.kt
> +                    if (markerSymbol == null) R.drawable.ic_map_marker_with_hole_small else R.drawable.ic_map_marker_small,
There's no test that checks this change (choosing the icon based on the marker symbol)

2022-09-26 11:16 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragment.kt
> +                    markerSymbol
There's no test to check whether the `markerSymol` and `markerColor` are extracted from the choice's additional children and passed in correctly here. We should also have tests for cases where "marker-color" or "marker-symbol" don't exist.

2022-09-26 11:16 UTC, seadowg commented on maps/src/main/java/org/odk/collect/maps/MarkerIconDescription.kt
> +    override fun hashCode(): Int {
Not seeing why `hashCode` is overridden here? I get that there would need to be a custom implementation to maintain the behaviour we lose from moving away from `data class`, but I can't find anything that requires that behaviour. Additionally, even those this doesn't breach the `hashCode`/`equals` relationship (objects that are equal would have the same `hashCode` here), it does feel weird to have a smart `hashCode` implementation but leave `equals` using basic object equality as it massively increases the cases where two objects can have the same `hashCode` but be "unequal".

2022-09-26 11:29 UTC, seadowg commented
@getodk/testers this is ready for manual testing as all the remaining requested changes are just adding automated tests.

2022-09-26 11:35 UTC, seadowg commented on maps/src/main/java/org/odk/collect/maps/MarkerIconDescription.kt
> +    override fun hashCode(): Int {
I've removed this and all tests seem to be passing.

2022-09-27 10:43 UTC, srujner commented
I noticed one strange behavior on every device:

https://user-images.githubusercontent.com/85225519/192499675-e1ebc40f-3086-4dcc-a8ce-a47b465bcdda.mp4

The "Berlin" point doesn't have "marker-color:" information in info, maybe that's the reason. 
I was able to reproduce it in geojson form to.

2022-09-27 10:51 UTC, srujner commented
One more thing to discuss:
The "P" point is barely visible on white background. Maybe adding some black outline to points wouldn't be a bad idea? 
So that they do not blend in with the background.

![Screenshot_20220927-110314(1)](https://user-images.githubusercontent.com/85225519/192506399-7bae409b-d71d-4697-89a4-95f98b515aaf.png)

2022-09-27 13:12 UTC, seadowg commented
> I noticed one strange behavior on every device:

This definitely looks like a bug. I'll investigate.

> The "P" point is barely visible on white background. Maybe adding some black outline to points wouldn't be a bad idea?
So that they do not blend in with the background.

Unless there's something I'm missing in the spec, I think this is something we should consider "user error" - it's probably a bad idea to use white markers. Does that sound fair @lognaturel? If not, I think we should write up a separate issue for the extra hand holding of special cases for hard to see markers.

2022-09-27 13:20 UTC, seadowg commented
@srujner could you confirm you're seeing the problem with markers without `marker-color` using the wrong color with the latest version of the PR please?

2022-09-27 14:21 UTC, srujner commented
@seadowg I can confirm to reproduce the issue with the latest version. Sometimes you need to select the markers first or change map source and then click multiple times on markers to reproduce it.

2022-09-27 15:16 UTC, seadowg commented
@srujner could you send me the form you're using to reproduce?

2022-09-27 15:34 UTC, lognaturel commented
> I think this is something we should consider "user error" 

Yes, I agree. We could eventually consider an outline for all markers -- this issue is not specific to the new features.

2022-09-28 07:59 UTC, srujner commented
@seadowg It's the one attached by Grzegorz
[form(1).zip](https://github.com/getodk/collect/files/9662743/form.1.zip)

2022-09-28 10:08 UTC, seadowg commented
@srujner ok that should be fixed now.

@grzesiek2010 this was a weird one! It turns out that we need to be calling [`mutate`](https://developer.android.com/reference/android/graphics/drawable/Drawable.html#mutate()) on `Drawable` objects we want to modify, or we end up with some state being shared between resources with the same ID (the docs explain this better than I would). This actually might explain some issues we've seen with day/night theme switching - although that will be most likely due to a lack of `mutate` calls in framework code.

2022-09-28 12:48 UTC, srujner commented
**Tested with Success!**
Verified on Android: 10, 12 and 13 

Verified cases:
    • Regression checks for GeoPoint, GeoTrace, GeoShape widgets; 
    • Select Map forms;
    • Adding markers to maps;
    • Offline Layers; 
    • Google Maps, Mapbox, OSM and all map styles; 
    • Collecting Location in background; 
    • View Submissions on map; 
    • Screen rotation, minimize app, using backward button,

2022-09-28 15:23 UTC, seadowg approved these changes

2022-09-28 15:53 UTC, merged