Remove untested and (believed to be) unnecessary updateAnswersForScreen calls
getodk/collect pull request #5330
Opened 2022-11-02 13:57 UTC by seadowg

- Convert test to Kotlin
- Add higher level assertion on track changes audit event to make iteration easier
- Make rotate actions consistent
- Remove overload
- Reformat code
- Stop updating screen answers in onPause
- Remove untested and (believed to be) unnecessary updateAnswersForScreen calls

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-09 20:08 UTC, grzesiek2010 requested changes

2023-02-09 20:08 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> -                                formEntryViewModel.updateAnswersForScreen(getAnswers(), false);
When you remove this, if we answer a question and change language then the answer is cleared. I don't think it is the expected behavior. We should have a test for this.

2023-02-09 20:08 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
> -                formEntryViewModel.updateAnswersForScreen(answersProvider.getAnswers(), false);
This is needed. Please try a form with repeats and then:
1. Answer a question.
2. Try to add a new group using the plus button.
3. Click `Do not answer` or `Add` (it doesn't matter).
4. The answer from the first question is removed.

We also should have an automated test for this case.

2023-02-09 20:08 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryMenuDelegateTest.java
> -    public void onItemSelected_whenAddRepeat_savesScreenAnswers() {
We still need this test as explained above.

2023-02-09 20:08 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
> -                        formEntryViewModel.updateAnswersForScreen(getAnswers(), false);
This indeed seems to be redundant but we would need to ask the QA team to play with clearing answers.

2023-02-15 18:44 UTC, seadowg commented
@grzesiek2010 thanks for taking a look through this! I'll have a look at adding tests for the calls you've identified as us still needing, and then we can hand over to QA to check for any other regressions.

2023-03-27 15:16 UTC, grzesiek2010 approved these changes

2023-03-27 15:27 UTC, grzesiek2010 commented
@srujner @dbemke you need to focus on testing if the state of questions (and answers) is preserved/updated correctly. By that I mean:
- answers do not disappear/are not changed (if they shouldn't)
- if there are multiple questions on one screen and they are related to each other (appear/disappear as a result of answering other questions, change their answers as a result of changing other questions etc.) everything works fine

Please test this not only by answering questions but also by triggering actions like:
- changing form language
- returning to the app etc.

2023-03-29 12:12 UTC, dbemke commented
**Tested with Success!**

Verified on Android 10

**Verified Cases:**
- checking issues mentioned in the PR 
- killing the app, minimizing, rotating, locking the screen
- changing settings (language, theme) in the middle of filling, editing a form
- don’t keep activities enabled/disabled
- regression checks in Fill Blank Form, Restoring the app from the background when Form Entry dialogs displayed, Get Blank Form, Track Reason Changes and other
- forms with audit, fieldlist updates form, All widgets, one question translation form, saveIncomplete, Identify User

2023-03-29 12:17 UTC, srujner commented
**Tested with Success!**

Verified on Android 13

2023-03-30 08:32 UTC, merged