Use LocalizedActivity instead of CollectAbstractActivity if it is possible
getodk/collect pull request #5442
Opened 2023-02-13 09:13 UTC by grzesiek2010

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-14 16:35 UTC, seadowg reviewed
Really nice to see this! I think you might be able to kill `CollectAbstractActivity` entirely here right? Not sure if there's a reason it can't be removed as the supertype for `ProjectPreferencesActivity`, and I think we could just push the `isInstanceStateSaved` stuff down to where it's used in `InstanceUploaderActivity`. I could totally be missing some complexity there though.

2023-02-14 16:36 UTC, seadowg requested changes
See https://github.com/getodk/collect/pull/5442#pullrequestreview-1297976987

2023-02-15 12:39 UTC, grzesiek2010 commented
> Really nice to see this! I think you might be able to kill CollectAbstractActivity entirely here right? Not sure if there's a reason it can't be removed as the supertype for ProjectPreferencesActivity, and I think we could just push the isInstanceStateSaved stuff down to where it's used in InstanceUploaderActivity. I could totally be missing some complexity there though.

It is needed in `ProjectPreferencesActivity` because we check the state in `ResetDialogPreferenceFragmentCompat`. But still, I can add it in both `InstanceUploaderActivity` and `ProjectPreferencesActivity` and remove `CollectAbstractActivity` entirely.

2023-02-15 16:23 UTC, seadowg approved these changes

2023-02-15 16:23 UTC, merged