Do not use dagger in AudioRecorderFactory
getodk/collect pull request #5446
Opened 2023-02-16 17:10 UTC by grzesiek2010

Closes #5445 

#### What has been done to verify that this works as intended?
I've tested recording audio.

#### Why is this the best possible solution? Were any other approaches considered?
We don't know why there is a problem with initializing that particular field (`internal lateinit var recordingRepository: RecordingRepository`). I guess dagger might have some problems with injecting objects into regular classes that are not components like activity/fragment/service, or maybe it's related to modularizing the app too, or maybe even with kotlin... it's difficult to tell. Fortunately in AudioRecorderFactory we don't have to use dagger and we can just create a new instance of `RecordingRepository`.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test recording audios with the forms available on the demo server.

#### Do we need any specific form for testing your changes? If so, please attach one.
Forms with audio recording.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-02-16 20:46 UTC, seadowg requested changes
This is a nice solution. Hopefully it either fixes the issue, or exposes something more obvious around what's happening. It looks like we could complete remove `RecordingRepository` from our `AudioRecorderDependencyModule` which would make the current change less out of place, so I think we should do that. I'm guessing we originally had it operate as a singleton rather than using `AppState` which allows us to get the same state from any instance.

2023-02-18 12:36 UTC, grzesiek2010 commented
> It looks like we could complete remove RecordingRepository from our AudioRecorderDependencyModule which would make the current change less out of place, so I think we should do that. I'm guessing we originally had it operate as a singleton rather than using AppState which allows us to get the same state from any instance.

Done.

2023-02-20 22:56 UTC, seadowg approved these changes

2023-02-21 13:36 UTC, srujner commented
**Tested with Success!**

Verified on Android 13

**Verified cases:**

- Audio forms available on demo server;
- All other audio forms;
- Background audio recording;
- Background processing off/on;
- Rotate the screen and minimize the app;
- Use external app for audio recording;

2023-02-21 13:46 UTC, dbemke commented
**Tested with Success!**

Verified on Android 10

2023-02-21 14:50 UTC, merged