Dependency updates v2023.2
getodk/collect pull request #5503
Opened 2023-03-18 19:46 UTC by grzesiek2010

#### What has been done to verify that this works as intended?
I've run automated tests and reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
As usual, I've updated the dependencies for the next release.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-03-22 11:23 UTC, seadowg requested changes

2023-03-22 11:23 UTC, seadowg commented on osmdroid/build.gradle
> +        exclude group: 'androidx.lifecycle'
Was curious why this was needed. Taking it out, I get a "Corrupt serialized resolution result" error on Gradle Sync. This looks like a weird Gradle issue: https://github.com/gradle/gradle/issues/14220. If that's the reason you added this, then let's add a comment here, making sure it's clear that it's a workaround for that issue. Hopefully we'd be able to avoid using the `exclude` here at some point.

2023-03-22 19:39 UTC, grzesiek2010 commented on osmdroid/build.gradle
> +        exclude group: 'androidx.lifecycle'
Ok. I've added a comment.

2023-03-23 09:46 UTC, seadowg approved these changes

2023-03-23 11:31 UTC, merged