Improved handling default images
getodk/collect pull request #5504
Opened 2023-03-19 12:23 UTC by grzesiek2010

Closes #5496

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-03-20 09:19 UTC, seadowg requested changes

2023-03-20 09:19 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
> +            if (binaryName != null && file != null) {
Can this just be `if (file != null)`?

2023-03-21 00:06 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
> +            if (binaryName != null && file != null) {
Right it can be simplified, done.

2023-03-21 09:38 UTC, seadowg approved these changes

2023-03-22 11:33 UTC, srujner commented
**Tested with Success!**

**Verified on device with Android**: 13

**Verified cases**;

- Issue #5496 is no longer reproducing;
- Regression check on Image/Draw/Signature/Annotate widgets;
- DefaultImagesTest form tested; 
- Minimize the app, rotate the screen;
- Light and Dark mode.

2023-03-22 11:36 UTC, merged