When a control in "Access control" settings is unchecked, hide that control
getodk/collect pull request #5589
Opened 2023-05-16 10:07 UTC by grzesiek2010

Closes #5581 

#### What has been done to verify that this works as intended?
I've tested the changes manually and updated automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
As described in the issue, we decided that in order to make the behavior consistent across the app, the buttons should be hidden not disabled. When it comes to the implementation itself there is nothing important to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe pr, please just verify that buttons are hidden (if disabled in settings) as described in the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-05-16 14:20 UTC, seadowg requested changes
The buttons are no longer constrained by the size of the warning card:

![image](https://github.com/getodk/collect/assets/556280/3b6a66cd-ba1e-41f2-80b4-30d66e02d66d)

2023-05-16 14:20 UTC, seadowg commented on collect_app/src/main/res/layout/form_entry_end.xml
> +            <View
I think you can use `layout_GoneMarginX` attributes instead of a spacer view here. There's an example in `property.xml`.

2023-05-16 15:37 UTC, grzesiek2010 commented on collect_app/src/main/res/layout/form_entry_end.xml
> +            <View
Right, done.

2023-05-16 15:37 UTC, grzesiek2010 commented
> The buttons are no longer constrained by the size of the warning card:

Fixed.

2023-05-17 07:31 UTC, seadowg approved these changes

2023-05-17 07:31 UTC, seadowg commented on collect_app/src/main/res/layout/form_entry_end.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
I think there must be a way to do this without nested `ConstraintLayout`s (maybe using `Barrier`), but it's really awkward to work out. Happy to go with this for now.

2023-05-17 12:05 UTC, srujner commented
**Tested With Success!**

Verified on device with Android 13

**Verified cases:**
- Issue #5589 is no longer reproducing;
- Save as Draft button is not visible when the option is unchecked in Form Entry Settings;
- Finalize button is not visible when the option is unchecked in Form Entry Settings;
- Minimize the app, rotate the screen;
- Light and Dark mode

2023-05-17 12:08 UTC, dbemke commented
**Tested With Success!**

Verified on device with Android 10

2023-05-17 12:18 UTC, merged