Show snackbar notification when a form is saved or sent
getodk/collect pull request #5609
Opened 2023-05-25 19:44 UTC by grzesiek2010

Closes #5424 

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-05-27 13:39 UTC, seadowg requested changes
Now we've got this to play with, I think there are a couple of behavioural things we should change before diving into a code review:

* The snackbar should be hidden after an action (like "View") is clicked. Right now it's on-screen for a while (which is good), but if you click "View" and then press back to return the menu, the snack bar is still there and is confusing.
* The "It looks like you're offline..." doesn't really make sense as-is. We only show it if the device is connected to the network required for auto send, but somehow also offline which will happen very rarely (even if at all) in reality. I think we should show also show this message in the cases that auto send won't happen (auto send is wifi only, but we only have a cellular connection for instance). We might need to tweak the text a little as "offline" won't be strictly true any longer. It'd be good to get some thoughts from @alyblenkin on this one.

2023-05-27 18:09 UTC, alyblenkin commented
> Now we've got this to play with, I think there are a couple of behavioural things we should change before diving into a code review:
> 
> * The snackbar should be hidden after an action (like "View") is clicked. Right now it's on-screen for a while (which is good), but if you click "View" and then press back to return the menu, the snack bar is still there and is confusing.

Ah yes, it should go away if you press back to return to the main menu. You wouldn't want to see the snackbar after you've take an action, it should disappear. 

> * The "It looks like you're offline..." doesn't really make sense as-is. We only show it if the device is connected to the network required for auto send, but somehow also offline which will happen very rarely (even if at all) in reality. I think we should show also show this message in the cases that auto send won't happen (auto send is wifi only, but we only have a cellular connection for instance). We might need to tweak the text a little as "offline" won't be strictly true any longer. It'd be good to get some thoughts from @alyblenkin on this one.

I didn't think about this - good point! 

If the device is connected to the network required for auto-send, we show "It looks like you're offline..." 

If they have a cellular connection, but no wifi, perhaps we could show "It looks like you don't have Wi-Fi. Your form will send when you are online" or "connected"? I guess they technically have a cellular connection. "It looks like you don't have Wi-Fi. Your form will be sent when you connect" 

What do you think?

2023-05-29 08:46 UTC, grzesiek2010 commented
> If they have a cellular connection, but no wifi, perhaps we could show "It looks like you don't have Wi-Fi. Your form will send when you are online" or "connected"? I guess they technically have a cellular connection. "It looks like you don't have Wi-Fi. Your form will be sent when you connect"

Now I wonder if it make sense to check internet connection and display it in the snackbar at all...
1. Theoritecally it is possible that there is no connection when the snackbar is being created but 1s later when the process of sending forms starts the devices is connected or the other way around so the message might not be accurate.
2. We would need to check more cases and probably display different messages:
   - `wifi only` is selected in settings but you have no connection or only cellular 
   - `cellular only` is selected in settings but you have only wifi
   - `wifi or cellular` is selected in settings but there is no connection at all
3. When auto-send fails we display a notification and I think that notification should contain a proper message that explain what happened.

Taking into account all of that maybe the snackbar should always display `Sending form…` if autosend is enabled and that notification should be responsible for providing more info.

2023-05-29 10:05 UTC, seadowg commented
> If the device is connected to the network required for auto-send, we show "It looks like you're offline..."

Do you mean if they're connected, but their connection isn't working (like bad signal for instance)? We won't be able to detect that scenario dependably. The only times the phone really knows it's "offline" it can't find a cellular or Wi-Fi network at all. We could try and determine whether we have a "good" connection or not (pinging a known dependable server for instance), but I think that's further than we want to go here (and it's not trivial to do if we're needing to determine the quality of a specific connection type).

> If they have a cellular connection, but no wifi, perhaps we could show "It looks like you don't have Wi-Fi. Your form will send when you are online" or "connected"? I guess they technically have a cellular connection. "It looks like you don't have Wi-Fi. Your form will be sent when you connect"

I think this approach makes sense. I guess the different scenarios when auto send is enabled we need to cover could look like this:

1. wifi and cellular enabled, but neither available
2. wifi only, but not available (cellular may or may not be enabled but doesn't change anything)
3. cellular only, but not available (wifi may or may not be enabled but doesn't change anything)

As I'm writing this I'm realizing there's further complexity here: in situation 2 or 3, I don't think we'll ever auto send the form if the connection type we need is disconnected, but the other is working. This is because (as far as I can tell) we currently wait for any connection to try and auto send, but will then determine whether we have the correct connection type or not and (again, as far as I can see), won't reschedule trying to send again if we don't. This would mean in a case where we have a cellular connection, but no wifi and auto send is "wifi only", we'd actually never auto send the form, so we can't say  "Your form will be sent when you connect".

@grzesiek2010 could you investigate this to see if I'm correct about those scenarios or not? I think we might want to either rethink what we say on this snackbar, or try and improve the auto send behaviour before adding it (which I'd prefer).

2023-05-30 11:33 UTC, grzesiek2010 commented
> This would mean in a case where we have a cellular connection, but no wifi and auto send is "wifi only", we'd actually never auto send the form, so we can't say "Your form will be sent when you connect".

In such cases, the `Send` button in the end screen is not displayed instead we see the `Finalize` one so it wouldn't be a problem. The message in snackabr would also be `Your form was saved` and not `Sending form...`.

But again the more I think about it the more I'm convinced that if the button is `Send` we should always display just `Sending form...` because as I said above at the time when the scankbar is being created the connection might not be available but after 1s it changes and the form is sent or the other way around. This solution would be simpler and more accurate and potential errors should be displayed in a notification.

2023-05-30 13:07 UTC, seadowg commented
> But again the more I think about it the more I'm convinced that if the button is Send we should always display just Sending form... because as I said above at the time when the scankbar is being created the connection might not be available but after 1s it changes and the form is sent or the other way around

Yeah I agree with this. I think we should go with this for the moment (not have a different message for "offline"), and then look at revising auto send to be less brittle in the future. I think there's a lot we could improve around retrying to send when we have the correct connection that would allow us to more accurately say to the user "Your form will be sent later". Does that sound ok @alyblenkin?

If so, let's remove that offline message and hide the snackbar when an action is clicked as discussed [here](https://github.com/getodk/collect/pull/5609#pullrequestreview-1447384244).

2023-05-30 15:36 UTC, lognaturel commented
Agreed just giving feedback that a send attempt is ongoing and giving a way to immediately view the form that was just completed is already very helpful. Seems reasonable to focus on that for this release.

Have we also considered showing a snackbar when an autosend attempt completes? Currently we show a notification but my experience is that those are really easy to miss and they feel less tied to current actions. I think we may have discussed switching to or adding snackbars at some point.

For example:
- autosend runs, a single form is successfully sent: "Form sent. &nbsp;&nbsp;&nbsp;&nbsp;View"
- autosend runs, multiple forms are successfully sent: "N forms sent."
- autosend runs, there are failures: "Autosend failure&nbsp;&nbsp;&nbsp;&nbsp;Go to Ready to send" (not sure what that action link should be)

2023-05-30 18:38 UTC, alyblenkin commented
> Agreed just giving feedback that a send attempt is ongoing and giving a way to immediately view the form that was just completed is already very helpful. Seems reasonable to focus on that for this release.
> 
> Have we also considered showing a snackbar when an autosend attempt completes? Currently we show a notification but my experience is that those are really easy to miss and they feel less tied to current actions. I think we may have discussed switching to or adding snackbars at some point.
> 
> For example:
> 
> * autosend runs, a single form is successfully sent: "Form sent.     View"
> * autosend runs, multiple forms are successfully sent: "N forms sent."

I spoke to @seadowg about the successfully sent message a while back, and we were worried that they could appear out of context or mid-flow when they are filling out another form. I documented some of that [conversation here](https://www.notion.so/System-notifications-e29d1836cdf744d6905794cebb312b25) - @seadowg suggested we could maybe leverage system notifications down the road.

> * autosend runs, there are failures: "Autosend failure    Go to Ready to send" (not sure what that action link should be)


What about - "Unable to send. Your form "Ready to Send" later.  View"

2023-05-30 19:45 UTC, grzesiek2010 commented
> If so, let's remove that offline message and hide the snackbar when an action is clicked as discussed

Done.

2023-06-05 12:44 UTC, seadowg requested changes
Looking good! Just a few things inline, but nothing major.

Before merging, it would be good to rebase this on top of `master` so that it gets the latest fixes for our instrumentation tests as this is red on Test Lab right now.

2023-06-05 12:44 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
> +        setResult(RESULT_OK, result.getData());
This isn't covered by any tests as far as I can tell.

2023-06-05 12:44 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
> -        markSubmissionFailed(instance);
Is there any benefit to changing this?

2023-06-05 12:44 UTC, seadowg commented on testshared/build.gradle
> +    implementation Dependencies.mockito_kotlin
I don't think you ended up needing this

2023-06-05 12:44 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
> +class FormSavedSnackbarTest {
I think you only need to test the saving a new form and saving a draft cases here (to check that the activity result setup is correct, and the Activity is hooked up to the ViewModel). Most of the details of the snack bar seem to be covered in the tests for `MainMenuViewModel#getFormSavedSnackbarType` in `MainMenuViewModelTest`.

2023-06-05 12:44 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
> +            return when (instance.status) {
This `return` can be lifted to the `if`

2023-06-06 10:08 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
> -        markSubmissionFailed(instance);
1. It was a confusing workaround. If the form was marked a failed before sending it was also visible to a user.
2. When creating a snackbar I need a real status but here it was possible that a form would be marked as failed first.

2023-06-06 10:12 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
> +            return when (instance.status) {
You mean something like this:
```java
    fun getFormSavedSnackbarType(uri: Uri): FormSavedSnackbarType? {
        val instance = instancesRepositoryProvider.get().get(ContentUriHelper.getIdFromUri(uri))
        if (instance != null) {
            if (instance.status == Instance.STATUS_INCOMPLETE) {
                return FormSavedSnackbarType.SAVED_AS_DRAFT
            } else if (instance.status == Instance.STATUS_COMPLETE) {
                val form = formsRepositoryProvider.get().getAllByFormIdAndVersion(instance.formId, instance.formVersion).first()
                return if (form.shouldFormBeSentAutomatically(autoSendSettingsProvider.isAutoSendEnabledInSettings())) {
                    FormSavedSnackbarType.SENDING
                } else {
                    FormSavedSnackbarType.FINALIZED
                }
            }
        }
        return null
    }
```

I don't see any advantage of this change.

2023-06-06 11:03 UTC, grzesiek2010 commented on testshared/build.gradle
> +    implementation Dependencies.mockito_kotlin
Right.

2023-06-06 11:04 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
> +        setResult(RESULT_OK, result.getData());
Fixed in https://github.com/getodk/collect/pull/5609/commits/9930c96c2c983c7f2a1654cc1a36d160ebfb4955

2023-06-06 16:02 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
> +class FormSavedSnackbarTest {
The tests in MainMenuViewModelTest verify that a proper SnackbarType is returned based on form status but they do not verify:
- if the snackbar is displayed at all
- if it contains proper message and action
- if a form is opened for edit/view after clicking on the action

2023-06-06 16:02 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
> +            return when (instance.status) {
Done.

2023-06-07 09:37 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
> -        markSubmissionFailed(instance);
Thanks that all makes sense!

2023-06-07 09:49 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
> +class FormSavedSnackbarTest {
As far as I can see, there is no conditional logic in `displayFormSavedSnackbar`. Therefore, if you just had a test that checks the snack bar flow for a new form (as finalized or a draft) and another to check the flow when editing and then saving a draft (as finalized or a draft), that'd check that the code that shows the snack bar is there and that the activity result stuff (why you need two tests for the two Activity objects) is all hooked up correctly. Then, the other cases are all covered by your tests in `MainMenuViewModelTest` as you check there that you get the right messages and actions in the right scenarios. As far as I understand whether the form gets opened for editing/viewing etc is handled by `FormUriActivity` and that is all tested in `FormUriActivityTest`. 

Basically, I'm imagining the top level of tests (instrumented) just check "we show a snack bar after filling a new form" and "we show a snack bar after editing a draft" and that the ViewModel tests and Activity tests (local) can cover the details like how the form was saved, is auto send on etc.

Does that make sense? Happy to chat about it more!

2023-06-07 12:03 UTC, seadowg commented
I'm going to mark this "needs testing", as we're only discussing tests now.

2023-06-07 13:40 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
> +class FormSavedSnackbarTest {
Ah yeah it makes sense.

2023-06-07 14:57 UTC, seadowg approved these changes

2023-06-14 12:02 UTC, dbemke commented
I'm not sure what should be an expected results in some scenarios:
1.   Steps:
-  Go to Drafts
- Open a form, go to a question
- Tap the device back button and **discard** changes

In this case the user is moved to the main menu and sees "Your form was **saved** as a draft" 

2. If there are few forms in Ready to send that are being sent at the moment and I'm on the main menu should I see the snackbar "Sending form..." for each form when it's being sent?

2023-06-14 13:52 UTC, dbemke commented
3. Steps:
-  In Form Entry settings disable moving backwards.
- Go to Start new form and open a form.
- Fill the form and save it as a draft
- When the snackbar appears click "Edit”

The user is moved to the view of a form with only an "Exit" option which seems ok but on the other hand moving backwards is supposed to prevent edits(?) so the word Edit in snackbar might be confusing?

2023-06-14 15:00 UTC, dbemke commented
Similar scenario to the previous one
4. Steps:
- In Access control, Main Menu Settings disable Drafts
- Go to Start new form and open a form.
- Fill the form and save it as a draft
- When the snackbar appears click "Edit”

The user is moved to the view of a form with only an "Exit" option

2023-06-15 11:51 UTC, grzesiek2010 commented
> Go to Drafts
Open a form, go to a question
Tap the device back button and discard changes
In this case the user is moved to the main menu and sees "Your form was saved as a draft"

Not perfect but also not something terrible to me. It happens because the snackbar is created whenever after quitting a form its URI is returned. It turns out that when we close a form discarding changes it is returned. I'm not sure if it's the expected behavior but we probably shouldn't touch it so fi we want to improve the current behavior we need to add something to the returned intent when the form is closed to distinguish those cases.

> If there are few forms in Ready to send that are being sent at the moment and I'm on the main menu should I see the snackbar "Sending form..." for each form when it's being sent?

No, the snackbar should be displayed only after closing a form for that particular form.

> In Form Entry settings disable moving backwards.
Go to Start new form and open a form.
Fill the form and save it as a draft
When the snackbar appears click "Edit”

Here the action name should be `View` instead of `Edit`

> In Access control, Main Menu Settings disable Drafts
Go to Start new form and open a form.
Fill the form and save it as a draft
When the snackbar appears click "Edit”

As above the action name should be `View` instead of `Edit`

I also wonder if it makes sense to have that `Save as draft` options visible if editing drafts is disabled like in those two last cases but it's somethingfor a separate discussion I guess.

@seadowg what do you think about all those cases? Do you agree with what I said?

2023-06-15 12:22 UTC, dbemke commented
One more question about expected
5. Steps:
- In settings, access control, main menu settings disable Ready to send and Sent
- Go to a form and send it

The users sees a snackbar with "View" option. I don't know if hiding Ready to send and Sent option from the main menu means that the user is not supposed to view forms that are being sent/ were sent?

2023-06-15 12:33 UTC, grzesiek2010 commented
> In settings, access control, main menu settings disable Ready to send and Sent
Go to a form and send it
The users sees a snackbar with "View" option. I don't know if hiding Ready to send and Sent option from the main menu means that the user is not supposed to view forms that are being sent/ were sent?

Hmm If viewing sent forms was only in the list of sent forms (not in the list of forms to send too) I would say that the View option in the snackbar should not be available but now I don't know... I would file a separate issue for this and discuss it later.

2023-06-16 09:23 UTC, seadowg commented
For **1**, I think we should fix this now by not showing a snackbar when exiting a form via "Discard changes/form". In terms of implementation, I think it should be fairly feasible to just not set a result (or set a `RESULT_CANCELLED` result) in `FormFillingActivity` when changes are discarded so that the activity result callbacks never end up firing. If it ends up being much more complex than that, then I agree it's something we should look at as a separate PR.

Totally agree that for cases **3** and **4** we should just change the action text from "Edit" to "View". It might be that there's a helper we can pull out (probably from the logic in `FormUriActivity`) so that we don't end up duplicating things.

I also agree that **5** is something we should discuss as part of another issue - we might not make any changes there.

2023-06-16 14:41 UTC, grzesiek2010 commented
> In terms of implementation, I think it should be fairly feasible to just not set a result (or set a RESULT_CANCELLED result) in FormFillingActivity when changes are discarded so that the activity result callbacks never end up firing.

You mean removing returning URI in that case like in https://github.com/getodk/collect/pull/5609/commits/76ec768a0f7b713cb34bec1b7672190b290796c0
Generally, I was thinking about that, and to me, that didn't even make sense (retuning that uri) but still, I'm not sure if it's not going to break anything...

2023-06-19 09:57 UTC, seadowg commented
@grzesiek2010 Yes that makes sense to me. It's a change in behaviour that will affect external apps (calling into Collect), so we'll need to announce the change explicitly, but that's ok.

2023-06-20 13:20 UTC, srujner commented
@dbemke already tested this PR

**Tested With Success!**

**Verified on Device with Android**: 10, 12, 13

**Verified Cases**:
- Acceptance Criteria from #5424 has been met;
- Issues mentioned by Dominika has been fixed;
- Number **5** will be created as separate Issue to discuss;
- Snackbars with all auto send options;
- Snackbars while auto sent is set to true or false and auto delete is set to true or false in a form;
- Switching to airplane mode while on the end page and trying to send a form in Start new form and Drafts with saving as draft enabled and disabled in Form End;
- Checking audit logs after editing and viewing the form via snackbar in Track changes and Track changes reason, Identify user forms;
- Snackbars while moving backwards is disabled, Drafts disabled in the main menu;
- Using Save as Draft option when Exiting the Form;
- Viewing a sent form via snackbars while in settings Delete after send is enabled and disabled;
- Sending a form while in server setting there is a wrong URL;
- Different font sizes;
- Don’t keep activities enabled/disabled;
- In device settings - no background processes;
- Saving, sending a form added from the form map view;
- Light and Dark Mode;
- Rotate the screen, minimize the app.

2023-06-20 13:51 UTC, merged