Fixed TriggerWidget
getodk/collect pull request #5611
Opened 2023-05-26 11:13 UTC by grzesiek2010

Closes #5523 

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-05-31 13:22 UTC, seadowg requested changes

2023-05-31 13:22 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/regression/TriggerWidgetTest.java
> +    public void whenTwoTriggerWidgetsPlacedOnOneScreen_keepProperAnswersOnScreenRotation() {
How would you feel about replacing this with a unit test for `TriggerWidget` that checks that the checkbox gets a new ID each time?

2023-05-31 18:42 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/regression/TriggerWidgetTest.java
> +    public void whenTwoTriggerWidgetsPlacedOnOneScreen_keepProperAnswersOnScreenRotation() {
Yes, that's a good idea. Done.

2023-06-01 08:35 UTC, seadowg approved these changes

2023-06-01 14:21 UTC, dbemke commented
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- issue #5523 is no longer reproducing
- All widgets – trigger widget
- don’t keep activities enabled/disabled
- no background processes setting
- rotating, minimizing, locking the screen

2023-06-01 14:24 UTC, srujner commented
**Tested with Success!**

Verified on device with Android 13

2023-06-01 14:31 UTC, merged