Allow viewing finalized forms in "Ready to send"
getodk/collect pull request #5629
Opened 2023-06-07 08:29 UTC by seadowg

- Allow viewing finalized form from Ready to send
- Convert test to Kotlin
- Make use of withProject helper
- Add failing test for selection in Ready to send
- Remove InstanceListActivity
- Remove InstanceUploaderListActivity from AppListAcitivty hierarchy
- Reimplement selection on Ready to send with MultiSelectViewModel
- Spike out working select all for Ready to send
- Move helper

Closes #

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-06-07 12:00 UTC, grzesiek2010 requested changes

2023-06-07 12:00 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.java
> +public class ViewFormPage extends Page<ViewFormPage> {
New class and it's java? Kotlin would be better here.

2023-06-07 12:00 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormFinalizingTest.kt
> +            .assertText("52")
I don't think those three last steps are needed here. This test is for checking if the form is finalized and asserting it ended up in the list of finalized forms is enough. Instead, the last step should be: `assertNumberOfFinalizedForms(1)`

2023-06-07 12:00 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
> +            case BY_STATUS_ASC:
We do not support sorting by status. It was possible in the past when for example we had incomplete and finalized forms on the same list. So it looks like we can get rid of it.

2023-06-07 12:00 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
> +            case BY_STATUS_ASC:
Again sorting by status seems to be redundant.

2023-06-07 12:04 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.java
> +public class ViewFormPage extends Page<ViewFormPage> {
Great catch! Not sure what I was thinking 😆.

2023-06-07 12:05 UTC, dbemke commented
Forms get deselected in "Ready to send" after minimizing the app when "don't keep activities" is enabled. The issue isn't present on the master version

**Steps to reproduce:**
1. In device settings enabled "don't keep activities".
2. In collect settings turn off the auto send option.
3. Send a submission.
4. Go to "Ready to send" and select the form.
5. Minimize the app.
6. Go back to the app.

2023-06-07 12:41 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormFinalizingTest.kt
> +            .assertText("52")
The `.clickOnForm` and `assertText` are what drives out being able to click on forms in this view. Would you prefer that I split that out to another test like `canViewFinalizedForms()`?

2023-06-07 12:55 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormFinalizingTest.kt
> +            .assertText("52")
Yeah, definitely there should be a separate test for checking if opening finalized forms for review is possible. This test is about saving only.

2023-06-07 13:43 UTC, seadowg commented
@dbemke fixed!

2023-06-07 14:27 UTC, seadowg commented
@dbemke looks like my solution for saving state when "Don't kill Activities" is on is breaking "Delete blank form". I think there's some deeper work to do there that's not worth it right now. I'm going to just revert that change, and then you can file an issue after we merge this that "Ready to send" and "Delete blank form" do not keep selections when multitasking with "Don't keep activities".

2023-06-08 00:41 UTC, grzesiek2010 requested changes

2023-06-08 00:41 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormFinalizingTest.kt
> +            .clickSendFinalizedForm(1)
There is no need to click on the button just use `assertNumberOfFinalizedForms` like in the test below.

2023-06-08 11:08 UTC, srujner commented
**Tested with Success!**

Verified on device with Android 13

Verified cases:
- deleting a form from file directory while the form is opened in Ready to send
- trying to open a deleted form
- adding instances to Ready to send manually in file directory
- multiclikicng
- deleting forms with auto send off and failed submissions in Delete form
- don't keep activities enabled/disabled
Changing view to Show Sent/Unsent Forms
Viewing Finalized Forms
Minimize the app and rotate the screen
No background processing option turned off/on

2023-06-08 11:10 UTC, dbemke commented
**Tested with Success!**

Verified on device with Android 10

2023-06-08 11:10 UTC, grzesiek2010 approved these changes

2023-06-08 11:11 UTC, merged