Remove Google Drive projects with no saved forms
getodk/collect pull request #5675
Opened 2023-07-13 19:01 UTC by grzesiek2010

Closes #5402 

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-07-18 10:22 UTC, grzesiek2010 commented
@seadowg @alyblenkin This was not clearly described in the issue but I updated the banner in a way that it is always visible so I removed the `Dismiss` button too. I think that's ok since it's the last version before removing the functionality completely but wanted to confirm with you.

2023-07-18 21:08 UTC, alyblenkin commented
Hey @grzesiek2010,  I agree with removing the dismiss button. It would be annoying, but we want to make it clear that it's going away soon!

Small design tweaks:
- Could we make the background of the message the same light blue that we use for the end of the finalization flow, so it reads as a warning and draws their attention to the top?
- I also think the icon we use in the finalization flow would be helpful to have at the beginning of the sentence. 

These are not show-stoppers, so if it's too much effort, I think we can ship it! 

![image](https://github.com/getodk/collect/assets/7871340/3d36701d-eaea-482b-8a0e-735862b4a3f7)

2023-07-20 11:24 UTC, grzesiek2010 commented
Yeah, we can do that it will be like:
![Screenshot_1689811033](https://github.com/getodk/collect/assets/3276264/57beb23e-a6cc-45b8-a3cc-797c02016ed5)

2023-07-20 15:02 UTC, alyblenkin commented
Looks great!

2023-07-25 13:17 UTC, seadowg requested changes
This does look like it makes changes so that the "Start new form" button is hidden for forms that still have unsent forms:

> Given I've created a Google Drive project in an earlier version of Collect
And I have unsent submissions (finalized or non finalized)
When I upgrade to and launch v2023.3
Then the Google Drive project is still there
And the "Start new form" button is gone in that project
And there is a banner with a warning about the project being deleted in the next release (text TBD)

2023-07-26 09:23 UTC, grzesiek2010 commented
@seadowg you are right I've missed the step with that button but now as I think about it I might have a better solution...
hiding the button wouldn't be perfect because starting new forms would be still possible using content providers. Taking that into account I think we should block starting new forms in `FormUriActivity` instead like we do in other cases where a form should not be started. Please take a look at the last commit and let me know if you agree https://github.com/getodk/collect/pull/5675/commits/b03fe755b804c64fced1c7eca754dad8a410bfa6

2023-08-03 14:50 UTC, grzesiek2010 commented
@seadowg I think you might have missed my question

2023-08-07 09:36 UTC, seadowg commented
> @seadowg I think you might have missed my question

No I got it. Just behind on replies. Will get to it soon hopefully!

2023-08-07 10:34 UTC, seadowg requested changes

2023-08-07 10:34 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
> -    fun whenGoogleUsedAsServer_sendsSubmissionToSheet() {
I think we should keep this test and use `copyInstance` (like in `InstancesAdbTest`) to set up the submission instead of deleting it.

2023-08-07 13:01 UTC, grzesiek2010 commented
@getodk/testers 
`v2023.1` was the last version where adding GD project was possible so I think you can use that version and then try to upgrade to this pr.
You can also try upgrading from `v2023.1` to `v2023.2` (where adding new GD projects was removed) and then this pr to make sure everything is fine but I would just perform one test like that and all the other cases verify upgrading directly `v2023.1` to this pr.

2023-08-07 14:18 UTC, dbemke commented
Can you attach app builds that allow accessing Google Drive and upgrading versions? I tried upgrading a released build (2023.1) from github to CircleCi  build from the PR - upgrade was impossible. I tried building my own app in AS (selfsigned, debug) and then "unable to make API calls"  so I'm not able to download forms from GD.

2023-08-08 12:17 UTC, grzesiek2010 commented
It doesn't work because you would need to [Enable the Google Drive API](https://github.com/getodk/collect#using-apis-for-local-development) but ok I can produce apk this will be faster:
https://drive.google.com/file/d/1q8hEWWWgD0FaE7JuyQe4RNX5Gapy63r9/view?usp=sharing

2023-08-08 13:41 UTC, dbemke commented
We installed the app (from the drive) but still API calls are unavailable.

2023-08-08 14:35 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
> -    fun whenGoogleUsedAsServer_sendsSubmissionToSheet() {
Right, done.

2023-08-08 15:56 UTC, seadowg approved these changes

2023-08-09 08:22 UTC, dbemke commented
I created a GD project in v2023.1.2 and upgraded to the PR build and when I tap "Download" (in a GD project) there is a crash.
![crashDownload](https://github.com/getodk/collect/assets/56479916/e8df52ea-3eb7-4398-bd27-84b01ae567d6)

2023-08-09 08:43 UTC, dbemke commented
Should a finalized form (in GD project upgraded to the PR) be editable? In "Ready to send" it's possible to view the form but not edit it.

2023-08-09 08:45 UTC, dbemke commented
There is a crash on sending (in "Ready to send", send selected) the finalized form in a GD project in the PR version.

2023-08-09 09:15 UTC, srujner commented
Both Crashes also appear on Android 13.

2023-08-09 12:43 UTC, grzesiek2010 commented
I was able to reproduce those crashes and it turns out it's a problem with code shrinking caused not by this pr but by upgrading Gradle about a month ago. The problem should be fixed.

> Should a finalized form (in GD project upgraded to the PR) be editable? In "Ready to send" it's possible to view the form but not edit it.

Yeah but for now it will work in this way (without editing). The change that introduce the grace period was merged to v2023.2.x but not to master and that's why in this pr editing finalized forms is not possible.

2023-08-09 12:44 UTC, grzesiek2010 commented
@lognaturel could you prepare a new apk for testing with the newest changes?

2023-08-16 08:08 UTC, dbemke commented
If the user tries to reconfigure a GD project with a QR code with GD project the server settings change to demo.getodk.org. In the PR version changing the type to GD is impossible so as a result the user is not able to send submissions any more. The issue is also present in 2023.1.2 but in that version it’s still possible to set the server as GD again.

**Steps to reproduce:**
1. Install 2023.1.2 and create a GD project.
2. Go to "Get Blank Form” and download a form.
3. Go to "Fill Blank form” and mark form as finalized, save and exit the form
4. (Update Collect - optional)
5. On other device create a GD project and create a QR code via reconfigure QR code.
6. On the first device scan a QR code with Google Drive project.
7. Check the Server settings.
8. Try to send the form

2023-08-16 09:24 UTC, grzesiek2010 commented
> If the user tries to reconfigure a GD project with a QR code with GD project the server settings change to demo.getodk.org. In the PR version changing the type to GD is impossible so as a result the user is not able to send submissions any more. The issue is also present in 2023.1.2 but in that version it’s still possible to set the server as GD again.

We didn't discuss such a case. Do you think we should block reconfiguring projects (if it is a GD project)? or maybe leave it as is and ignore this case? I'm somewhat torn but if I had to choose I would block reconfiguring, @seadowg @alyblenkin

2023-08-16 10:07 UTC, seadowg commented
> We didn't discuss such a case. Do you think we should block reconfiguring projects (if it is a GD project)? or maybe leave it as is and ignore this case?

Wow yeah that's an annoying scenario to get into to. I think I'd lean towards blocking as well.

2023-08-16 10:35 UTC, seadowg commented
Oh and just to add: if that's the only thing blocking this, I reckon we merge and create an issue rather than holding this PR any longer.

2023-08-16 12:07 UTC, dbemke commented
In the PR version there is a crash of the app on sending a form if the fallback submission URL is wrong.

2023-08-17 13:39 UTC, dbemke commented
We finished testing the PR. 
Scenarios from the acceptance criteria work as expected. 
Fixed issues will be tested after merging this PR and PR #5521

2023-08-17 13:54 UTC, merged