Show warning when editing finalized form
getodk/collect pull request #5681
Opened 2023-07-17 23:20 UTC by grzesiek2010

Closes #5680 

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-07-18 09:44 UTC, seadowg requested changes

2023-07-18 09:44 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
> +            .clickOKOnDialog()
This test will fail after October 1st. Like in the [previous PR], can you split out a before and after test?

Same goes for the `SendFinalizedFormPage` change.

2023-07-18 10:38 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
> +            .clickOKOnDialog()
It won't fail because the date is set manually to `OCTOBER_1st_2023_UTC - 1` so the test will always work like it is the end of September.

2023-07-18 14:02 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
> +            .clickOKOnDialog()
Ah my bad. The top of the test was obscured in Github's change log and I mistook it for a different one.

2023-07-18 14:02 UTC, seadowg approved these changes

2023-07-19 07:44 UTC, dbemke commented
After changing dark/ light mode to the opposite mode compared to the device's mode there are parts of the wrong mode applied. As far as I remember issues connected  with opposite modes won't be fixed but just to let you know that it exists also in the warning. If you decide that it's possible to fix, let me know and I'll figure out some reproducible steps.
![oppositeThemes](https://github.com/getodk/collect/assets/56479916/ff2701d0-af75-4f7d-bff5-a0888884ec2d)

2023-07-19 08:00 UTC, dbemke commented
This one is connected with the previous PR introducing the possibility to edit finalized form. I was away when it was introduced and I don't know if this case was discussed but the end page says "You will not be able to make edits once you finalize..." and now it's temporary possible so it might be a bit confusing.

![notAble ToEdit](https://github.com/getodk/collect/assets/56479916/a0367533-70aa-40dc-a988-5c9a345742e7)

2023-07-19 08:24 UTC, grzesiek2010 commented
> This one is connected with the previous PR introducing the possibility to edit finalized form. I was away when it was introduced and I don't know if this case was discussed but the end page says "You will not be able to make edits once you finalize..." and now it's temporary possible so it might be a bit confusing.

It is confusing but we decided that we should not change anything there. Even the snackbar action is `View` when you finalize but it allows you to edit forms.

2023-07-19 09:14 UTC, grzesiek2010 commented
> After changing dark/ light mode to the opposite mode compared to the device's mode there are parts of the wrong mode applied. As far as I remember issues connected with opposite modes won't be fixed but just to let you know that it exists also in the warning. If you decide that it's possible to fix, let me know and I'll figure out some reproducible steps.

It should be fixed.

@seadowg was there any reason not to use the `LocalizedActivity` in `FormUriActivity`?

2023-07-20 08:23 UTC, seadowg commented
> @seadowg was there any reason not to use the LocalizedActivity in FormUriActivity?

I guess it probably didn't have any UI when it was first made? Other than that, I can't think of a reason.

2023-07-21 15:05 UTC, srujner commented
**Tested with Success** alongside with @dbemke 

Verified on device with Android 10,13

Verified cases:

- Sending finalized Forms, Editing saved Forms, Viewing sent Forms, Deleting saved Forms;
- Form version and media updates;
- Viewing Snackbar after sending a form
- Sending forms with big-sized media
- All auto send options
- Forms being sent at the same time

2023-07-21 21:30 UTC, merged