Fix for #5358 Downloaded forms…
getodk/collect pull request #5699
Opened 2023-08-01 07:21 UTC by dimwight

Closes #5358?

#### What has been done to verify that this works as intended?

Tested manually including simulation of failed download. (In any case not possible to test formally for cancel attempt?)

#### Why is this the best possible solution? Were any other approaches considered?
In effect forces the expected behaviour. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Behaviour is now effectively as proposed. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-08-16 09:56 UTC, dimwight commented
Maybe @lognaturel's title change is somewhat misleading about the behaviour change proposed. Would 'Compel confirmation of result dialog...' be more descriptive?

2023-08-16 10:53 UTC, grzesiek2010 commented
> Maybe @lognaturel's title change is somewhat misleading about the behaviour change proposed. Would 'Compel confirmation of result dialog...' be more descriptive?

The title has been changed according to the expected solution described in the issue but this pr does something else. It blocks closing the dialog after clicking out of its area instead of navigating back to the main menu.

2023-08-16 10:54 UTC, grzesiek2010 requested changes
As in the comment above this pr does not solve the issue in the way we expected.

2023-08-16 14:30 UTC, lognaturel commented
Ahh, interesting! Just goes to show the value of a descriptive pull request title. 😊 We do use these for release notes so it's important that they describe the actual behavior introduced. It's also helpful in review to have a short summary of what the PR intends to do.

2023-08-17 14:03 UTC, dimwight commented
> It's also helpful in review to have a short summary of what the PR intends to do.

Indeed, now updated above to show my workings in more detail.

2023-09-12 09:28 UTC, seadowg commented
@dimwight we'd still the user to be able to dismiss the dialog by tapping outside it, we just want that dismiss behaviour to also return them to the main menu like it describes in the issue. I understand that the behaviour you've added here is arguably the same end state, but it does prevent the user from being able to dismiss the dialog as easily as they can now.

2023-09-13 14:50 UTC, dimwight commented
I can't help feeling this approach clashes with the usual semantics* of tapping outside a dialog:

- Responsive (A) - clears the dialog and redisplays the underlying screen.
- Unresponsive (B) - the dialog is blocking and requires interaction. 

An example of A is the current Download Form screen, where the screen is redisplayed without being updated.

B is what  happens in the Ready to Send screen (though A might be more appropriate since clearing the blocking dialog redisplays the underlying screen). 

We definitely don't want A, so B seems the natural alternative for Download Form. 

On the other hand the suggested response of clearing the dialog but not redisplaying the underlying screen, jumping instead to the main menu, arguably contravenes the principle of least surprise. 

Forgive me for splurging a bit on this, but I have given it quite a lot of thought. 

*I'm not sure semantics is the right word, but I can't think of a better one.

2023-10-04 10:30 UTC, seadowg commented
> I can't help feeling this approach clashes with the usual semantics* of tapping outside a dialog

I do actually agree with the points you make here. Nevertheless, currently the "OK" button in the dialog does move the user back to the Main Menu, and I think there's a good argument for keeping that and tapping outside the dialog consistent (as the user isn't actually agreeing to something with "OK"). It would be nice to change that behaviour (while keeping it consistent), but there will be users that will have been using Collect for 10+ years that will be very used to setting up possible 100s of devices at a time with this behaviour in place.

2023-11-22 09:58 UTC, seadowg commented
I'm going to mark this as a draft and close it as it's been inactive for over a month. Feel to free to reopen if you get started on it again @dimwight!

2023-11-22 09:59 UTC, closed without merging