Remove grace period restriction from editing finalized forms
getodk/collect pull request #5717
Opened 2023-08-28 11:49 UTC by seadowg

- Update translations (#5664)
- Fix date format in translation
- Add test to check date formats parse correctly
- Add a note about adding to the test
- Rename test
- Show broken translation on fail
- Added tests
- Allow editing finalized forms saved before October 1st 2023 UTC
- Added new logs
- Fixed tests
- Fix/remove broken format strings
- Catch RuntimeExceptions in validateAnswers method
- Added tests
- Added separate tests for the grace period
- Protect against onResume running in MainMenuActivity during crash flow
- Assert on started activity
- Use ActivityController properly
- Revert "Do not mark forms as failed to send before sending"
- Fixed displaying snackbar for autosend
- Add failing test in FormUriActivityTest
- Display a warning when editing finalized forms
- Fixed tests
- Added logs
- Updated the message
- FormUriActivity should extend LocalizedActivity
- Update string
- Update translations
- Fix failing date format strings
- Add Arabic from Google Translate
- Add Swahili from Google Translate
- Translate grace period message in top 8 languages
- Add back string needed for connected tests
- Add log when showing crash report
- Always allow finalized forms to be edited
- Edit string for new finalize behaviour

2023-08-28 12:56 UTC, seadowg commented on strings/src/main/res/values/strings.xml
> +    <string name="edit_finalized_form_warning">In later releases, you will not be able to edit finalized forms. Save forms as draft to edit them later.\n\nYou can check for errors in a draft form by
I'm not a big fan this message. Any ideas for a better one @lognaturel?

2023-08-28 19:40 UTC, grzesiek2010 requested changes

2023-08-28 19:40 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceExt.kt
>  fun Instance.canBeEditedWithGracePeriod(settingsProvider: SettingsProvider): Boolean {
This method should be renamed or even merged with the one above.

2023-08-29 21:16 UTC, grzesiek2010 approved these changes

2023-08-30 14:52 UTC, dbemke commented
#### Problem description
A finalized form can be saved as a draft again when accessed via Ready to send. Afterwards for a moment it’s possible to send the form or edit it again from Ready to send (while it’s really a draft).
#### Steps to reproduce the problem
1. In Collect settings auto send is set to off.
2. Go to a form and finalize it.
3. Go to Ready to send and open the form.
4. In the end page of the form, tap Save as draft.
5. When moved to Ready to send list, quickly select the form and send it (or try to open it and edit it again).
#### Other information
The issue also occurs in the v2023.2.3. In the master version 602cac5a61af060b50d02c3a90e9e17d47192b09 editing finalized forms is not allowed so the issue is impossible to reproduce.

2023-08-30 14:57 UTC, dbemke commented
When a finalized form is edited via Ready to send it’s possible to tap Save as draft in the exit dialog. The changes are saved but the form stays in Ready to send.
#### Steps to reproduce the problem
1. In Collect settings auto send is set to off.
2. Go to a form and finalize it.
3. Go to Ready to send and open the form.
4. Tap the device back button.
5. In the dialog tap Save as draft.
#### Other information

The issue also occurs in the v2023.2.3.

2023-08-31 08:32 UTC, dbemke commented
The first issue is fixed. The second issue is still present but I don't know if the form should be moved from Ready to send to draft in that case.

2023-08-31 08:35 UTC, dbemke commented
After editing a finalized form the subtext in Ready to send is a bit misleading. The subtext shows the date and time when the form was finalized. 

Steps to reproduce:
1. In Collect settings auto send is set to off.
2. Go to a form and finalize it.
3. Go to Ready to send and open the form.
4. Edit some answers.
5. Tap the save button (floppy disc).
6. Tap the device and discard changes.

The changes are saved but the subtext isn’t changed (Finalized with the date and time of the first finalization). If you enter the form and tap the device back button, in the exit dialog there is information that the form was saved/edited and the new date and time is present.
If in step 6 in the exit dialog the user taps Save as draft the date and time is updated in the subtext but it’s still Finalized.


![FinalizedSubtextTime](https://github.com/getodk/collect/assets/56479916/55363655-a5db-4cb1-975a-c21fd45800c2)

2023-08-31 09:30 UTC, seadowg commented
> When a finalized form is edited via Ready to send it’s possible to tap Save as draft in the exit dialog. The changes are saved but the form stays in Ready to send.

> After editing a finalized form the subtext in Ready to send is a bit misleading. The subtext shows the date and time when the form was finalized.

I don't think either of these are critical, but they do make everything confusing. It seems like both are consequence of a hangover of the old world where finalisation was less "final". When you hit the new "Save as draft" button on the end screen, Collect explicitly saves the form as a draft (the "incomplete" status) whereas for the floppy disk and the "Save as draft" button in the quit dialog, it will save the form as finalised if the form is already finalised. This hadn't really come up before, because it doesn't matter if you can't edit finalized forms (and the weirdness must have been missed the first time we added the grace period).

I think that we should remove the extra "intelligence" on the floppy/quit dialog save buttons and just have them always save the form as a draft leaving the only way to save a finalised form and keep it finalised is to hit "Finalize" itself. This introduces a bit of disruption to people that edit finalized forms and then immediately send them as they'll have to actually hit "Finalize", but I think the current situation allows for very mixed messaging as you're able "Save as draft" and then immediately send. I think the only alternative (other than keeping the current behaviour), would be to add an extra "Finalize" button to the quit dialog and I'm not sure how we'd deal with the floppy button. I'll go ahead and make the change and we can revert if it's not something that we're agreed upon (cc @grzesiek2010 and @lognaturel)

> The changes are saved but the subtext isn’t changed (Finalized with the date and time of the first finalization). If you enter the form and tap the device back button, in the exit dialog there is information that the form was saved/edited and the new date and time is present.

I don't think we'll want to add a specific piece of text for quitting a form that was finalised as we're still going to be taking the ability to edit a finalised form away later. "Last saved" isn't innaccuracte so I think it's ok for the moment. I think making the changes I've suggest above should make the scenario less confusing.

2023-08-31 10:12 UTC, seadowg commented
@dbemke I've made changes as described!

2023-08-31 10:13 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
> +                saveForm(false, false, null, true);
This was a super easy change as the tests already describe the desired behaviour. I just had to get rid of the extra untested logic

2023-08-31 10:18 UTC, grzesiek2010 commented
> I think that we should remove the extra "intelligence" on the floppy/quit dialog save buttons and just have them always save the form as a draft leaving the only way to save a finalised form and keep it finalised is to hit "Finalize" itself. This introduces a bit of disruption to people that edit finalized forms and then immediately send them as they'll have to actually hit "Finalize", but I think the current situation allows for very mixed messaging as you're able "Save as draft" and then immediately send. I think the only alternative (other than keeping the current behaviour), would be to add an extra "Finalize" button to the quit dialog and I'm not sure how we'd deal with the floppy button. I'll go ahead and make the change and we can revert if it's not something that we're agreed upon (cc @grzesiek2010 and @lognaturel)

to me, that solution would be ok. Still confusing a little bit but it is what it is I would rather avoid adding new buttons for finalization.

2023-08-31 11:03 UTC, dbemke commented
After the fix forms are moved to Drafts. The only thing is the scenario below (save button + discard changes) in which after those steps the user is moved to Ready to send view and the form is still there (for a moment before going back to the main menu - like in the first issue) and it's possible to send it (although it's a draft).

Steps to reproduce:
1. In Collect settings auto send is set to off.
2. Go to a form and finalize it.
3. Go to Ready to send and open the form.
4. Edit some answers.
5. Tap the save button (floppy disc).
6. Tap the device and discard changes.
7. When moved to the Ready to send list, try to send the form.

2023-08-31 12:16 UTC, seadowg commented
> The only thing is the scenario below (save button + discard changes) in which after those steps the user is moved to Ready to send view and the form is still there (for a moment before going back to the main menu - like in the first issue) and it's possible to send it (although it's a draft).

Good find! Not sure why we end up on "Ready to send" instead of the Main Menu there, but will fix that.

2023-08-31 13:11 UTC, seadowg commented
@dbemke that should be fixed now!

2023-09-01 13:08 UTC, dbemke commented
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- editing finalized form after the 30th of October
- issues mention in the PR are fixed
- changing finalized forms to drafts (forms with validation and audit logs)
- moving backwards not allowed
- all auto send options
- validation upon forward swipe/ defer validation until finalized
- killing the app after tapping the save button in a finalized form
- editing finalized form accessed via the form map in Start new form
- editing finalized form accessed via a snackbar
- trying to edit a form with a „sending failed” status
- subtexts in Ready to send

2023-09-01 13:10 UTC, srujner commented
**Tested with Success!**

Verified on device with Android 13

2023-09-01 13:49 UTC, merged