Removed Stamen maps
getodk/collect pull request #5822
Opened 2023-11-06 09:12 UTC by grzesiek2010

Closes #5806

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-11-08 16:13 UTC, seadowg requested changes

2023-11-08 16:13 UTC, seadowg commented on settings/src/main/java/org/odk/collect/settings/ODKAppSettingsMigrator.java
> +                translateValue("stamen").toValue("osm").forKey(KEY_BASEMAP_SOURCE)
This and the test should probably use the constant for `"osm"`.

2023-11-09 08:50 UTC, grzesiek2010 commented on settings/src/main/java/org/odk/collect/settings/ODKAppSettingsMigrator.java
> +                translateValue("stamen").toValue("osm").forKey(KEY_BASEMAP_SOURCE)
Done.

2023-11-09 09:38 UTC, seadowg approved these changes

2023-11-14 14:59 UTC, dbemke commented
What is the expected in this case? I created (via reconfigure QR code) a QR code in 2023.3.0 of the demo project with Stamen maps. I installed Collect with the PR version (build in AS- with maps available) and added a new project by scanning the created QR code. The result in the PR version is that Google maps are source of maps.
So what is the default map instead of Stamen maps when there is an app with all maps are available (apk built in Android Studio) and an app without all token for maps (CircleCi apk- this changes Stamen to Google and Google to OSM as Google in not available?)?

2023-11-14 15:22 UTC, grzesiek2010 commented
> What is the expected in this case? I created (via reconfigure QR code) a QR code in 2023.3.0 of the demo project with Stamen maps. I installed Collect with the PR version (build in AS- with maps available) and added a new project by scanning the created QR code. The result in the PR version is that Google maps are source of maps.
So what is the default map instead of Stamen maps when there is an app with all maps are available (apk built in Android Studio) and an app without all token for maps (CircleCi apk- this changes Stamen to Google and Google to OSM as Google in not available?)?

as long as Google Maps are available I would say it's not a big deal although it was supposed to use OSM... could you give it a try now?

2023-11-16 10:09 UTC, dbemke commented
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- #5806
- Stamen maps aren’t available
- adding a project and reconfiguring a project with a QR code with Stamen maps
- importing a QR code with Stamen maps
- updating Collect with a project w Stamen maps
- resetting a project in which Stamen maps were in settings before migrating to OSM

2023-11-16 10:09 UTC, srujner commented
**Tested with Success!**

Verified on a device with Android 13

2023-11-16 11:32 UTC, merged