Finish activity when the dialog is canceled
getodk/collect pull request #5873
Opened 2023-12-13 15:23 UTC by grzesiek2010

Closes #5872 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2023-12-14 12:53 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
> +    fun `The activity should be finished after clicking the back button when an error dialog is displayed`() {
Why do we need this test when all the other tests now assert on the cancellation behaviour?

2023-12-14 12:53 UTC, seadowg requested changes
Why do we need this test when all the other tests now assert on the cancellation behaviour?

2023-12-14 12:59 UTC, grzesiek2010 commented
> Why do we need this test when all the other tests now assert on the cancellation behaviour?

All the existing tests verified clicking the cancel button but the new one pressing the back button.

2023-12-14 15:17 UTC, seadowg approved these changes

2023-12-14 15:17 UTC, merged

2024-01-05 11:16 UTC, srujner commented
**Tested with Success!**

Verified on device with Android 10,12,13

- Issue #5872 is no longer reproducing;