Rework the widgets that still use deprecated addAnswerView method
getodk/collect pull request #5886
Opened 2023-12-23 23:35 UTC by grzesiek2010

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-02-05 13:34 UTC, seadowg requested changes
Loving this! I've spotted that we only have one use left of `createSimpleButton` (in `ExStringWidget`). Could we get rid of that as well?

2024-02-05 13:34 UTC, seadowg commented on collect_app/src/main/res/layout/annotate_widget.xml
> +        style="?materialButtonStyle"
This (and the other buttons in this PR) should use `?widgetButtonQuestionWidgetStyle` I think?

2024-02-29 15:57 UTC, grzesiek2010 commented on collect_app/src/main/res/layout/annotate_widget.xml
> +        style="?materialButtonStyle"
Right, fixed.

2024-02-29 15:57 UTC, grzesiek2010 commented
> Loving this! I've spotted that we only have one use left of createSimpleButton (in ExStringWidget). Could we get rid of that as well?

Right, fixed.

2024-03-08 11:00 UTC, seadowg approved these changes

2024-03-08 11:00 UTC, merged

2024-03-11 15:02 UTC, dbemke commented
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- buttons in widgets
- regression checks in the image widgets,the ranking widget,the video widget, the likert widget,text widgets

2024-03-11 15:11 UTC, srujner commented
**Tested with Success!**

Verified on device with Android 13