Fixed marking converted projects as old GD projects
getodk/collect pull request #5909
Opened 2024-01-11 22:08 UTC by grzesiek2010

Closes #5903

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-01-16 10:11 UTC, seadowg requested changes
An alternative solution I think would be worth considering is to add a test in `ProjectsRepositoryTest` (the "contract" test) to cover the difference in behaviour between the two implementations and then get that passing. Then you can continue to use the fake rather than the real implementation in tests. 

What do you think?

2024-01-17 12:13 UTC, grzesiek2010 commented
> An alternative solution I think would be worth considering is to add a test in ProjectsRepositoryTest (the "contract" test) to cover the difference in behaviour between the two implementations and then get that passing. Then you can continue to use the fake rather than the real implementation in tests.
What do you think?

I don't think the bug we had was something I could test using `ProjectsRepositoryTest`. The problem was that `isOldGoogleDriveProject` was a variable that we were able to change and assume it updates the saved project no matter if it's stored using shared prefs or a list in memory (`InMemProjectsRepository`), of course it didn't work with shared prefs. I've updated `isOldGoogleDriveProject` so that now it's val and I think we can revert the changes in tests.

2024-01-17 13:08 UTC, seadowg approved these changes

2024-01-17 13:08 UTC, merged

2024-01-23 14:13 UTC, dbemke commented
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- the banner is displayed correctly
- upgrading with a GD project with and without drafts and finalized forms
- resetting the project after upgrading
- trying to reconfigure an upgraded GD project with a QR code with an old GD project

2024-01-23 14:15 UTC, srujner commented
Tested with Success!

Verified on a device with Android 13