Apply M3 styling to user identity and change reason text fields
getodk/collect pull request #6019
Opened 2024-03-16 19:45 UTC by grzesiek2010

Closes #5949 

#### Why is this the best possible solution? Were any other approaches considered?
I've decided to create a new style for `TextInputLayouts` to share the common attributes with custom values. For now, it's only the background color but it might be something else in the future too.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please just confirm that the text fields (in text questions,  user identity, and change reason) have the same background color.

#### Do we need any specific form for testing your changes? If so, please attach one.
I've used: 
[audit.xlsx](https://github.com/getodk/collect/files/14625036/audit.xlsx)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-03-22 14:16 UTC, seadowg requested changes
It looks like how these are styled has just changed with the new tonal colors (like we had to deal with in the dialogs). The Material Components docs have been updated [here](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md). 

We shouldn't need a custom style (and can just use `?attr/textInputFilledStyle`), but that will mean we end up using our `colorSurfaceContainerHighest` for the background resulting in a text field like this:

<img width="329" alt="Screenshot 2024-03-22 at 14 14 44" src="https://github.com/getodk/collect/assets/556280/abd7109c-0732-4a3e-81ef-ddaf820719e2">

What do you think @alyblenkin? I'm definitely biased towards sticking to the way the tonal palette is applied to components, so if this doesn't seem ok we could tweak our container colors again.

2024-03-22 15:03 UTC, alyblenkin commented
> What do you think @alyblenkin? I'm definitely biased towards sticking to the way the tonal palette is applied to components, so if this doesn't seem ok we could tweak our container colors again.

Good spot! Yes, let's tweak the colours and get this right.

2024-03-23 08:54 UTC, grzesiek2010 commented
@alyblenkin so what color do you think we should use? The one we currently use in text fields used in text questions? Or maybe you like the new blue one (see example above)?

2024-03-25 15:12 UTC, alyblenkin commented
@grzesiek2010 I think we should keep the same grey for the text field as before, but that means we need to shift the surface colours. I think the grey would become our new surface low? @seadowg Do you think it might be easier to jump on a call and tweak the colour?

2024-03-25 16:00 UTC, seadowg commented
@grzesiek2010 just had a quick call to revise the colors we'd looked at the other day (not realising text inputs are meant to use "highest"). Let's set `colorSurfaceContainerHighest` to `#f2f2f2` in light mode (and leave it as-is for dark). We can then just use `?textInputFilledStyle` for the text inputs instead of needing a custom style.

2024-03-25 22:49 UTC, grzesiek2010 commented
> @grzesiek2010 just had a quick call to revise the colors we'd looked at the other day (not realising text inputs are meant to use "highest"). Let's set colorSurfaceContainerHighest to #f2f2f2 in light mode (and leave it as-is for dark). We can then just use ?textInputFilledStyle for the text inputs instead of needing a custom style.

Ok but that will change the color of some other components for example the banner in the form end view. Is that ok or we would need to fix it?:
| Before | After |
| ------------- | ------------- |
| ![Screenshot_1711406204](https://github.com/getodk/collect/assets/3276264/a06bab35-0a68-4112-a9f0-72db68ed2bb1) | ![Screenshot_1711406221](https://github.com/getodk/collect/assets/3276264/b0308456-484d-4db6-a215-fa2f24424ed4) |

2024-03-25 23:16 UTC, alyblenkin commented
@grzesiek2010 We discussed this one when we paired on it, and I think that's okay! We want to use the new M3 styling rather than creating special cases as we did for this one. I also believe we will remove this message at one point or rethink it if we decide to allow edits on finalized/sent forms.

2024-03-26 13:09 UTC, seadowg approved these changes

2024-03-26 13:09 UTC, merged

2024-03-27 09:14 UTC, dbemke commented
The "No errors" pill became also gray. Is it expected?
![gray](https://github.com/getodk/collect/assets/56479916/f247a161-00f5-4005-ba99-f1c506dadee0)

2024-03-27 09:51 UTC, dbemke commented
The microphone icon changed to gray in the audio widget. Is it expected?
![audio](https://github.com/getodk/collect/assets/56479916/e8105e64-5649-4a49-bf8a-56bb70938916)

2024-03-27 10:34 UTC, dbemke commented
I filed separate issues with colors that changed.

2024-03-28 14:27 UTC, WKobus commented
**Tested with success!**
Verified on device with Android 11
**Verified cases:**

- Issue https://github.com/getodk/collect/issues/5949 does not occur
- Check of widget and dialogs across the app
- Dark and light mode
- Opposite theme on app and device
- Forms with Identify User dialog

2024-03-28 14:27 UTC, dbemke commented
**Tested with success!**

Verified on device with Android 10,14

2024-03-28 14:27 UTC, srujner commented
**Tested with success!**

Verified on device with Android 12,13