Disable maxWidth attribute in the bottom sheet
getodk/collect pull request #6067
Opened 2024-04-03 14:51 UTC by grzesiek2010

Closes #6066 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-04-04 09:54 UTC, seadowg requested changes
Are you able to file an issue at https://github.com/material-components/material-components-android about there not being a good way to remove the max width (as suggested in the Material Guidelines)? It doesn't feel like something we should have to hack around.

2024-04-04 09:54 UTC, seadowg commented on geo/src/main/res/layout/selection_map_layout.xml
> +        android:maxWidth="10000dp"
Could we do this programmatically and use `Integer.MAX_VALUE` instead? It [looks like](https://stackoverflow.com/questions/28205014/android-remove-max-width-attribute-from-text-view) that's what Android does internally.

I'd also be keen to make it more explicit what's going on here. We already have our own implementation of `BottomSheetBehavior`, so we could add a method like `setMaxWidth(width: Int?)` that just "disables" the max width on the underlying (actual) `BottomSheetBehavior` (by setting the max width to the `MAX_VALUE`).

2024-04-08 10:05 UTC, grzesiek2010 commented on geo/src/main/res/layout/selection_map_layout.xml
> +        android:maxWidth="10000dp"
Oh it looks like `android:maxWidth="@null"` disables it correctly so we don't to set that attribute with any big number like `10000` or `Integer.MAX_VALUE`.
When it comes to doing that programmatically... I've tried it and it didn't work but either way, I think doing that in XML (the layout file) is better.

2024-04-08 10:49 UTC, seadowg approved these changes

2024-04-08 10:50 UTC, merged

2024-04-09 11:42 UTC, dbemke commented
I was wondering if it was possible to reduce the amount of empty space at the top of the bottom sheet? In the horizontal view when there are properties added to a point, the bottom sheet covers a half of the screen which makes looking at/using the map quite difficult. Even if there is the "errors/no errors" pill there is a bit of empty space at the top of the bottom sheet (covering the map). I know it's not the part of the PR exactly but just wanted to know what you think about the horizontal view.
![verticalBottom](https://github.com/getodk/collect/assets/56479916/abab2e81-6f42-40b8-9fde-4bd5400bf06e)

2024-04-09 11:54 UTC, grzesiek2010 commented
> I was wondering if it was possible to reduce the amount of empty space at the top of the bottom sheet? In the horizontal view when there are properties added to a point, the bottom sheet covers a half of the screen which makes looking at/using the map quite difficult. Even if there is the "errors/no errors" pill there is a bit of empty space at the top of the bottom sheet (covering the map). I know it's not a part of the PR exactly but just wanted to know what you think about the horizontal view.

So much margin is added by default see examples from https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md
I don't know if we want to change it. What do you think @alyblenkin @seadowg?

2024-04-09 16:41 UTC, alyblenkin commented
It's not a great user experience! It's worth considering changing the default. Google Maps has a nice adjustment that makes viewing and interacting easier. I think we could go ahead with the default for now and add this as a separate issue, which we can prioritize later. What do you think @grzesiek2010 @seadowg?

<img width="1203" alt="Screenshot 2024-04-09 at 9 36 07 AM" src="https://github.com/getodk/collect/assets/7871340/1cfe5cf7-0ba8-4d82-8e4f-685d7cef19ab">

2024-04-09 19:20 UTC, grzesiek2010 commented
Sounds good.

2024-04-11 13:04 UTC, dbemke commented
**Tested with Success!**

Verified on devices with Androids: 10, 14

**Verified cases:**
- issue #6066 is fixed
- bottom sheet in the form map and select one from map forms
- errors/ no errors pill in the bottom sheet
- properties of a point in the bottom sheet
- landscape and portrait view
- dark and light mode

2024-04-11 13:06 UTC, WKobus commented
**Tested with Success!**

Verified on device with Android 11