Do not allow to mix 'thousands-sep' with 'masked'
getodk/collect pull request #6088
Opened 2024-04-12 09:49 UTC by grzesiek2010

Closes #6073 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-04-15 13:03 UTC, seadowg requested changes
> This pull request addresses three issues but only https://github.com/getodk/collect/issues/6072 is worth explaining. To me, it seems like an Android bug since only number questions were affected. It looks like moving the cursor needs to be delayed a little bit so I used the [post](https://github.com/getodk/collect/pull/6088/commits/caea28a0306b68c6f95b23b569bbc7c42dceaefe) method like in a few other places of the app.

These no `post` in the changes. Is there a commit missing perhaps? Or I guess this comment might be out of date.

2024-04-15 13:06 UTC, grzesiek2010 commented
> These no post in the changes. Is there a commit missing perhaps? Or I guess this comment might be out of date.

Yeah, it was the old version I forgot to update the description.

2024-04-15 15:24 UTC, seadowg requested changes
I think we should add tests for the changes to `WidgetAnswerText` here.

2024-04-18 21:47 UTC, grzesiek2010 commented
> I think we should add tests for the changes to WidgetAnswerText here.

Done.

2024-04-26 16:58 UTC, seadowg approved these changes

2024-04-26 16:59 UTC, merged

2024-05-09 14:11 UTC, WKobus commented
**Tested with Success!**

Verified on devices with Android 11

**Verified cases:**

- Listed issues no longer occur
#6072 
 #6073 
#6075, 
#6080 
- All question types with masked appearance
- Masked in field list
- Light and dark mode

2024-05-09 14:12 UTC, dbemke commented
**Tested with Success!**

Verified on devices with Android 10, 14