Fixed displaying saved forms to delete
getodk/collect pull request #6107
Opened 2024-04-24 10:43 UTC by grzesiek2010

Closes #6017 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-04-24 16:01 UTC, seadowg requested changes
It looks like there's some conflicts blocking this.

> I could have edited InstancesDataService by adding a new flow specifically for undelete instances (and read them from the repository) but:
>
> 1. This would make testing more difficult than what I did because I would need to rework the view model test completely so that it tests a real InstancesDataService object.
> 2. I'm not sure if exposing different flows for different scenarios (all instances, undelete instances, etc) is what we want to have in our data service. Maybe exposing just one like now is clearer.

Good points. I guess it's a trade off, if we expose different Flows/LiveData values for different "filters" over the data then there is definitely more complexity in the data service to manage this and more API to care about from clients. On the other hand, exposing "everything" and then filtering in memory will definitely be less efficient than pushing that work all the way to the DB. I think sticking with the least change for now (what you've done) is a good idea. If we do need to change it later once we're using the data service for all our lists, we'll be better informed to make that decision then.

2024-04-24 16:01 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/activities/DeleteFormsActivity.kt
> +                DeleteSavedFormListViewModel::class.java -> DeleteSavedFormListViewModel(
I'm not sure about this rename. I was envisioning that we'd be able to use `SavedFormListViewModel` in other places (like "Drafts") in the future. But, maybe it makes more sense to have this (`DeleteSavedFormListViewModel`) name now and rename in the future if we do end up generalising it?

2024-04-28 16:51 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/DeleteFormsActivity.kt
> +                DeleteSavedFormListViewModel::class.java -> DeleteSavedFormListViewModel(
Yeah, I thought that with the new changes that view model could not be shared but that's not true in Drafts as you said we would also need to filter out deleted forms. I've removed that change.

2024-04-29 15:57 UTC, seadowg approved these changes

2024-04-29 15:58 UTC, merged

2024-05-06 09:59 UTC, WKobus commented
**Tested with Success!**

Verified on device with Android: 11

**Verified cases:**

- Issue https://github.com/getodk/collect/issues/6017 does not occur
- Deleting blank / saved forms
- Deleting forms with different states
- Forms with auto delete
- Deleting forms while sending

2024-05-06 10:01 UTC, dbemke commented
**Tested with Success!**

Verified on device with Android: 10

2024-05-06 10:03 UTC, srujner commented
**Tested with Success!**

Verified on device with Android: 13