Collect 6131
getodk/collect pull request #6139
Opened 2024-05-16 19:12 UTC by grzesiek2010

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-05-20 12:42 UTC, seadowg requested changes
Just one small tweak here.

This is a really interesting change as it's the first time we've really had repos acknowledge each other (here `FormsRepository` knows about `SavepointsRepository`). I was initially unsure about how I felt about this, but it seems like it most accurately reflects how I think things **should** work: forms, instances and savepoints in a single DB allowing us to implement these kinds of features with `CASCADE` etc.

2024-05-20 12:42 UTC, seadowg commented on forms-test/src/main/java/org/odk/collect/formstest/FormsRepositoryTest.java
> +        Savepoint savepoint2 = new Savepoint(form.getDbId() + 1, null, "", "");
Probably a little bit safer to just create another form rather than doing ID manipulation here. Same goes for the other new tests that use this pattern.

2024-05-20 22:23 UTC, grzesiek2010 commented on forms-test/src/main/java/org/odk/collect/formstest/FormsRepositoryTest.java
> +        Savepoint savepoint2 = new Savepoint(form.getDbId() + 1, null, "", "");
Done.

2024-05-21 08:48 UTC, seadowg approved these changes

2024-05-21 08:49 UTC, merged

2024-05-23 11:31 UTC, WKobus commented
**Tested with Success!**

Verified on device with Android: 14

**Verified cases:**

- Issue #6131 no longer occur
- Deleting / soft deleting blank forms
- Deleting blank forms through forms folder
- Quick regression check on savepoints

2024-05-23 11:35 UTC, dbemke commented
**Tested with Success!**

Verified on device with Android: 10