Make managing project dependencies more consistent
getodk/collect pull request #6158
Opened 2024-05-28 12:53 UTC by seadowg

- **Rename class**
- **Make it simpler to construct ProjectDependencyModule**
- **Move new data classes to relevant packages**
- **Move ProjectDependencyFactory to projects module**
- **Cut down on boiler plate with an injected constructor**
- **Make FormSourceProvider implement ProjectDependencyFactory**

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-06-11 16:30 UTC, seadowg commented
I think it'd also be good to introduce a new convenience abstraction for building data services here. Something like:

```kotlin
abstract class DataService(private val appState: AppState) {

    fun <T> getData(key: String, default: T): Data<T> {
        return Data(appState, key, default)
    }
}

class Data<T>(private val appState: AppState, private val key: String, private val default: T) {
    fun get(qualifier: String? = null): Flow<T> {
        return appState.getFlow("$qualifier:$key", default)
    }

    fun set(value: T, qualifier: String? = null) {
        appState.setFlow("$qualifier:$key", value)
    }
}
```

2024-06-25 16:54 UTC, seadowg commented
@grzesiek2010 we probably want to wait on merging this until we've got the last release things in, but I'd like to get your initial thoughts.

2024-07-15 10:11 UTC, grzesiek2010 requested changes

2024-07-15 10:11 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/activities/DeleteFormsActivity.kt
> +        val projectDependencyProvider = projectDependencyModuleFactory.create(projectId)
This should be renamed `projectDependencyProvider` -> `projectDependencyModule`.

2024-07-15 10:11 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formmanagement/FormsDataService.kt
> +        val projectDependencyProvider = projectDependencyModuleFactory.create(projectId)
This should be renamed `projectDependencyProvider` -> `projectDependencyModule`.

2024-07-15 10:11 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt
> +        val projectDependencyProvider = projectDependencyModuleFactory.create(projectId)
This should be renamed `projectDependencyProvider` -> `projectDependencyModule`.

2024-07-15 10:11 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
> +    private val projectDependencyProvider = projectsDependencyModuleFactory.create("blah")
This should be renamed `projectDependencyProvider` -> `projectDependencyModule`.

2024-07-15 10:11 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/application/initialization/SavepointsImporterTest.kt
>      private val projectDependencyProvider = projectDependencyProviderFactory.create(project.uuid)
This should be renamed `projectDependencyProvider` -> `projectDependencyModule`.

2024-07-15 10:11 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
> +    ProjectDependencyModuleFactory projectDependencyProviderFactory();
This should be renamed `projectDependencyProviderFactory` -> `projectDependencyModuleFactory`.

2024-07-15 10:11 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
> +        it.save(ProjectKeys.KEY_AUTOSEND, AutoSend.WIFI_ONLY.getValue(application))
Why do we need this? It wasn't there before and it seems like the test passes without it.

2024-07-15 14:35 UTC, grzesiek2010 requested changes

2024-07-15 14:35 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/application/initialization/SavepointsImporterTest.kt
> +    private val projectDependencyProviderFactory = component.projectDependencyModuleFactory()
`projectDependencyProviderFactory` variables should be renamed to `projectDependencyModuleFactory` as well.

2024-07-15 15:39 UTC, grzesiek2010 approved these changes

2024-07-15 15:39 UTC, merged

2024-07-17 14:07 UTC, dbemke commented
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- sending, finalizing, saving forms as draft
- deleting forms
- adding duplicate projects
- adding different versions of a form
- regression checks in savepoints
- manually copying instances of a form to a project
- shortcuts
- testers intents app

2024-07-17 15:18 UTC, WKobus commented
**Tested with Success!**

Verified on a device with Android 14