Update STATE.md
getodk/collect pull request #6217
Opened 2024-06-20 15:18 UTC by seadowg

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-06-20 15:19 UTC, seadowg commented on docs/STATE.md
> +* Improving the `MapFragment` abstraction so more logic can be shared between the map engines
We're not actually doing this yet, but I really want to start.

2024-06-20 16:48 UTC, lognaturel approved these changes

2024-06-24 19:01 UTC, grzesiek2010 requested changes

2024-06-24 19:01 UTC, grzesiek2010 commented on docs/STATE.md
> +* Moving towards a ["data services"](data_services_architecture.pdf) oriented architecture that has emerged over time that uses AndroidX Architecture Components for the core of the UI (Fragment, View
`etc` should have a dot at the end: `etc.`

2024-06-24 19:01 UTC, grzesiek2010 commented on docs/STATE.md
> +* Questions are rendered using a view "framework" of implementations inheriting from `QuestionWidget` (which is documented at in [WIDGETS.MD](WIDGETS.md)) which are also used to store UI state during
Is `at in` correct in English? It's not my fist language but as far as I know, it should be just in.

2024-06-24 19:01 UTC, grzesiek2010 commented on docs/STATE.md
> +* The form hierarchy is rendered using `FormHierarchyActivity` which hasn't been seriously touched (at a code or design) level for a few years
There should be a comma before which: `...using FormHierarchyActivity, which...`

2024-06-25 08:45 UTC, seadowg commented on docs/STATE.md
> +* Moving towards a ["data services"](data_services_architecture.pdf) oriented architecture that has emerged over time that uses AndroidX Architecture Components for the core of the UI (Fragment, View
I didn't know that!

2024-06-25 08:47 UTC, seadowg commented on docs/STATE.md
> +* Questions are rendered using a view "framework" of implementations inheriting from `QuestionWidget` (which is documented at in [WIDGETS.MD](WIDGETS.md)) which are also used to store UI state during
No, that's a typo.

2024-06-25 09:18 UTC, grzesiek2010 approved these changes

2024-06-25 09:18 UTC, merged