Rework release planning details
getodk/collect pull request #6223
Opened 2024-06-21 15:16 UTC by seadowg

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-06-21 15:50 UTC, lognaturel approved these changes

2024-06-21 17:12 UTC, alyblenkin approved these changes

2024-06-24 07:53 UTC, srujner approved these changes

2024-06-24 07:54 UTC, dbemke approved these changes

2024-06-24 18:45 UTC, grzesiek2010 requested changes

2024-06-24 18:45 UTC, grzesiek2010 commented on README.md
> +3. The core team will then meet to trim work not that will not be included in the next release and pitch alternative things to work on
I think it should be ...`to trim work that will not be included`...

2024-06-25 09:17 UTC, grzesiek2010 approved these changes

2024-06-25 09:17 UTC, merged