Fixed updating layers on changing basemaps
getodk/collect pull request #6251
Opened 2024-07-04 09:38 UTC by grzesiek2010

Closes #6248 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-07-04 13:33 UTC, grzesiek2010 commented on maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPickerViewModel.kt
> +class OfflineMapLayersPickerViewModel(
Actually, I'm happy that we no longer keep the code that is not shared in the shared ViewModel. Not using a shared ViewModel for communication between fragments is also the direction we were thinking about in https://github.com/getodk/collect/pull/6243#discussion_r1662129936

2024-07-04 17:06 UTC, seadowg requested changes
I think this is heavily pointing us towards wanting a data service for layers that allows us to share reactive data between view models rather than sharing them between UI components or using Fragment results to nudge things to get updated. That's another thing to look at when we do #6198 I reckon (I'll make a note there) rather than holding up release.

For the moment though, could we not just fix this by calling `loadExistingLayers`  whenever we show the bottom sheet (in `OfflineMapLayersPicker#onAttach` for example). That feels like a smaller change. It'd mean refreshing on rotate as well, but I'm OK with the trade-off there.

We're also missing tests. I think the only option is to write something with `ActivityScenario` which feels like a bit of an undertaking (we need a test Activity in `debug` etc), so I'd also feel better about going ahead without tests with the smaller change.

2024-07-05 09:06 UTC, grzesiek2010 commented
> For the moment though, could we not just fix this by calling loadExistingLayers whenever we show the bottom sheet (in OfflineMapLayersPicker#onAttach for example). That feels like a smaller change. It'd mean refreshing on rotate as well, but I'm OK with the trade-off there.

I would prefer to have such a small change here too. The problem is that it will be called on every screen rotation. Do you think it's ok?

2024-07-08 08:27 UTC, seadowg commented
> I would prefer to have such a small change here too. The problem is that it will be called on every screen rotation. Do you think it's ok?

Yeah! I said that in the original comment, but maybe it wasn't clear. It'd definitely not be ideal, but I think gets us to a more "correct" place with less workarounds, risk and disruption to hold things up.

2024-07-08 09:03 UTC, grzesiek2010 commented
@seadowg I won't be available for the next ~3 hours. If there is something you would like to change here please feel free to do that.

2024-07-08 09:28 UTC, seadowg approved these changes

2024-07-08 09:28 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/preferences/screens/MapsPreferencesFragment.kt
> +        } else if (key == KEY_BASEMAP_SOURCE) {
It looks like there's no testing for anything in `onSettingsChanged` here. No need to block this - I'll just create an issue as a follow-up.

2024-07-08 09:29 UTC, seadowg commented
@getodk/testers I'll wait for manual testing to merge here just in case as there's a few changes here that aren't tested.

2024-07-08 14:29 UTC, WKobus commented
**Tested with Success!**

Verified on device with Android 14

Verified cases:
- Issue #6248 does not occur
- Adding vector layers
- Different map sources
- Regression check on offline layers
- Don't keep activities enabled
- No background processes

2024-07-08 14:29 UTC, srujner commented
**Tested with Success!**

Verified on device with Android 13

2024-07-08 15:07 UTC, merged