Add trunkVersion and branchId support
getodk/collect pull request #6276
Opened 2024-07-22 14:56 UTC by seadowg

- **Add getById to EntitiesRepository**
- **Spike out name query filter strategy for entities**
- **Use new funtion handler API**
- **Fix filter strategy returning results for non-entity queries**
- **Switch to using custom FormEntryController setup**
- **Add test for no matching entities case**
- **Add tests for unsupported expressions**
- **Switch to InstanceProvider for entities**
- **Make tests more realistic**
- **Add test for matching entity**
- **Replace partials when querying by ID**
- **Add getAllByProperty to EntitiesRepository**
- **Load lists up front to prevent StrictMode violations in hierarchy**
- **Add support for optimized property filters**
- **Pull out object for mapping entities to XPath queries**
- **Use data adapter for parsing as well**
- **Use constants for identifying entity attributes**
- **Remove extra function handler setup**
- **Remove use of deprecated method from CollectFormEntryControllerFactory**
- **Only create structure for first entity item**
- **Add trunkVersion**
- **Rename class**
- **Update trunk version when updating from list**
- **Update trunk version from form**
- **Update test forms for trunk version**

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-07-31 11:03 UTC, grzesiek2010 requested changes

2024-07-31 11:03 UTC, grzesiek2010 commented on entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
> +    fun `updateLocalEntitiesFromForm updates properties on update`() {
What kind of update is happening here?
You have properties `"prop" to "value"` in the original entity then you do the update and it's still the same.

2024-07-31 12:57 UTC, seadowg commented on entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
> +    fun `updateLocalEntitiesFromForm updates properties on update`() {
Yeah, that test makes no sense 😂. Let me have another look!

2024-07-31 15:01 UTC, grzesiek2010 approved these changes

2024-07-31 15:01 UTC, merged

2024-08-06 13:50 UTC, WKobus commented
**Tested with success**

Verified on device with Android 14

**Verified cases:**

- Create or update entity forms
- Regression check on entity forms
- Local entities disabled/enabled

2024-08-06 13:53 UTC, dbemke commented
**Tested with success**

Verified on device with Android 10