Fix memory leak when deleting project
getodk/collect pull request #6296
Opened 2024-07-30 15:27 UTC by seadowg

- **Make sure to use consistent admin settings in BaseAdminPreferencesFragment**
- **Create admin SettingsStore in fragment**
- **Remove unused Dagger inject**

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-08-29 08:42 UTC, grzesiek2010 requested changes

2024-08-29 08:42 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/preferences/screens/BaseAdminPreferencesFragment.java
> +    Settings adminSettings;
Those should be private I think.

2024-08-29 12:07 UTC, grzesiek2010 approved these changes

2024-08-29 12:07 UTC, merged

2024-08-30 11:51 UTC, WKobus commented
**Tested with Success!**

Verified on device with Android 10, 14

**Verified cases:**
- Issue #6280 does not occur
- Deleting big projects