Update markup and signature exit model with new styling
getodk/collect pull request #6300
Opened 2024-07-31 20:45 UTC by grzesiek2010

Closes #6117

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-08-19 12:37 UTC, seadowg requested changes

2024-08-19 12:37 UTC, seadowg commented on draw/src/main/java/org/odk/collect/draw/QuitDrawingDialog.kt
> +object QuitDrawingDialog {
I like this having a separate implementation from `QuitFormDialog` as it feels more like they **happen** to be the same as opposed to them always being the same.

2024-08-19 12:37 UTC, seadowg commented on draw/src/main/java/org/odk/collect/draw/QuitDrawingDialog.kt
> +        binding.discardChanges.setOnClickListener {
I can't see any test coverage for these 3 buttons - I'm guessing that's an existing problem though. This is probably a good opportunity to add it (maybe as part of a `DrawActivityTest`).

2024-08-19 12:37 UTC, seadowg commented on draw/src/main/res/layout/quit_drawing_dialog_layout.xml
> +            android:layout_marginTop="@dimen/margin"
This always gets me! Should be `margin_standard`. `margin` is part of the color picker library.

2025-09-19 10:10 UTC, grzesiek2010 commented on draw/src/main/java/org/odk/collect/draw/QuitDrawingDialog.kt
> +        binding.discardChanges.setOnClickListener {
Done.

2025-09-19 13:22 UTC, seadowg approved these changes

2025-09-19 13:23 UTC, merged

2025-09-26 11:55 UTC, WKobus commented
**Tested with success**

Verified on Android 16

**Verified cases:**

- Exit dialogs in Signature, Draw and Annotate widgets
- Dark and light theme
- Different font sizes
- RTL language
- Regression checks in Signature, Draw and Annotate widgets

2025-09-26 11:56 UTC, dbemke commented
**Tested with success**

Verified on Android 10