Fixed displaying required questions with audio attachments
getodk/collect pull request #6332
Opened 2024-08-09 18:50 UTC by grzesiek2010

Closes #6327 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-08-15 12:39 UTC, seadowg requested changes

2024-08-15 12:39 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.kt
> +    fun `requiredQuestionIsMarkedWithAnAsterisk`() {
This doesn't need backticks

2024-08-15 12:39 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.kt
> +            .assertText("* Required question")
We've already got a helper for this assertion: you can use `assertQuestion("Required question", isRequired = true)`. You can do the same with `swipeToNextQuestion` as well.

2024-08-22 09:19 UTC, seadowg approved these changes

2024-08-22 09:19 UTC, merged

2024-08-23 11:30 UTC, dbemke commented
**Tested with Success!**

Verified on a device Android 10

**Verified Cases:**
- issue #6327 doesn't occur
- required questions with different media
- forms with required questions and styling examples
- regression checks in forms with required

2024-08-23 11:32 UTC, WKobus commented
**Tested with Success**

Verified on device with Android 14