Guard against incorrect paths
getodk/collect pull request #6340
Opened 2024-08-13 16:09 UTC by seadowg

- **Fixed applying the masked appearance**
- **Fixed tests**
- **Added new tests**
- **Let Errors crash the app during form loading**
- **Added failing tests**
- **Fixed hiding error in external widgets**
- **Fixed passing the SavepointsRepositoryProvider to viewModelFactory**
- **Fixed passing dependencies to BackgroundLocationHelper**
- **Added a failing test**
- **Sanitize media file names**
- **Removed support for InstanceProvider#update**
- **Fixed tests**
- **Improve sanitizing file names**
- **Removed unused analytics event**
- **Guard against incorrect paths**

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-08-14 08:26 UTC, grzesiek2010 requested changes

2024-08-14 08:26 UTC, grzesiek2010 commented on shared/src/main/java/org/odk/collect/shared/PathUtils.kt
> +            throw SecurityException()
I was initially considering checking this only during form upload, but we can proceed with this approach. However, I believe we should at least include another test to confirm that the exception is triggered during form upload. Right now, we know this method is used in that context, but it's not guaranteed. There's a risk that we might refactor the code and overlook this exception that should be thrown.

2024-08-14 09:55 UTC, grzesiek2010 approved these changes

2024-08-14 09:55 UTC, merged

2024-08-16 15:44 UTC, WKobus commented
**Tested with Success**

Verified on device with Android 14,10

**Verified cases:**
- Saving and sending different forms
- Autosend on/off