Show scale on map
getodk/collect pull request #6379
Opened 2024-08-28 09:57 UTC by grzesiek2010

Closes #6233

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-08-29 12:01 UTC, seadowg requested changes
I'm actually thinking we shouldn't bother with the scale bar for Google Maps given it means pulling in another dependency - especially one that's not been updated for 4 years. Let's just do the OSM/Mapbox changes for now, and we can discuss whether adding scale to Google Maps is worth the risk of us maintaining it in the future in our next sync.

2024-09-04 09:53 UTC, grzesiek2010 commented
According to our discussion with @lognaturel and @seadowg I've pulled out https://github.com/pengrad/MapScaleView into the `google-maps` module. I think it can be a part of that module instead of being a separate one since it's used only with google maps.

2024-09-04 13:16 UTC, seadowg approved these changes

2024-09-06 11:11 UTC, WKobus commented
**Tested with Success**

Verified on device with Android 14

**Verified cases:**
- Scale bars in different geo questions / form map
- All map sources
- Offline layers
- Regression check on maps
- Rotating device
- Don't keep activities on
- No background processes

2024-09-09 14:35 UTC, srujner commented
**Tested with Success**

Verified on device with Android 10

2024-09-09 14:44 UTC, merged