Include DynamicPreloadExtra in formDef only if a form contains search or pulldata
getodk/collect pull request #6448
Opened 2024-10-09 13:37 UTC by grzesiek2010

Closes #6447

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-10-11 14:55 UTC, seadowg requested changes

2024-10-11 14:55 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/dynamicpreload/DynamicPreloadParseProcessorTest.kt
> +    fun `usesDynamicPreload is null when xpath does not contain pulldata`() {
These tests should probably be renamed so they read like "DynamicPreloadExtra is..." instead of referencing the now gone `usesDynamicPreload`.

2024-10-11 14:55 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataUseCasesTest.kt
> +    fun `create() does not create a db file if the FormDef has not a DynamicPreloadExtra()`() {
`...if the `FormDef` does not have a...`

2024-10-15 11:43 UTC, seadowg approved these changes

2024-10-15 11:53 UTC, merged

2024-10-18 11:24 UTC, WKobus commented
**Tested with Success**

Verified on device with Android 14

**Verified cases:**

- Forms with search and pulldata
- Pulldata in entity forms

2024-10-18 11:25 UTC, dbemke commented
**Tested with Success**

Verified on device with Android 10