[#6439] Fix UI of repeat labels
getodk/collect pull request #6459
Opened 2024-10-16 11:07 UTC by karntrehan

Closes #6458 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No regressions. Tests have been added. Need translations though.

#### Do we need any specific form for testing your changes? If so, please attach one.
Added in the code.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below. 
Not applicable

#### Before submitting this PR, please make sure you have:
- [X] added or modified tests for any new or changed behavior
- [X] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass - Some are failing here without my changes as well
- [X] added a comment above any new strings describing it for translators - NA
- [X] added any new strings with date formatting to `DateFormatsTest` - NA
- [X] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).  - NA
- [X] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-10-16 11:10 UTC, karntrehan commented on strings/src/main/res/values/strings.xml
> +    <string name="add_another_question">Add another?</string>
Not sure how translations are done. Did not see it in the readme also. Kindly advice.

2024-10-16 12:07 UTC, karntrehan commented
Tried to look at the style guide mentioned here https://github.com/getodk/collect/blob/e828193dca70ecf0f9b299c641df0177d7e7c117/docs/CONTRIBUTING.md?plain=1#L44 but the link seems to be broken.

2024-10-16 15:30 UTC, alyblenkin commented
The UI looks good to me. I wait for the others to chime in on implementation.

2024-10-21 05:43 UTC, karntrehan commented
Hie @lognaturel just following up on this PR.

2024-10-21 17:57 UTC, lognaturel commented
Thanks, @karntrehan! We haven't forgotten about it and will try to get to it this week. In general, our review capacity is limited so we'll have to think about the best way to get you involved. Are there some specific things that you/Samagra are hoping to get into Collect or are you looking to help out generally?

2024-10-22 06:04 UTC, karntrehan commented
Thank you for the reply @lognaturel. I understand the limited bandwidth and the busy schedules. Please take your time.

> Are there some specific things that you/Samagra are hoping to get into Collect or are you looking to help out generally?

It is just me, in my personal capacity, wanting to contribute back to the amazing product I have used daily and in any capacity I can. Maybe I can keep getting a deeper knowledge of the system and also help with PR reviews in the future. Please feel free to tag me in issues you think I can help fix. I have some time kept aside for contributions to ODK. 

Looking forward :)

2024-10-22 16:59 UTC, lognaturel commented
Thanks so much, @karntrehan! Excited to see what we can do together.

2024-10-23 13:03 UTC, seadowg requested changes

2024-10-23 13:03 UTC, seadowg commented on README.md
> +	adb push my_form.xml /sdcard/Android/data/org.odk.collect.android/files/formsprojects/DEMO/forms
Good spot! This isn't quite right though. It'd be `/sdcard/Android/data/org.odk.collect.android/files/projects/<project id>/forms`. We have docs for this [elsewhere](https://docs.getodk.org/collect-adb/#developer-tasks-and-troubleshooting-with-adb), so I actually think we should just link to that here instead of having it repeated.

2024-10-23 13:03 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/AddRepeatTest.java
> +    public void whenInEmptyRepeat_swipingNext_andClickingAdd_addsAnotherRepeat() {
It'd be good to call out the missing label in the test name here: `whenInRepeatWithoutLabel_swipingNext_andClickingAdd_addsAnotherRepeat`.

2024-10-23 13:03 UTC, seadowg commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/AddRepeatTest.java
> +                .assertQuestion("First name", true)
I don't think you need to assert or answer the question here right? It could just swipe through.

2024-10-23 13:03 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/formentry/repeats/AddRepeatDialog.java
> +                case BUTTON_POSITIVE -> listener.onAddRepeatClicked();
I hadn't realized you could avoid `break` in Java now! Nice.

2024-10-29 17:26 UTC, seadowg requested changes
It looks like the `README.md` has been reformatted in some way?

2024-11-04 04:59 UTC, karntrehan commented
> It looks like the `README.md` has been reformatted in some way?

Not sure of this. Let me check. My android studio auto formats before commits. Let me undo that.

2024-11-05 14:10 UTC, seadowg approved these changes

2024-12-10 14:36 UTC, merged

2024-12-17 15:18 UTC, WKobus commented
**Tested with Success!**

Verified on device with Android 15

**Verified cases:**

- Check on different repeat forms
- Repeat forms with null values

2024-12-17 15:33 UTC, dbemke commented
**Tested with Success!**

Verified on device with Android 10