Reset savepoints when resetting instances
getodk/collect pull request #6468
Opened 2024-10-23 13:22 UTC by grzesiek2010

Closes #6331 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-10-30 16:52 UTC, seadowg requested changes
This looks good, but it needs to be rebased on top of master so that it's not readding back in the entities clearing (which was removed recently).

2024-10-30 17:47 UTC, grzesiek2010 commented
> This looks good, but it needs to be rebased on top of master so that it's not readding back in the entities clearing (which was removed recently).

Done.

2024-10-30 18:06 UTC, seadowg approved these changes

2024-11-05 13:51 UTC, WKobus commented
**Tested with Success**

Verified on device with Android 15

**Verified cases:**
- Issue #6331 does not occur
- Resetting saved and blank forms
- Resets in entity and non entity forms

2024-11-05 14:12 UTC, dbemke commented
**Tested with Success**

Verified on device with Android 10

2024-11-05 14:16 UTC, merged