Convert hierarchy to Fragment
getodk/collect pull request #6516
Opened 2024-11-18 15:52 UTC by seadowg

- **Add tests for view only behaviour**
- **Remove ViewOnlyHierarchyActivity**
- **Spike out empty form hierarchy Fragment**
- **WIP convert hierarchy to fragment**

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-11-22 16:17 UTC, seadowg commented
@getodk/testers marking this ready for testing before review as it'd be good to get a first pass before I clean things up in case there are some fundamental problems here I've missed.

2024-12-16 10:36 UTC, dbemke commented
There used to be 2 icons: to go to the hierarchy view and to go "up" in the hierarchy (the second screenshot). Now there's only one icon and it feels a bit confusing in groups and repeats cause the new icon doesn't suggest where the user is moved after tapping it. Is it expected?
![newHierarchy](https://github.com/user-attachments/assets/dd395501-fcc4-46d9-a0e5-98cdb1f89b4c)
![hierarchyIcon](https://github.com/user-attachments/assets/7a5d3847-4293-4b42-a274-74e3e81e384b)

2024-12-16 11:33 UTC, seadowg commented
> There used to be 2 icons: to go to the hierarchy view and to go "up" in the hierarchy (the second screenshot). Now there's only one icon and it feels a bit confusing in groups and repeats cause the new icon doesn't suggest where the user is moved after tapping it. Is it expected?

I think this was the intention of https://github.com/getodk/collect/issues/6303, but please correct me if I'm wrong @alyblenkin.

2024-12-16 16:34 UTC, alyblenkin commented
> I think this was the intention of https://github.com/getodk/collect/issues/6303, but please correct me if I'm wrong @alyblenkin.

This is a good catch! The goal was just to update the east arrow icon, not the up icon as well. I think the up arrow is still a helpful visual indicator that you're going back up to the table of contents.

2024-12-16 16:47 UTC, seadowg commented
> This is a good catch! The goal was just to update the east arrow icon, not the up icon as well. I think the up arrow is still a helpful visual indicator that you're going back up to the table of contents.

That makes sense. Just to be sure though before I unwind anything, [the Figma link](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=6228-20698&t=CbI3Km7LacH9cKvO-1) shows the hierarchy with the list icon in the top right:

<img width="237" alt="Screenshot 2024-12-16 at 16 47 05" src="https://github.com/user-attachments/assets/c6541d9c-5297-4ed7-85a3-83d49a2ac5cc" />

I'm guessing that's a mistake?

2024-12-16 17:05 UTC, alyblenkin commented
Sorry I think the group folder icon in the first mockup is a mistake. However, now I'm second guessing myself because we discussed this a while back. @lognaturel correct me if I'm wrong here, but our goal was just update the east arrow, not the up arrow icon as well.

2024-12-16 17:09 UTC, alyblenkin commented
To clarify, I think the list icon would work on it's own if we didn't already have the up arrow, but I think it's a pretty ingrained pattern now. I think the list icon would suggest you go back to the top level given the current pattern where there is more of this concept of moving up or down, but you could also imagine tapping to keep going to the main table of contents. I don't think this is a stronger design choice, rather it could be another option. Not worth considering given we haven't had folks bring up any issues.

2024-12-16 17:20 UTC, lognaturel commented
Feels right to me to leave the up arrow as it is. I think navigating up a level feels relatively clear. I don't think the table of contents icon works well there because it would suggest you go all the way back to the top level.

2024-12-16 18:59 UTC, alyblenkin commented
@seadowg - sorry that you have to unwind things there! I've update the design.

2024-12-17 10:01 UTC, seadowg commented
> sorry that you have to unwind things there! I've update the design.

No worries! I just wanted to double check.

2024-12-17 15:22 UTC, seadowg commented
@getodk/testers that should be good to go again!

2024-12-20 13:37 UTC, dbemke commented
**Tested with success!**

Verified on devices with Android 10, 14

**Verified cases:**
- the new icon in the hierarchy
- groups and repeats
- the hierarchy view in new forms, drafts, Ready to send, Sent 
- the hierarchy view after recovering a savepoint
- moving backwards enabled and disabled
- RTL
- light and dark  mode
- don't keep activities enabled and disabled

2025-01-07 12:23 UTC, grzesiek2010 requested changes

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormHierarchyTest.java
> +    public void whenViewFormInHierarchyForRepeat_noDeleteButtonAppears() {
Above you renamed `whenInHierarchyForRepeat_clickingPlus_addsRepeatAtEndOfSeries` adding `Group` so for consistency here the test also should be named `whenViewFormInHierarchyForRepeatGroup_noDeleteButtonAppears`.

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
> +public class FormHierarchyFragment extends Fragment {
Are we planning to convert this to Kotlin in a follow-up pull request?

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/res/layout/form_hierarchy_layout.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Now `hierarchy_layout` is redundant and you can remove it.

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/AndroidManifest.xml
> +        <activity android:name="org.odk.collect.android.formhierarchy.FormHierarchyActivity" />
This should be removed.

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
> -public class FormHierarchyActivity extends LocalizedActivity implements DeleteRepeatDialogFragment.DeleteRepeatDialogCallback {
There are still a couple of comments where `FormHierarchyActivity` is used instead of `FormHierarchyFragmentHostActivity` plus in the `STATE.md` file.

2025-01-07 12:23 UTC, grzesiek2010 commented on icons/src/main/res/drawable/ic_baseline_list_24.xml
> +        android:fillColor="?colorSurface"
Why not `colorOnSurface`?

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formentry/repeats/DeleteRepeatDialogFragment.java
> +                if (callback != null) {
Can't we have one way of communication?

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
> +            public <T extends ViewModel> T create(@NonNull Class<T> modelClass) {
We could move this to `FormEntryViewModelFactory` and just use `viewModelFactory` as above.

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
> +            ArrayList<HierarchyItem> elementsToDisplay = new ArrayList<>();
You should use the `List` interface here:
`List<HierarchyItem> elementsToDisplay = new ArrayList<>();
`

2025-01-07 12:23 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
> +            recyclerView.setAdapter(new HierarchyListAdapter(formHierarchyViewModel.getElementsToDisplay(), this::onElementClick));
I think here you can directly use `elementsToDisplay`. However, if you always access the list via the ViewModel please update it below in line `formController.jumpToIndex(elementsToDisplay.get(0).getFormIndex());` as well.

2025-01-08 09:00 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
> +public class FormHierarchyFragment extends Fragment {
Not in the short term. I wanted to stay away from bulk Kotlin converts here to keep the diffs tight and limit any extra work. My strategy was to just keep the Java contained in `FormHierarchyFragment` and try and make as little changes there as possible.

2025-01-08 09:06 UTC, seadowg commented on icons/src/main/res/drawable/ic_baseline_list_24.xml
> +        android:fillColor="?colorSurface"
I'm pretty sure they're flipped from what you'd think here: the tint is `colorOnSurface` and the path is `colorSurface`. Everything looks correct right?

2025-01-08 09:23 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
> +            public <T extends ViewModel> T create(@NonNull Class<T> modelClass) {
`FormHierarchyViewModel` is currently private to `FormHierarchyFragment` and I reckon as we continue we'll probably remove it and move its functionality into `FormEntryViewModel`.

2025-01-08 09:53 UTC, grzesiek2010 commented on icons/src/main/res/drawable/ic_baseline_list_24.xml
> +        android:fillColor="?colorSurface"
But why not to use `colorOnSurface` in both as we do in every other icon? What's the point of using `colorSurface` here?

2025-01-08 10:44 UTC, seadowg commented on icons/src/main/res/drawable/ic_baseline_list_24.xml
> +        android:fillColor="?colorSurface"
Good question! It looks like we just don't need `tint`. I'd always get confused by this, but the tint color [is "blended" in with the others](https://developer.android.com/reference/android/R.attr#tint) so here the `path` was being rendered with `colorSurface` but then it would just be "blended" (just overridden in this case) with `colorOnSurface`. If I remove `tint` and set the path to `colorOnSurface` it seems to work as expected.

2025-01-08 13:07 UTC, grzesiek2010 commented on icons/src/main/res/drawable/ic_baseline_list_24.xml
> +        android:fillColor="?colorSurface"
> If I remove tint and set the path to colorOnSurface it seems to work as expected.

Yes, but when you change themes it might not work as expected see this pr https://github.com/getodk/collect/pull/5537
Maybe now as removed changing the theme in the app it is no longer needed but I'm not sure. If you want to remove it please make sure it is not needed or maybe a better idea is to keep it and file an issue to investigate if we still need it.

2025-01-08 15:11 UTC, grzesiek2010 requested changes
https://github.com/getodk/collect/pull/6516#discussion_r1907155873

2025-01-08 18:46 UTC, grzesiek2010 approved these changes

2025-01-08 18:46 UTC, merged