Remove education dialog for error pills in Drafts list
getodk/collect pull request #6528
Opened 2024-11-21 20:08 UTC by lognaturel

#### Why is this the best possible solution? Were any other approaches considered?

Error/no errors pills were introduced in Oct 2023. It's fairly common for data collectors to switch devices or otherwise need to reinstall Collect. Seeing the education message again is not a very big deal but it is slightly annoying so I think now is a good time to remove it.

Happy to discuss and close this if others see a good reason to keep it in longer.

I considered keeping the "New feature" string but that would require using it somewhere to pass lint and I don't think it's worth it. I can bring back the translations if we need it again. 

I used the translation editor to remove the string definition from all languages. This left the comments behind and those will be cleaned up the next time we update from Transifex.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The intentional change is to remove the information dialog. I think there is a low risk of a bug. The biggest risk is probably that someone who hasn't yet seen the pills doesn't see the information dialog and is confused about their function. I think they're pretty self-explanatory so this feels unlikely to me. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-11-22 17:08 UTC, alyblenkin commented
Given we've had the educational dialog for quite some time, I think it's safe to remove it. Mostly because the pills are pretty intuitive and we haven't heard any feedback, that I'm aware of, about them causing confusion for data collectors.

2024-11-27 09:32 UTC, seadowg requested changes
My guess is that this is having the same problem as https://github.com/getodk/collect/pull/6526.

2024-11-28 08:49 UTC, seadowg requested changes
The connected tests aren't compiling. Looks like there's at least one constructor call (in `InstancePickActionTest`) that needs updating.

2025-02-03 09:48 UTC, seadowg commented
@lognaturel this still needs fixed. I can take over if that would be easier?

2025-02-04 08:41 UTC, seadowg approved these changes

2025-02-04 08:41 UTC, merged