Improve media displayed in widgets [BarcodeWidget + ArbitraryFileWidget]
getodk/collect pull request #6534
Opened 2024-11-28 16:20 UTC by grzesiek2010

Work towards #6234 

#### Why is this the best possible solution? Were any other approaches considered?
The structure of this pull request reflects the discussion below. It’s the first step toward creating shareable answer views that can be used across all question types and eventually in the summary view as well. The changes are introduced for `BarcodeWidget`, `ArbitraryFileWidget`, and `ExArbitraryFileWidget`, but later other question types will be reworked in the same way.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The only visible change is that answers in the barcode question will now include an icon in addition to the text. This is something we plan to introduce later for other question types as well, since a shared style should be used across both the questions and the summary view.
Aside from that, this is purely a refactoring and shouldn't introduce any functional changes. However, we should still test the `BarcodeWidget`, `ArbitraryFileWidget`, and `ExArbitraryFileWidget` to ensure that no regressions have been introduced.

#### Do we need any specific form for testing your changes? If so, please attach one.
The `All question types` form is fine.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-12-04 14:31 UTC, grzesiek2010 commented
@seadowg 
please take a quick look to see if the general approach looks good to you.

2024-12-05 11:10 UTC, seadowg requested changes
I definitely like the general direction of pulling out a view to specifically represent the answer here. I had in mind that we could go a bit further and have a generalized `AnswerView` with a similar structure that where `setAnswer` takes an `IAnswerData` (I think the widget would handle the hidden appearance in that setup). That would get us something that's simple to then use in the hierarchy later.

2025-01-13 14:51 UTC, grzesiek2010 commented
@seadowg could you clarify your feedback because I'm not sure if I understand?
Do you want to have one `AnswerView` for all types of questions? or maybe `AnswerView` should be an interface and implementations would be created based on data type as we do for the whole widgets in `WidgetFactory`?

2025-01-15 10:51 UTC, seadowg commented
> Do you want to have one AnswerView for all types of questions? or maybe AnswerView should be an interface and implementations would be created based on data type as we do for the whole widgets in WidgetFactory?

I was thinking one `AnswerView` that can handle any `IAnswerData`, but I'd imagine that'd be implemented using multiple different child views. My thinking is that we currently make the decision about how to display an answer in two places (in each widget and in the hierarchy list items) and we could move that to one place.

2025-01-20 17:35 UTC, grzesiek2010 commented
> I was thinking one AnswerView that can handle any IAnswerData, but I'd imagine that'd be implemented using multiple different child views.

That makes sense. 

> My thinking is that we currently make the decision about how to display an answer in two places (in each widget and in the hierarchy list items) and we could move that to one place.

The view I factored out will be one that can be shared between the question layout and the hierarchy layout.

As I rework other questions, I’ll likely introduce some form of abstraction. Later, when we work on the hierarchy view, we'll need to implement a factory to construct the appropriate view but that can wait for now.

Let's maybe continue with other question types in this pull request to see how it goes, unless you have something against the current changes.

2025-01-21 10:21 UTC, seadowg reviewed
> Let's maybe continue with other question types in this pull request to see how it goes, unless you have something against the current changes.

That sounds good! You're right that it makes more sense to introduce the generalization after 2 or 3 examples rather than trying to plan it ahead of time.

2025-02-13 13:28 UTC, seadowg commented
@grzesiek2010 I've been running into frustrations trying to add an arg to the `QuestionWidget` constructor, and it led me to thinking a bit more about the eventual structure we want. 

Basically I think we need to get to a point where we can modify `QuestionWidget` (the thing responsible for the shared view logic between every widget) without needing to then modify all the subclasses. I reckon we'll need to deploy some "composition over inheritance" to achieve this. To go with the example we already have here I reckon instead of a `BearingWidget` we really just want to have a `BearingWidgetAnswer` and then in `WidgetFactory` be constructing our bearing question like this (or something similar):

```kotlin
QuestionWidget(context, questionDetails, BearingWidgetAnswer())
```

That would let us easily modify `QuestionWidget`'s constructor in the future (and remove things like Dagger). I think getting to that sort of place for at least one widget here would be great! Sadly I don't think that kind of restructure is a good idea in one go.

2025-02-18 23:18 UTC, grzesiek2010 commented
@seadowg 
As discussed earlier, I've reworked another question type (actually four, since there are multiple image questions) to see how it goes. I believe we can have a single interface implemented for all widget answer classes, like `BarcodeWidgetAnswer`, `ImageWidgetAnswer`, and so on. However, different implementations require different dependencies. For example, `ImageWidgetAnswer` needs `imageLoader`, `questionMediaManager`, etc. Given that, I think we'll need a factory similar to the one we use for entire widgets.

> QuestionWidget(context, questionDetails, BearingWidgetAnswer())

The current implementation adds the answers using XML, but this won’t be possible later in the summary view, where we’ll need to generate answers dynamically. So, it would probably make more sense to add that view programmatically in the widgets as well. Is that what you meant? Any other thoughts?

2025-02-24 16:09 UTC, seadowg commented
> The current implementation adds the answers using XML, but this won’t be possible later in the summary view, where we’ll need to generate answers dynamically. So, it would probably make more sense to add that view programmatically in the widgets as well. Is that what you meant? Any other thoughts?

Right it feels like we need to move to the views being added programmatically for this to work. So ideally `QuestionWidget` has a new constructor arg for the widget answer view (like we've been describing) that is a `View` and also implements our new interface (`WidgetAnswer` for example). In Kotlin, we could do this:

```kotlin
class QuestionWidget<A>(private val widgetAnswerView: A) where A : View, A : WidgetAnswer {
```

I think in Java we just need to use an abstract to combine the types:

```java
public abstract class WidgetAnswerView extends View implements WidgetAnswer {
}
```

Then we'd be able to add that view into the layout for the `QuestionWidget` programmatically and interact with it using the interface. Given it's going to be hard to convert everything at once, we probably want to deprecate, but continue to support `QuestionWidget#onCreateAnswerView` for a while longer.

2025-03-09 21:24 UTC, grzesiek2010 commented
@seadowg 
The current version of this PR demonstrates how this could look using the `BarcodeWidget` and `ArbitraryFileWidget`. I think it's close to what we need. Please take a look. If it looks good, I can prepare it for review and then continue working on other widgets.

2025-03-13 14:14 UTC, seadowg reviewed
@grzesiek2010 I had been thinking we'd basically replace the `onCreateAnswerView` implementation with the new `WidgetAnswer` concept. Do you think that's another step or do you disagree?

2025-03-19 22:43 UTC, grzesiek2010 commented
@seadowg `onCreateAnswerView` is responsible for setting up the entire question view, not just the answer part. For example, in `BarcodeWidget`, the view it returns includes both the button to trigger scanning and the real answer part. The current naming is misleading and should be changed, but we cannot remove this method.

2025-03-20 10:41 UTC, seadowg commented
Just to expand on my [earlier comment](https://github.com/getodk/collect/pull/6534#issuecomment-2656604891), I wanted to be more explicit about where I saw this eventually going. My thinking was that in the future (🔮) we'd end up switching away from an inheritance based model for widgets to a composition based one. The way I'd see that working is that we'd have a `QuestionWidget` class that's `final` (no subclasses) that has a constructor like this (with probably a couple of extra args for things like `AudioPlayer`):

```kotlin
class QuestionWidget(context: Context, questionDetails: QuestionDetails, widgetAnswer: WidgetAnswer)
```

Then when we're displaying a question we are always constructing a `QuestionWidget` with the only difference being which `WidgetAnswer` implementation we pass it and that `WidgetAnswer` would handle all the type specific stuff so it would have an interface more similar to the current `QuestionWidget`'s abstract methods. 

I was thinking a way to transition to that would be to have `QuestionWidget` take an optional `WidgetAnswer` for the moment and have `QuestionWidget#onCreateAnswerView` use that if it's non-null (along with other methods like `clearAnswer` etc). In that world, we'd end up with no `BarcodeWidget` at all, we'd just pass `BarcodeWidgetAnswer` to a `QuestionWidget`. I think where the PR is right now is pretty similar, I'm just proposing making it a more general change and expanding it so we can kill the specific widget classes we're updating here (I'd suggest we limit it to the ones we've already got to) to set a direction.

As an aside, there's been some back and forth about Compose. I think that this direction is exactly what we'd want to do if we were looking to build widgets with Composables (or similar frameworks like React/JSX):

```kotlin
@Composable
fun QuestionWidget(questionDetails: QuestionDetails) {
    BarcodeAnswer(
        questionDetails: QuestionDetails,
        onScanBarcode = {
            // Launch barcode scanner
        },
        onLongPress = onLongPressListener
     )
}
```

Obviously we're pretty far off from that kind of thing as widgets hold state (which wouldn't work in a Compose setup), but I think shooting for that kind of structure makes sense.

2025-03-20 11:13 UTC, seadowg reviewed
https://github.com/getodk/collect/pull/6534#issuecomment-2739915313

2025-03-20 19:42 UTC, grzesiek2010 commented
@seadowg The structure I started building (to be used in the hierarchy as well) consists of `WidgetAnswerView`s that contain only the answer part—for example, just the image for image questions or just the text for barcode questions. This aligns with what we previously agreed on, as I recall. Based on your description, it seems like you envision `WidgetAnswerView` as the entire question view, including buttons and other elements. Am I misunderstanding something? The structure you described isn’t compatible with the one I started working on. Of course, in the future, we can introduce another set of views that build on `WidgetAnswerView` and incorporate the rest of the layout.

2025-03-21 11:50 UTC, seadowg commented
> Based on your description, it seems like you envision WidgetAnswerView as the entire question view, including buttons and other elements. Am I misunderstanding something? The structure you described isn’t compatible with the one I started working on. Of course, in the future, we can introduce another set of views that build on WidgetAnswerView and incorporate the rest of the layout.

I've had a bit of a think about it, and I agree. I'm jumping the gun a bit! Down the line, I'd really like to get to a place where `QuestionWidget` has no subclasses, and we just create widgets via composition, but you're right that `WidgetAnswer` can be a building block in that rather than providing the whole thing. 

How about we rename `WidgetAnswer` to `AnswerView` to make it really clear that this is a component for rendering answer data. We should rename `onCreateAnswerView` to something else here as well as (as you point out), it's really more than just the "answer" - it's the full type specific controls and answer for the widget.

Thanks for back and forth on this with me! I'm liking the direction we're moving in.

2025-03-21 11:50 UTC, seadowg commented
> Based on your description, it seems like you envision WidgetAnswerView as the entire question view, including buttons and other elements. Am I misunderstanding something? The structure you described isn’t compatible with the one I started working on. Of course, in the future, we can introduce another set of views that build on WidgetAnswerView and incorporate the rest of the layout.

I've had a bit of a think about it, and I agree. I'm jumping the gun a bit! Down the line, I'd really like to get to a place where `QuestionWidget` has no subclasses, and we just create widgets via composition, but you're right that `WidgetAnswer` can be a building block in that rather than providing the whole thing. 

How about we rename `WidgetAnswer` to `AnswerView` to make it really clear that this is a component for rendering answer data. We should rename `onCreateAnswerView` to something else here as well as (as you point out), it's really more than just the "answer" - it's the full type specific controls and answer for the widget.

Thanks for back and forth on this with me! I'm liking the direction we're moving in.

2025-06-04 12:02 UTC, grzesiek2010 commented
> How about we rename WidgetAnswer to AnswerView to make it really clear that this is a component for rendering answer data. We should rename onCreateAnswerView to something else here as well as (as you point out), it's really more than just the "answer" - it's the full type specific controls and answer for the widget.

Done.

2025-06-05 11:10 UTC, seadowg requested changes
Did a first pass and some comments on some structural things

2025-06-05 11:10 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.kt
> +    private val widgetAnswerView: WidgetAnswerView,
For right now is there any reason to have `WidgetAnswerView` passed in like this? It seems like we'd only ever want `ArbitraryFileWidget` to be using `ArbitraryFileWidgetAnswerView`.

2025-06-05 11:10 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
> +    void inject(WidgetAnswerTextView widgetAnswerText);
I'd love to avoid using Dagger here. Could we add a `setFontSize` to `WidgetAnswerView` instead?

2025-06-05 11:10 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.kt
> +        val answer = widgetAnswerView.getAnswer()
While we're here, it would be great to try and avoid propagating the pattern of storing state in the views themselves. Would we be able to remove `getAnswer` from `WidgetAnswerView` and just store the answer in a field in these widgets?

2025-06-05 11:10 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
> +    protected View onCreateWidgetView(@NonNull Context context, @NonNull FormEntryPrompt prompt, int answerFontSize) {
`WIDGETS.md` will need an update

2025-07-13 11:15 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.kt
> +    private val widgetAnswerView: WidgetAnswerView,
> It seems like we'd only ever want ArbitraryFileWidget to be using ArbitraryFileWidgetAnswerView.

That's correct. Do you think it should be declared here with `ArbitraryFileWidgetAnswerView` type or not passed via the constructor at all?

2025-07-13 11:59 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
> +    void inject(WidgetAnswerTextView widgetAnswerText);
Ok.

2025-08-06 08:26 UTC, seadowg requested changes

2025-08-06 08:26 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.kt
> +    private val widgetAnswerView: WidgetAnswerView,
I think eventually it would be nice to get back to my earlier dream of being able to have a `QuestionWidget` that just takes a `WidgetAnswerView` and that's how we create different widgets for different types. With the goal here being to just get to reusable "answer views" then I think it'd be better to reduce the number of changes by just constructing the answers views within the widgets.

2025-08-21 22:05 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.kt
> +    private val widgetAnswerView: WidgetAnswerView,
> I think eventually it would be nice to get back to my earlier dream of being able to have a QuestionWidget that just takes a WidgetAnswerView and that's how we create different widgets for different types. With the goal here being to just get to reusable "answer views" then I think it'd be better to reduce the number of changes by just constructing the answers views within the widgets.

So now you would like to generate that `WidgetAnswerView` in the widget instead of doing that in the `WidgetFactory` and passing it via the constructor?

2025-08-22 08:30 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.kt
> +    private val widgetAnswerView: WidgetAnswerView,
> So now you would like to generate that WidgetAnswerView in the widget instead of doing that in the WidgetFactory and passing it via the constructor?

Right now, there's no reason to pass them in right? We require a specific type at the constructor (rather than the `WidgetAnswerView` interface) and as far as I can see, the `QuestionWidget` implementations have everything they need to construct them. That said, there is a nice separation with the current structure. What do you prefer?

2025-08-22 09:39 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.kt
> +    private val widgetAnswerView: WidgetAnswerView,
> Right now, there's no reason to pass them in right?

correct

> What do you prefer?

I don’t have strong preferences at the moment. My thought was that once we start reusing the same views in the summary view, we could have a single factory for them, shared across both places. That factory could be used in WidgetAnswerView to generate a view and pass it through the constructor (as it works now), or it could be passed directly and used to build the answer view inside a widget. I’m not sure yet which approach you or I will prefer in the future. I’m fine with leaving it as it is, but I’m also open to changing it so that each widget generates its own views.

2025-08-22 10:40 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.kt
> +    private val widgetAnswerView: WidgetAnswerView,
> My thought was that once we start reusing the same views in the summary view, we could have a single factory for them, shared across both places. That factory could be used in WidgetAnswerView to generate a view and pass it through the constructor (as it works now), or it could be passed directly and used to build the answer view inside a widget. I’m not sure yet which approach you or I will prefer in the future. I’m fine with leaving it as it is, but I’m also open to changing it so that each widget generates its own views.

Yeah I could see either working as well! Ok I think I'm happy with the current approach then. We're not coupling because the constructors require a `WidgetAnswerView` (rather than the specific implementations) so we could move to that factory structure later. I'll have a look at the rest of this!

2025-08-22 12:20 UTC, seadowg commented on collect_app/src/main/res/layout/arbitrary_file_widget_answer_view.xml
> +        android:tag="ArbitraryFileWidgetAnswer"
Why do we need this tag?

2025-08-22 12:20 UTC, seadowg commented on collect_app/src/main/res/values/attrs.xml
> +        <attr name="widgetAnswerTextViewStyle" format="reference" />
I can't find any usages of this? I'm guessing I'm missing something.

2025-08-22 12:32 UTC, seadowg requested changes

2025-08-22 12:32 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidgetAnswerView.kt
> +        this.answer = stripInvalidCharacters(answer)
I'm wondering if this should happen in the widget (probably only in `setData`) given it's not really a display concern and more of a "data processing" thing.

2025-08-27 22:52 UTC, grzesiek2010 commented on collect_app/src/main/res/layout/arbitrary_file_widget_answer_view.xml
> +        android:tag="ArbitraryFileWidgetAnswer"
It is used in tests to find this type of question, and for example, to check if it is displayed.

2025-08-28 07:51 UTC, seadowg commented on collect_app/src/main/res/layout/arbitrary_file_widget_answer_view.xml
> +        android:tag="ArbitraryFileWidgetAnswer"
Ah right! It would be better for it to use something visible to do that, but that's not something introduced here so I'll avoid getting distracted by it.

2025-09-15 07:02 UTC, grzesiek2010 commented on collect_app/src/main/res/values/attrs.xml
> +        <attr name="widgetAnswerTextViewStyle" format="reference" />
Fixed.

2025-09-15 07:02 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidgetAnswerView.kt
> +        this.answer = stripInvalidCharacters(answer)
Fixed.

2025-09-16 08:17 UTC, seadowg requested changes

2025-09-16 08:17 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.kt
> +        val answer = widgetAnswerView.getAnswer()
Could we still store state at the widget level here? As I said in the previous comment, removing `getAnswer` from `WidgetAnswerView` so it's not used as a store of state would be ideal here. Ultimately, we'd like to avoid storing state in the widget as well (it should live outside the view layer in a ViewModel or something similar at that level), but for now I'd just like to avoid duplicating that problem in these new components.

2025-09-18 12:20 UTC, seadowg approved these changes

2025-09-19 09:17 UTC, srujner commented
Icon is to close to the text and I don't know if it's just me but it looks bit weird if there is longer text? 
Also you might notice that the text is cut off and it's not possible to move it
<details> <summary> Icon to close </summary>

![Screenshot_20250919_105855_ODK Collect](https://github.com/user-attachments/assets/e9ca87f7-c95b-4cd8-bbd2-5abebebf0497)

</details>

<details> <summary> Long and cut off text</summary>

![Screenshot_20250919_110522_ODK Collect](https://github.com/user-attachments/assets/389157a9-7232-4259-bf1d-5df03508dbcc)

</details>

2025-09-23 08:06 UTC, srujner commented
@grzesiek2010 Could you take a look?

2025-09-24 12:52 UTC, grzesiek2010 commented
@srujner it should work well now.

2025-09-25 11:20 UTC, WKobus commented
**Tested with success**

Verified on Android 16

**Verified cases:**

- Scanning different barcodes
- Different type of media in file widget
- Regression check on media, file and barcode widget

2025-09-25 11:28 UTC, dbemke commented
**Tested with success**

Verified on Android 10

2025-09-25 22:52 UTC, merged