Fix instances count on main menu
getodk/collect pull request #6535
Opened 2024-11-28 17:25 UTC by seadowg

- **Convert properties to functions**
- **Make instances counts project specific**
- **Use Flow for current project**

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2025-02-06 23:27 UTC, grzesiek2010 requested changes

2025-02-06 23:27 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/mainmenu/CurrentProjectViewModelTest.kt
> +    private val currentProjectViewModel by lazy { CurrentProjectViewModel(projectsDataService) }
Does it make any sense to use `by lazy` in tests?

2025-02-06 23:27 UTC, grzesiek2010 commented on androidshared/src/main/java/org/odk/collect/androidshared/data/Data.kt
> +    protected fun <T> data(key: String, default: T, updater: () -> T): DataDelegate<T> {
It's used just in one place I think we can get rid of it and use `qualifiedData` instead. Then we could also remove `attachData` and move the code directly to `qualifiedData`.

2025-02-07 11:22 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/mainmenu/CurrentProjectViewModelTest.kt
> +    private val currentProjectViewModel by lazy { CurrentProjectViewModel(projectsDataService) }
You can't construct a `CurrentProjectViewModel` until after the JUnit rules have run (so that `InstantTaskExecutorRule` has done its job). I agree that the `lazy` is a bit weird though, so I'll just replace it with construction in the tests themselves.

2025-02-07 11:29 UTC, seadowg commented on androidshared/src/main/java/org/odk/collect/androidshared/data/Data.kt
> +    protected fun <T> data(key: String, default: T, updater: () -> T): DataDelegate<T> {
Right this is a little weird. The reason for the two is so that the `updater` type can be more accurate: for `data` we don't want there to be a qualifier passed to it. This kind of falls apart though because you **could** still then pass a qualifier to `Data#flow`. I'll have a quick go at making the types stricter throughout.

2025-02-07 12:28 UTC, grzesiek2010 approved these changes

2025-02-07 12:29 UTC, merged

2025-02-10 13:54 UTC, dbemke commented
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- issue # 6531 doesn't occur 
- regression checks in saving as draft,finalizing, sending form
- regression checks in form new version, downloading/updating media

2025-02-10 13:59 UTC, WKobus commented
**Tested with Success!**

Verified on a device with Android 15 and Android 12 by Szymon