Optimize more entity filter expressions
getodk/collect pull request #6539
Opened 2024-12-02 21:41 UTC by grzesiek2010

Closes #6498 

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-12-03 01:16 UTC, grzesiek2010 commented
The issue outlines four filter expressions that need optimization.  
The first one (`label = <value>`) is already supported.  
I have added support for the last one (`id/label/version/property != <value>`).

It seems we need to discuss how to handle the following cases:  
- `<id/property/label> = <value 1> and <id/property/label> = <value 2>`  
- `<id/property/label> = <value 1> or <id/property/label> = <value 2>`

Specifically:
- Should we support only combining two expressions, or was the example just a demonstration, with the solution needing to be more flexible?
- To write tests, we must first merge https://github.com/getodk/javarosa/pull/808, as wiring expressions with `and`/`or` will fail without this.

Another question, not directly related to any of the filter types:  
we are calling [[replacePartialElements](https://github.com/getodk/collect/blob/master/entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt#L52C36-L52C58)](https://github.com/getodk/collect/blob/master/entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt#L52C36-L52C58). In which scenario would we encounter issues if we do not call it? I removed this call, and all tests passed, which was strange to me. I believe I understood its purpose, but now that all tests are passing without it, I feel a bit disoriented.

@seadowg, feel free to not only answer these questions but also take over if you don't have other pressing tasks. You might have intended to work on this yourself, and I took it on without asking. If that's the case, I hope at least what I’ve done will be helpful.

2024-12-03 09:06 UTC, seadowg commented
> The first one (label = <value>) is already supported.

It's supported, but not optimized (compared to `id = <value>`). The [current implementation](https://github.com/getodk/collect/blob/62991d28c63e413fc6902d8a8b7c280af8a754f5/entities/src/main/java/org/odk/collect/entities/javarosa/intance/LocalEntitiesInstanceAdapter.kt#L57) will use the DB to find the tree references, but it does that by calling `getEntities` and then filtering them in memory which requires the whole entity list (from the DB) in memory (at least temporarily). We want to let SQLite handle the filtering here (like we do with ID) so we don't need to take that hit.

> Should we support only combining two expressions, or was the example just a demonstration, with the solution needing to be more flexible?

For this issue, I'd only intended that we add support for those exact expressions. If it feels easier to you at this point to make the solution more general though, that'd be a bonus.

> To write tests, we must first merge https://github.com/getodk/javarosa/pull/808, as wiring expressions with and/or will fail without this.

Interesting! I'll have a look at that as soon as I can.

> Another question, not directly related to any of the filter types:
we are calling [[replacePartialElements](https://github.com/getodk/collect/blob/master/entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt#L52C36-L52C58)](https://github.com/getodk/collect/blob/master/entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt#L52C36-L52C58). In which scenario would we encounter issues if we do not call it? I removed this call, and all tests passed, which was strange to me. I believe I understood its purpose, but now that all tests are passing without it, I feel a bit disoriented.

Everything will "work" without `replacePartialElements`: the `FilterStrategy` chain will return the correct references and then later those will get materialized into elements via the secondary instance's `resolveReference` method. Without `replacePartialElements` however, the call to `resolveReference` will end up forcing a full parse of the secondary instance as the reference will point at a partial element. `replacePartialElements` essentially fills in the gaps in the partially parsed instance (from the representation) as we make filters so we only load the things into memory that we need. There are specific tests that check that we don't "fallback" like this (example [here](https://github.com/getodk/collect/blob/62991d28c63e413fc6902d8a8b7c280af8a754f5/entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt#L138)).

> @seadowg, feel free to not only answer these questions but also take over if you don't have other pressing tasks. You might have intended to work on this yourself, and I took it on without asking. If that's the case, I hope at least what I’ve done will be helpful.

No I think it's actually a good idea to swap over on this one as I'm worried I'm a silo on how the entities stuff all works (especially the optimizations). It'll be good to spread the knowledge out a bit!

2024-12-13 10:26 UTC, grzesiek2010 commented
@seadowg  
I think I need to rethink the approach we started with, so I wanted to discuss it with you.  

If you take a look at the first couple of commits, you'll see that I added support for `label = <value>` and `id != <value>` by continuing with our initial approach. Specifically, I updated the `queryEq` method and implemented a new [queryNotEq](https://github.com/getodk/collect/pull/6539/commits/ccdfc206f1f2960561362b5528460deade214f20)

While this worked well initially, I found that adding new methods like `getBySomething` for every case ended up generating a lot of code. The real challenge came when I started thinking about how to handle combinations of `=` and `!=` with `AND/OR`. I realized that our current approach would make it extremely difficult, if not impossible, to support versatile expressions involving multiple `AND/OR` conditions.  

I believe the best solution to address this, while also reducing the amount of code, would be to generate SQLite selection and selection arguments directly in [LocalEntitiesFilterStrategy](https://github.com/getodk/collect/pull/6539/commits/b2d25889a88ebb11fef287a44b6d30c5cf571df4#diff-958253b34c67052b5a65a4f5feb4dfed8a09e3d80acb7d12b3d55a0f04189e4dR45).
This approach offers several advantages:  
- It significantly reduces boilerplate code.  
- It automatically optimizes other expressions like `version = <value>` and `version != <value>`, eliminating the need to add support for each case individually.  
- It simplifies handling combinations of expressions using `AND`/`OR`.  

Please take a quick look to make sure you agree with it before I continue.

2024-12-13 11:51 UTC, seadowg commented
> While this worked well initially, I found that adding new methods like getBySomething for every case ended up generating a lot of code. The real challenge came when I started thinking about how to handle combinations of = and != with AND/OR. I realized that our current approach would make it extremely difficult, if not impossible, to support versatile expressions involving multiple AND/OR conditions.

I do think you're right that we're going to need something more versatile to support all the kinds of expressions we want to optimize, and I think you're going in the right direction. It is probably the right time to consider generalizing so we don't end up with loads of methods on `EntitiesRepository` we replace later (as you say). However, I'd like to avoid passing SQL through as much as possible so any actual string query construction is kept to one place (`DatabaseEntitiesRepository`) and so that the API is still pretty rigid so we could go further. I think we're probably aiming to build our own fairly limited query language here to expand on what you've already got (which is going to be interesting). I'm just going to think out loud about how that could work here:

```kotlin
entitiesRepository.query(Eq("age", "34"))
entitiesRepository.query(NotEq("age", "52"))
entitiesRepository.query(And(Eq("age", "34"), NotEq("name", "Callum"))
```

I guess that would require a type hierarchy like:

```kotlin
sealed interface Query {
    class Eq(val column: String, val value: String): Query
    class NotEq(val column: String, val value: String): Query
    class And(val query1: Query, val query2: Query): Query
    class Or(val query1: Query, val query2: Query): Query
}
```

This would mean we'd support any length/depth of `and` or `or` XPath expressions though (and that's not something we need right now), so we could simplify it initially:

```kotlin
sealed interface Query {
    class And(val comparison1: Comparison, val comparison2: Comparison): Query
    class Or(val comparison1: Comparison, val comparison2: Comparison): Query

    sealed interface Comparison : Query {
        class Eq(val column: String, val value: String): Comparison
        class NotEq(val column: String, val value: String): Comparison
    }
}
```

What do you think?

2024-12-13 18:12 UTC, grzesiek2010 commented
> What do you think?

It looks nice but I'm not sure if generating expressions with multiple AND/OR would be easy. I will try to add support for it with the current approach and then introduce such an interface at the end of the process.

2024-12-13 18:32 UTC, seadowg commented
> It looks nice but I'm not sure if generating expressions with multiple AND/OR would be easy.

Do you mean generating `Query` or creating the SQL from it wouldn't be easy?

> I will try to add support for it with the current approach and then introduce such an interface at the end of the process.

That's fine, but I really do think we should make sure we end up with something structured rather than passing string SQL queries to the repository (but it doesn't have to be this type based tree representation approach - that's just one possibility). I'd be tempted to start with just replacing with the current `getByX` methods with something general and then build on top of that to add the new expressions. Remember we don't need to deal with mixed or nested and/or expressions at the moment as well.

2024-12-17 21:05 UTC, grzesiek2010 commented
> Do you mean generating Query or creating the SQL from it wouldn't be easy?

Yes but never mind I figured it out.

> That's fine, but I really do think we should make sure we end up with something structured rather than passing string SQL queries to the repository (but it doesn't have to be this type based tree representation approach - that's just one possibility).

I agree and it has been implemented.

> Remember we don't need to deal with mixed or nested and/or expressions at the moment as well.

Yes but I didn't want to waste time and this pull request should handle complex cases as well.

2024-12-18 13:58 UTC, seadowg requested changes
This is looking really cool! I wanted to dig into `Query` mainly at first. Two things:

1. I think we should make sure to separate the `Query` "language" from the "compiler" that turns it into SQL(ite) here. `Query` could live outside the `sqlite` package and then in `sqlite` (or somewhere else) we could have the logic that translates `Query` object to SQL.
2. We could theoretically get rid of the `getByX` methods on `EntitiesRepository` now right? They can just be replaced with `query` as far as I can see. Maybe that's better as a follow-up though?

One more thing is that it looks to me like you've added support for nested expressions here (like `value = thing and (value != blah and value != other)`) due to the recursion in `LocalEntitiesFilterStrategy#xPathExpressionToQuery`. That's very cool, but not something we need right now so if it makes 1 harder, I'd happily drop it for now.

2024-12-18 13:58 UTC, seadowg commented on entities/src/main/java/org/odk/collect/entities/storage/EntitiesRepository.kt
> +    fun query(list: String, query: Query?): List<Entity.Saved>
I don't `query` needs to be nullable here?

2024-12-21 11:35 UTC, grzesiek2010 commented
> I think we should make sure to separate the Query "language" from the "compiler" that turns it into SQL(ite) here. Query could live outside the sqlite package and then in sqlite (or somewhere else) we could have the logic that translates Query object to SQL.

Done.

> We could theoretically get rid of the getByX methods on EntitiesRepository now right? They can just be replaced with query as far as I can see. Maybe that's better as a follow-up though?

I think it would be better to do that in a separate pull request.

> One more thing is that it looks to me like you've added support for nested expressions here (like value = thing and (value != blah and value != other)) due to the recursion in LocalEntitiesFilterStrategy#xPathExpressionToQuery. That's very cool, but not something we need right now so if it makes 1 harder, I'd happily drop it for now.

That doesn't seem to be a problem and I still think it's easier to implement a complete and versatile solution in one pull request.

2025-01-07 16:39 UTC, seadowg requested changes

2025-01-07 16:39 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
> +        return queryWithAttachedRowId(list, query.mapColumns { columnName ->
I think the work `mapColumns` is doing here should happen in `LocalEntitiesInstanceAdapter#query` instead. `DatabaseEntitiesRepository` shouldn't have to know anything about the XForm representation of an entity and that would allow `EntityItemElement` to stay `internal`.

2025-01-07 16:39 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
> +    override fun query(list: String, query: Query): List<Entity.Saved> {
We discussed that this can now replace most of the rest of the interface in https://github.com/getodk/collect/pull/6539#issuecomment-2558090911, but that it'd make sense to remove them later. For the moment, how about we just deprecate the other methods with a `replaceWith` so it's clear?

2025-01-07 16:39 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
> +    fun `#query returns matching entities`() {
I think these tests can just use the simplest possible queries (like just a basic `Query.Eq`) given that `SqlQueryTest` covers the complexity of translating the objects to actual SQL.

2025-01-07 16:39 UTC, seadowg commented on entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt
> +            next.get()
It doesn't look like this path gets tested (from running with coverage). We need cases for non-optimized expressions (like functions) and for expressions where part of them isn't supported (for the two `else` clauses that return `null` in `xPathBoolExprToQuery` and `xPathEqExprToQuery`).

2025-01-07 19:25 UTC, grzesiek2010 commented on entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt
> +            next.get()
Actually, this code was redundant. We have a null check before calling this method and there is one test that covers this case: `works correctly with non eq name expressions`

2025-01-07 19:25 UTC, grzesiek2010 commented on collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
> +    fun `#query returns matching entities`() {
Done.

2025-01-07 19:25 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
> +    override fun query(list: String, query: Query): List<Entity.Saved> {
Done.

2025-01-07 19:30 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
> +        return queryWithAttachedRowId(list, query.mapColumns { columnName ->
The `LocalEntitiesInstanceAdapter` in the entities package would need to know the column names used by `DatabaseEntitiesRepository` in the app module, which isn't a proper way to organize things.

2025-01-08 08:45 UTC, seadowg commented on collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
> +        return queryWithAttachedRowId(list, query.mapColumns { columnName ->
Ah I see! So `EntitiesRepository` uses the same "column" names for `Query` objects it accepts. I had that backwards in my head. 

I don't like the idea that the `EntitiesRepostory` fields and the node names are defined in one place: they happen to be the same right now, but if we change one the other would break. Maybe we can make that less uncomfortable by just renaming `EntityItemElement` to something more general like `EntitySchema`?

2025-01-08 09:24 UTC, grzesiek2010 commented on collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
> +        return queryWithAttachedRowId(list, query.mapColumns { columnName ->
> Maybe we can make that less uncomfortable by just renaming EntityItemElement to something more general like EntitySchema?

Done.

2025-01-09 10:19 UTC, seadowg requested changes

2025-01-09 10:19 UTC, seadowg commented on entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt
> +    fun `returns matching nodes when id = value`() {
Definitely my fault here, but now most expressions are optimized, it's hard to get a quick sense of tests that check for optimized expressions and ones that don't. Maybe a quick set of renames around the theme of expressions that do or don't fall through would help?

I think once we get to optimizing all secondary instances, we'll most likely want to rework the tests or pull out something that just handles the XPath to `Query` translation, but I think doing that now feels over the top (even though it'd probably be more focused).

2025-01-09 12:51 UTC, grzesiek2010 commented on entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt
> +    fun `returns matching nodes when id = value`() {
Something like this https://github.com/getodk/collect/pull/6539/commits/870c23dfc793a1f3ed7e7f0c56b37573988fa70a?

2025-01-09 13:41 UTC, seadowg approved these changes

2025-01-09 13:41 UTC, merged

2025-01-16 12:19 UTC, WKobus commented
**Tested with success**

Verified on device with Android 15

**Verified cases:**

- Choice filters in big entity forms
- Entity forms with complex filters
- Check on filters in regular forms
- Pulldata forms

2025-01-16 12:21 UTC, dbemke commented
**Tested with success**

Verified on device with Android 10

2025-01-16 12:22 UTC, srujner commented
**Tested with success**

Verified on device with Android 14