Fixed the filtering of duplicate columns
getodk/collect pull request #6543
Opened 2024-12-08 12:24 UTC by grzesiek2010

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-12-09 12:03 UTC, seadowg requested changes

2024-12-09 12:03 UTC, seadowg commented on collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
> +         * Attempt to save again to ensure that duplicate properties are correctly compared,
I think we can break this into two test now as it feels like we're accounting for two distinct (but very related cases):

1. When an entity is created with duplicate case-insensitive properties
2. When an entity is created with a new property that's a case-insensitive duplicate of an existing one. 

So basically we can have one test that just checks saving something like:

```
val entity = Entity.New(
    "1",
    "One",
    properties = listOf(Pair("prop", "value"), Pair("Prop", "value"))
)
```

And another that checks saving a new entity to an existing list with a case-insensitive duplicate property like:

```
val repository = buildSubject()
val entity = Entity.New(
    "1",
    "One",
    properties = listOf(Pair("prop", "value"))
)

repository.save("things", entity)
var savedEntities = repository.getEntities("things")
assertThat(savedEntities[0].properties.size, equalTo(1))
assertThat(savedEntities[0].properties[0].first, equalTo("prop"))

repository.save("things", entity.copy(properties = listOf(Pair("Prop", "value"))))
savedEntities = repository.getEntities("things")
assertThat(savedEntities[0].properties.size, equalTo(1))
assertThat(savedEntities[0].properties[0].first, equalTo("prop"))
```

I'm pretty sure that'll drive out both the `distintBy` and the `filterNot` processing we have to do and give us different fails if one or the other is missing. Mainly though, I think it'll make it easier to understand the intended behaviour from the tests.

2024-12-09 12:54 UTC, seadowg approved these changes

2024-12-09 12:55 UTC, merged

2024-12-10 12:01 UTC, WKobus commented
**Tested with Success**

Verified on device with Android 15

**Verified cases:**
- Duplicate properties in entity registration form
- Duplicate properties in entity update form

2024-12-10 12:02 UTC, dbemke commented
**Tested with Success**

Verified on device with Android 10