Log form and CSV instance sizes when loading
getodk/collect pull request #6554
Opened 2024-12-18 13:21 UTC by seadowg

- **Log form and CSV instance sizes**
- **Log csv sizes individually**

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

2024-12-18 13:25 UTC, seadowg commented
@lognaturel I looked at not including entities CSVs, but it meant reworking more code to get `FormLoaderTask` access to an `EntitiesRepository`. I think given we're looking to see if small forms also cause OOMs, it shouldn't really matter if entity CSVs are included.

2024-12-18 17:29 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
> +            Timber.i(
We currently only send warnings and errors to Crashlytics which explains why the log lines we were seeing are warnings. See `CrashReportingTree`.

I think it's ok to use `w` for these even though they're not technically warnings. We don't expect these to stick around for very long.

2024-12-18 17:30 UTC, lognaturel requested changes
Informational logs won't make it to Crashlytics.

2024-12-19 17:18 UTC, lognaturel approved these changes

2024-12-19 17:18 UTC, merged