Fixes error when trying to upload GPS coordinate to Google Sheets
getodk/collect pull request #820
Opened 2017-04-03 17:21 UTC by shobhitagarwal1612

Fixes #819

2017-04-05 10:15 UTC, shobhitagarwal1612 commented
@lognaturel Please review

2017-04-05 15:57 UTC, lognaturel commented
@shobhitagarwal1612 You're welcome to tag the reviewers if you're not getting a review within 10 days but within that time frame, we are doing our best to review when we can!

In this case, my initial reaction is that I don't think this is the right approach. I want to give myself some more time to think about it and possibly offer an alternative, however.

2017-04-05 16:08 UTC, shobhitagarwal1612 commented
Sorry for being so impatient.
It was done in a hurry as I thought it needed an urgent fix so I did not think whether it's the best approach or not. It would be nice to have some opinion regarding a better solution.
Currently what I have done is check whether string matches the pattern for filename. I don't think so that the file formats that have to be uploaded have a full numeric extension but if the filename is a gps coordinate, then that would be a complete numeric.

2017-04-05 17:53 UTC, lognaturel commented
@shobhitagarwal1612 Unless we're somehow corrupting data or preventing use of a feature, we usually just wait until the next release. We'd make it super clear if something is urgent in some way. 😊

What I'm more worried about is that if my name is "foo.jpg", this fails. I wanted to double check it but had some trouble sending to sheets when I first looked at it. I think there has been some instability to that infrastructure recently. Next time I should just tell you what I think the problem is and you can look into it!

I think it would be good to look at the aggregate upload task and see how it determines what fields are files to send.

2017-04-05 18:04 UTC, shobhitagarwal1612 commented
That is a great idea. I'll check how it is being done in aggregate.
> What I'm more worried about is that if my name is "foo.jpg", this fails.
I have tested uploading all kinds of file types and it seemed to work for me. It was also able to distinguish GPS coordinate.

2017-04-05 18:46 UTC, lognaturel commented
Yes, but what if you enter a string with a .* pattern?? It tries to upload that and shows an error because it can't find it. A more realistic example might be that someone is filling out a report: "blah blah blah. And I also noticed...". No text field can have periods because they will be considered filenames.

2017-04-06 10:01 UTC, shobhitagarwal1612 commented
Using regex to check whether it's a file or not was a wrong choice. 
Now, i'm checking whether the path is a fie or not.

![screenshot_2017-04-06_15-29-37](https://cloud.githubusercontent.com/assets/8918023/24748663/0516b016-1ade-11e7-9b7e-be5a02f46d75.png)
![screenshot_2017-04-06_15-27-28](https://cloud.githubusercontent.com/assets/8918023/24748664/0517069c-1ade-11e7-805b-6816c49d9e7f.png)

2017-04-06 23:23 UTC, lognaturel requested changes
Yay, this works great. 😊 Small suggestion and then we're ready to go.

2017-04-06 23:23 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java
> +                                  HashMap<String, String> mediaToUpload, File instanceFile)
Here what you really need is the instance folder path, right? I'd pass in something like `File instanceFolder` and just call `getParentFile()` once when you make the call. That makes the intent a little bit clearer I think.

2017-04-07 19:12 UTC, merged