Issue #562: Added Firebase tree and Timber logging
getodk/collect pull request #821
Opened 2017-04-03 19:08 UTC by anudeepti2004

2017-04-03 20:41 UTC, lognaturel requested changes
Good start! I had to change the firebase dependencies version from 9.0.2 to 10.0.1 to match the other play services libraries or else it would crash.

One thing to look at across the board is style. You'll want to make sure that you're matching the guides described [here](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#style-guidelines). In particular, you'll want to review the sections on [horizontal whitespace](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace) and [braces](https://google.github.io/styleguide/javaguide.html#s4.1-braces).

The code should "breathe"! We put spaces before `{`, after `if`, `else` or other control statements, after `,` and so on.

In particular `Timber.e(e,e.getMessage());` should be `Timber.e(e, e, getMessage())`.

2017-04-03 20:41 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/application/Collect.java
> +            FirebaseCrash.logcat(Log.ERROR, tag, message);
If the log level is verbose or debug, nothing gets logged which makes sense. But if the log level is ASSERT, INFO or WARN in addition to ERROR, then the message will be logged as ERROR. That doesn't seem right to me. I don't think we need to log INFO events. I think ASSERT and WARN, if they're logged, should be shown at that level unless FirebaseCrash doesn't know about them.

2017-04-03 20:41 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java
> +        } catch ( XmlPullParserException |IOException | FormException e2) {
Spacing should be `catch (XmlPullParserException | IOException | FormException e2)`

2017-04-04 20:21 UTC, anudeepti2004 commented on collect_app/src/main/java/org/odk/collect/android/application/Collect.java
> +            FirebaseCrash.logcat(Log.ERROR, tag, message);
Got it. I will make the required changes

2017-04-05 16:27 UTC, nribeka commented on collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
> +                    Timber.e(e,"Client Protocol Exception "+((ClientProtocolException) e).getMessage());
I don't think you need to do type casting in any of this getMessage() calls.

2017-04-05 16:31 UTC, nribeka commented
A few general suggestions:
* Put space between params when calling the timber method.
* Use the string format approach instead of concatenating the string when generating the log message. So you want to call TImber.e(Throwable, S formattedMessage, Object ... args).

For example, instead of calling:
`Timber.e(e, "Exception happens here due to: " + e.getMessage());`

You would do:
`Timber.e(e, "Exception happens here due to: %s", e.getMessage())`

2017-04-05 16:34 UTC, nribeka commented
@anudeepti2004 the `catch(Throwable | Throwable | Throwable t)` is awesome!!

2017-04-05 21:14 UTC, anudeepti2004 commented on collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
> +                    Timber.e(e,"Client Protocol Exception "+((ClientProtocolException) e).getMessage());
Got it. I will remove the casts.

2017-04-06 00:22 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/application/Collect.java
> +            //Changed from Log.ERROR to priority below.
Great! But now I don't think this comment is needed. If you want to point something out to a reviewer you can add one of these kinds of GitHub comments that don't go in the code. 😊

2017-04-06 18:30 UTC, anudeepti2004 commented on collect_app/src/main/java/org/odk/collect/android/application/Collect.java
> +            //Changed from Log.ERROR to priority below.
Haha ok. Let me remove the comment. :)

2017-04-06 18:31 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/application/Collect.java
> +            //Changed from Log.ERROR to priority below.
🎉

2017-04-06 18:32 UTC, anudeepti2004 commented
@nribeka : Thanks. Thats very interesting I didnt know about the string formatting in TImber logging. Let me change the files.

2017-04-06 18:38 UTC, lognaturel commented
@anudeepti2004 If you're working on this now I can pause merging in any more changes while you make those changes and fix the merge conflicts.

2017-04-06 18:39 UTC, anudeepti2004 commented
@lognaturel : I am almost done. I am just doing the changes Nyoman requested.

2017-04-06 20:02 UTC, anudeepti2004 commented
@lognaturel : I committed the changes. I hope they are ok. :) Can you please review when you have the time?

2017-04-06 20:22 UTC, lognaturel commented
Great, will start reviewing now. In the mean time, can you please resolve the merge conflicts? https://help.github.com/articles/about-merge-conflicts/ and https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ have good explanations on how to do it.

2017-04-06 20:43 UTC, lognaturel requested changes
Looks good, thanks for making those style updates. 

I tried to mark all the redundant `Log` calls that should be removed. The point of using `Timber` is that in development mode it will use `Log` and in production it will use `Fire Crash`. There should no longer be any need for any call directly to `Log`!

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
>                  Log.e(TAG, e.getMessage(), e);
This `Log` should be replaced by the `Timber` call.

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/database/ItemsetDbAdapter.java
>              Log.e("MD5", e.getMessage());
`Log` call can be removed.

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java
>                      Log.e(TAG, e.getMessage(), e);
No more need for `Log`.

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java
>                  Log.e(TAG, e.getMessage(), e);
No more need for `Log`.

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
> +                        Timber.i(e, "Error encoding URL for devise id : %s due to : %s ", deviceId, e.getMessage());
device rather than devise

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.e(t, e.toString());
No more need for `Log`.

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.e(t, "Unable to encrypt the symmetric key");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.e(t, e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.e(t, "Unable to encrypt the symmetric key");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.w(t, "Unable to obtain BouncyCastle provider! Decryption may fail!");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.e(t, msg);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.e(t, msg);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>                  Log.e(t, msg);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
> +            Log.e(t, msg);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>              Log.e(t, msg, e);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
>              Log.e(t, msg);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
>                  Log.e(t, "Cannot read " + file.getName());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
>              Log.e(t, "Cannot find " + file.getName());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
>                  Log.e(t, "Cannot close input stream for " + file.getName());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
> +        } catch (NoSuchAlgorithmException | IOException e) {
No more need for `Log` calls

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
>                      Log.e(t, e.getMessage(), e);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
> +                Log.e(t, "FileNotFoundException while copying file", e);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
>              Log.w(t, "UTF 8 encoding unavailable, trying default encoding");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
>                      Log.w(t, xmlFile.getAbsolutePath() + " Error closing form reader");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
>                  Log.i(t, xmlFile.getAbsolutePath() + " does not have a submission element");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/InfoLogger.java
>              Log.e(t, "exception: " + e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
>              Log.e(t, e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
>              Log.e(t, e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
>              Log.e(t, e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
>              Log.e(t, e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
>              Log.e(t, e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
>              Log.e(t, e.toString());
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/WebUtils.java
>                  Log.e(t, error);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/utilities/WebUtils.java
>              Log.w(t, error);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/AudioButton.java
>                  Log.e(t, "Invalid reference exception");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/AudioButton.java
>                  Log.e(t, errorMsg);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
>                  Log.e(t, "Invalid reference exception");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
>                  Log.e(t, errorMsg);
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
>                  Log.e(t, "image invalid reference exception");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
>                      Log.e("GridMultiWidget", "image invalid reference exception");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/LabelWidget.java
>                          Log.e(t, "image invalid reference exception");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/ListMultiWidget.java
>                          Log.e(t, "image invalid reference exception");
No more need for `Log` call

2017-04-06 20:43 UTC, lognaturel commented on collect_app/src/main/java/org/odk/collect/android/widgets/ListWidget.java
>                          Log.e(t, "image invalid reference exception");
No more need for `Log` call

2017-04-07 16:32 UTC, anudeepti2004 commented
@lognaturel : Removed log statements and merged conflicts.

2017-04-07 18:10 UTC, lognaturel approved these changes

2017-04-07 18:11 UTC, merged

2017-04-07 18:11 UTC, lognaturel commented
Thank you @anudeepti2004!! 🎉🎉 This is a BIG deal and will really help us make sure we know what issues users are running into!

2017-04-07 18:45 UTC, anudeepti2004 commented
@lognaturel : Thank you so much for giving me the opportunity. I appreciate it. I really learned a lot and hope not repeat my mistakes.

2017-04-07 18:49 UTC, yanokwa commented
@anudeepti2004 Welcome to ODK and congrats on your first PR! It's going to make fixing bugs a lot easier going forward.

2017-04-07 18:53 UTC, anudeepti2004 commented
@yanokwa : Thank you :). Is there something I can start working on now that this is done?

2017-04-07 19:27 UTC, lognaturel commented
@anudeepti2004 I encourage you to look through the issues and see if any that aren't taken interest you. I also need to do a triage pass in the next few days and I'll let you know if I think of any that might be good!

2017-04-07 19:40 UTC, anudeepti2004 commented
Got it. Let me have a look.